// solid/src/ui/inputs/DateField.tsx
/**
 * Date field (spec/ui-standards/inputs.md › Date entry). Values are NaiveDate (YYYY-MM-DD).
 * Uses the native date control as an acceptable fallback (its displayed format follows the
 * OS locale; a DD/MM/YYYY picker is the ideal but out of scope here — flagged ⚠️ VERIFY in
 * the spec). Everywhere a date is *displayed* it is DD/MM/YYYY via `formatDate`.
 */
import { type JSX } from 'solid-js';
import { FieldShell } from './FieldShell';
import { fieldWidth } from './field-widths';

export interface DateFieldProps {
  label?: string;
  /** NaiveDate string YYYY-MM-DD (or null). */
  value: string | null | undefined;
  onChange?: (value: string | null) => void;
  disabled?: boolean;
  required?: boolean;
  error?: string;
  compact?: boolean;
  min?: string;
  max?: string;
  width?: string;
}

export function DateField(props: DateFieldProps): JSX.Element {
  const cls = () =>
    `control${props.compact ? ' control--compact' : ''}${props.error ? ' control--invalid' : ''}`;
  return (
    <FieldShell label={props.label} required={props.required} error={props.error} width={props.width ?? fieldWidth.date}>
      {({ inputId, describedBy }) => (
        <input
          id={inputId}
          class={cls()}
          type="date"
          value={props.value ?? ''}
          min={props.min}
          max={props.max}
          disabled={props.disabled}
          aria-invalid={props.error ? 'true' : undefined}
          aria-describedby={describedBy}
          onChange={(e) => props.onChange?.(e.currentTarget.value || null)}
        />
      )}
    </FieldShell>
  );
}

// svelte/src/lib/ui/inputs/DateField.svelte
<script lang="ts">
	import FieldShell from './FieldShell.svelte';
	import type { FieldWidth } from './field-widths';

	/**
	 * Date entry. Binds an ISO date-only string (YYYY-MM-DD), the shape the API
	 * uses (NaiveDate). Display format is browser/OS-controlled for the native
	 * picker; values are rendered DD/MM/YYYY elsewhere via format.ts.
	 * (Spec note: DD/MM/YYYY *input* display would need a custom picker — see Stage 2 notes.)
	 */
	let {
		value = $bindable(null),
		label,
		id,
		error,
		help,
		required = false,
		disabled = false,
		compact = false,
		width = 'date',
		onchange
	}: {
		value?: string | null;
		label?: string;
		id?: string;
		error?: string;
		help?: string;
		required?: boolean;
		disabled?: boolean;
		compact?: boolean;
		width?: FieldWidth | string;
		onchange?: (value: string | null) => void;
	} = $props();

	const auto = $props.id();
	const fieldId = $derived(id ?? auto);
</script>

<FieldShell {label} id={fieldId} {required} {error} {help} {width}>
	<input
		class="control"
		class:compact
		id={fieldId}
		type="date"
		bind:value
		{disabled}
		{required}
		aria-invalid={error ? 'true' : undefined}
		aria-describedby={error ? `${fieldId}-error` : help ? `${fieldId}-help` : undefined}
		onchange={() => onchange?.(value)}
	/>
</FieldShell>
