// react/src/components/Button.tsx
import { forwardRef, type ButtonHTMLAttributes, type ReactNode } from 'react';
import { Icon, type IconName } from '@/icons/Icon';
import './Button.css';

/**
 * Button variants per spec/ui-standards/controls.md#buttons:
 *  - primary: the one main action of a view (filled brand accent)
 *  - secondary: outlined / neutral surface
 *  - ghost: text-only, low emphasis
 *  - destructive: carries the error colour as its cue (divergence D7) + delete icon
 * At most one primary action visible per view. Every button shares the theme's
 * single button radius. A busy button shows progress and is non-interactive.
 */
export type ButtonVariant = 'primary' | 'secondary' | 'ghost' | 'destructive';
export type ButtonSize = 'default' | 'compact';

export interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: ButtonVariant;
  size?: ButtonSize;
  icon?: IconName;
  iconTrailing?: boolean;
  busy?: boolean;
  children?: ReactNode;
}

export const Button = forwardRef<HTMLButtonElement, ButtonProps>(function Button(
  {
    variant = 'secondary',
    size = 'default',
    icon,
    iconTrailing = false,
    busy = false,
    disabled,
    children,
    className,
    ...rest
  },
  ref,
) {
  const iconOnly = icon != null && children == null;
  const iconEl = busy ? (
    <Icon name="refresh" size={size === 'compact' ? 16 : 20} className="oms-btn__spin" />
  ) : icon ? (
    <Icon name={icon} size={size === 'compact' ? 16 : 20} />
  ) : null;

  return (
    <button
      ref={ref}
      type="button"
      disabled={disabled || busy}
      aria-busy={busy || undefined}
      className={[
        'oms-btn',
        `oms-btn--${variant}`,
        `oms-btn--${size}`,
        iconOnly ? 'oms-btn--icon-only' : '',
        className ?? '',
      ]
        .filter(Boolean)
        .join(' ')}
      {...rest}
    >
      {!iconTrailing && iconEl}
      {children != null && <span className="oms-btn__label">{children}</span>}
      {iconTrailing && iconEl}
    </button>
  );
});

// solid/src/ui/Button.tsx
import { type JSX, Show, splitProps } from 'solid-js';
import { Icon, type IconName } from './Icon';

/*
 * Buttons (controls.md#buttons). Variants: primary (one per view), secondary,
 * ghost, destructive. Destructive reads as dangerous via a red (error) icon on an
 * otherwise-neutral button, never colour alone. A busy button shows progress and
 * is non-interactive. Icon-only buttons require an accessible label. All buttons
 * share the theme's single button radius.
 */

export type ButtonVariant = 'primary' | 'secondary' | 'ghost' | 'destructive';

export interface ButtonProps
  extends Omit<JSX.ButtonHTMLAttributes<HTMLButtonElement>, 'children'> {
  variant?: ButtonVariant;
  icon?: IconName;
  label?: string;
  busy?: boolean;
  compact?: boolean;
  /** Accessible label for an icon-only button. */
  'aria-label'?: string;
}

export function Button(props: ButtonProps): JSX.Element {
  const [local, rest] = splitProps(props, [
    'variant',
    'icon',
    'label',
    'busy',
    'compact',
    'class',
    'disabled',
  ]);
  const variant = () => local.variant ?? 'secondary';
  const iconOnly = () => !local.label;
  return (
    <button
      type="button"
      {...rest}
      class={`btn btn-${variant()}${local.compact ? ' btn-compact' : ''}${
        iconOnly() ? ' btn-icon-only' : ''
      }${local.busy ? ' btn-busy' : ''}${local.class ? ` ${local.class}` : ''}`}
      disabled={local.disabled || local.busy}
      aria-busy={local.busy ? 'true' : undefined}
    >
      <Show when={local.busy}>
        <span class="btn-spinner" aria-hidden="true" />
      </Show>
      <Show when={local.icon && !local.busy}>
        <Icon name={local.icon!} size={local.compact ? 16 : 20} />
      </Show>
      <Show when={local.label}>
        <span class="btn-label">{local.label}</span>
      </Show>
    </button>
  );
}
