// react/src/components/Modal.tsx
import { useEffect, useRef, type ReactNode } from 'react';
import { createPortal } from 'react-dom';
import { Icon } from '@/icons/Icon';
import { Button } from './Button';
import './Modal.css';

/**
 * Modal / dialog layered above the whole frame for a focused sub-task
 * (spec/ui-standards/layout.md#modals--dialogs): owns its sub-task while open,
 * traps focus, dismisses on Escape / backdrop, returns focus to the trigger on close.
 */
interface ModalProps {
  open: boolean;
  onClose: () => void;
  title: string;
  children: ReactNode;
  /** Footer actions (rendered right-aligned). */
  footer?: ReactNode;
  /** Max content width. */
  size?: 'sm' | 'md' | 'lg';
  /** Disable backdrop-click dismissal (e.g. while saving). */
  dismissable?: boolean;
}

export function Modal({
  open,
  onClose,
  title,
  children,
  footer,
  size = 'md',
  dismissable = true,
}: ModalProps) {
  const dialogRef = useRef<HTMLDivElement>(null);
  const triggerRef = useRef<Element | null>(null);
  const titleId = useRef(`modal-${Math.random().toString(36).slice(2)}`).current;

  useEffect(() => {
    if (!open) return;
    triggerRef.current = document.activeElement;
    const dialog = dialogRef.current;

    // Focus the first focusable element (or the dialog itself).
    const focusables = dialog?.querySelectorAll<HTMLElement>(
      'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])',
    );
    (focusables?.[0] ?? dialog)?.focus();

    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && dismissable) {
        e.stopPropagation();
        onClose();
        return;
      }
      // Simple focus trap.
      if (e.key === 'Tab' && dialog) {
        const items = Array.from(
          dialog.querySelectorAll<HTMLElement>(
            'button:not(:disabled), [href], input:not(:disabled), select:not(:disabled), textarea:not(:disabled), [tabindex]:not([tabindex="-1"])',
          ),
        ).filter((el) => el.offsetParent !== null);
        if (items.length === 0) return;
        const first = items[0];
        const last = items[items.length - 1];
        if (e.shiftKey && document.activeElement === first) {
          e.preventDefault();
          last.focus();
        } else if (!e.shiftKey && document.activeElement === last) {
          e.preventDefault();
          first.focus();
        }
      }
    };
    document.addEventListener('keydown', onKey, true);
    const prevOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';

    return () => {
      document.removeEventListener('keydown', onKey, true);
      document.body.style.overflow = prevOverflow;
      // Return focus to the trigger on close.
      (triggerRef.current as HTMLElement | null)?.focus?.();
    };
  }, [open, onClose, dismissable]);

  if (!open) return null;

  return createPortal(
    <div
      className="oms-modal-scrim"
      onMouseDown={(e) => {
        if (dismissable && e.target === e.currentTarget) onClose();
      }}
    >
      <div
        ref={dialogRef}
        role="dialog"
        aria-modal="true"
        aria-labelledby={titleId}
        tabIndex={-1}
        className={`oms-modal oms-modal--${size}`}
      >
        <header className="oms-modal__head">
          <h2 id={titleId} className="oms-modal__title">
            {title}
          </h2>
          <Button
            variant="ghost"
            size="compact"
            icon="close"
            aria-label="Close"
            title="Close"
            onClick={onClose}
          />
        </header>
        <div className="oms-modal__body">{children}</div>
        {footer && <footer className="oms-modal__footer">{footer}</footer>}
      </div>
    </div>,
    document.body,
  );
}

/** Small convenience wrapper for the close (×) icon in a header, if needed elsewhere. */
export function CloseGlyph() {
  return <Icon name="close" size={20} />;
}

// solid/src/ui/Modal.tsx
import { Show, createEffect, onCleanup, type JSX } from 'solid-js';
import { Portal } from 'solid-js/web';
import { Icon } from './Icon';

/*
 * Modal / dialog (layout.md#modals--dialogs): layered above the whole frame for a
 * focused sub-task. Owns focus while open (trap) and returns focus to the trigger
 * on close. Backdrop uses surface.scrim; Escape closes unless suppressed (a dirty
 * modal guards its own close — the caller intercepts onClose).
 */

export interface ModalProps {
  open: boolean;
  onClose: () => void;
  title: string;
  children: JSX.Element;
  footer?: JSX.Element;
  /** small | medium | large — controls max width. */
  size?: 'sm' | 'md' | 'lg';
  /** Disable Escape / backdrop dismissal (e.g. while saving). */
  disableDismiss?: boolean;
  headerActions?: JSX.Element;
}

export function Modal(props: ModalProps): JSX.Element {
  let dialog: HTMLDivElement | undefined;

  createEffect(() => {
    if (!props.open) return;
    const previouslyFocused = document.activeElement as HTMLElement | null;

    requestAnimationFrame(() => {
      const focusable = dialog?.querySelector<HTMLElement>(
        'input, select, textarea, button, [href], [tabindex]:not([tabindex="-1"])',
      );
      (focusable ?? dialog)?.focus();
    });

    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && !props.disableDismiss) {
        e.stopPropagation();
        props.onClose();
        return;
      }
      if (e.key === 'Tab' && dialog) {
        const nodes = dialog.querySelectorAll<HTMLElement>(
          'input, select, textarea, button, [href], [tabindex]:not([tabindex="-1"])',
        );
        const items = Array.from(nodes).filter((n) => !n.hasAttribute('disabled'));
        if (items.length === 0) return;
        const first = items[0]!;
        const last = items[items.length - 1]!;
        if (e.shiftKey && document.activeElement === first) {
          e.preventDefault();
          last.focus();
        } else if (!e.shiftKey && document.activeElement === last) {
          e.preventDefault();
          first.focus();
        }
      }
    };
    document.addEventListener('keydown', onKey, true);
    const prevOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';

    onCleanup(() => {
      document.removeEventListener('keydown', onKey, true);
      document.body.style.overflow = prevOverflow;
      if (previouslyFocused && typeof previouslyFocused.focus === 'function') {
        previouslyFocused.focus();
      }
    });
  });

  return (
    <Show when={props.open}>
      <Portal>
        <div
          class="modal-scrim"
          onPointerDown={(e) => {
            if (e.target === e.currentTarget && !props.disableDismiss) props.onClose();
          }}
        >
          <div
            ref={dialog}
            class={`modal modal-${props.size ?? 'md'}`}
            role="dialog"
            aria-modal="true"
            aria-label={props.title}
            tabindex="-1"
          >
            <header class="modal-header">
              <h2 class="modal-title">{props.title}</h2>
              <div class="modal-header-actions">
                {props.headerActions}
                <button
                  type="button"
                  class="modal-close"
                  aria-label="Close"
                  onClick={() => props.onClose()}
                >
                  <Icon name="close" size={20} />
                </button>
              </div>
            </header>
            <div class="modal-body">{props.children}</div>
            <Show when={props.footer}>
              <footer class="modal-footer">{props.footer}</footer>
            </Show>
          </div>
        </div>
      </Portal>
    </Show>
  );
}
