// svelte/src/lib/components/Modal.svelte
<script lang="ts">
  // Dialog layered above the whole frame (spec ui-standards/layout.md › modals).
  // Scrim backdrop, Escape/close returns focus to the trigger, focus moves in on open.
  import type { Snippet } from 'svelte';
  import { portal } from '../util/portal';
  import Icon from './Icon.svelte';

  type Props = {
    open: boolean;
    title: string;
    size?: 'sm' | 'md' | 'lg';
    onclose: () => void;
    closeOnScrim?: boolean;
    children: Snippet;
    footer?: Snippet;
  };
  let { open, title, size = 'md', onclose, closeOnScrim = true, children, footer }: Props = $props();

  let dialog = $state<HTMLElement | null>(null);
  let opener: Element | null = null;

  $effect(() => {
    if (open) {
      opener = document.activeElement;
      requestAnimationFrame(() => {
        const focusable = dialog?.querySelector<HTMLElement>(
          'input, select, textarea, button, [tabindex]:not([tabindex="-1"])',
        );
        (focusable ?? dialog)?.focus();
      });
    } else if (opener instanceof HTMLElement) {
      opener.focus();
      opener = null;
    }
  });

  function onKey(e: KeyboardEvent) {
    if (open && e.key === 'Escape') {
      e.stopPropagation();
      onclose();
    }
  }
</script>

<svelte:window onkeydown={onKey} />

{#if open}
  <div class="scrim" use:portal>
    <button
      class="scrim-hit"
      aria-label="Close dialog"
      tabindex="-1"
      onclick={() => closeOnScrim && onclose()}
    ></button>
    <div
      class="modal modal--{size}"
      bind:this={dialog}
      role="dialog"
      aria-modal="true"
      aria-label={title}
      tabindex="-1"
    >
      <header class="modal__head">
        <h2>{title}</h2>
        <button class="close" aria-label="Close" onclick={onclose}>
          <Icon name="close" size={20} />
        </button>
      </header>
      <div class="modal__body">
        {@render children()}
      </div>
      {#if footer}
        <footer class="modal__foot">{@render footer()}</footer>
      {/if}
    </div>
  </div>
{/if}

<style>
  .scrim {
    position: fixed;
    inset: 0;
    z-index: var(--z-modal);
    background: var(--surface-scrim);
    display: flex;
    align-items: center;
    justify-content: center;
    padding: var(--sp-4);
  }
  .scrim-hit {
    position: absolute;
    inset: 0;
    border: 0;
    background: transparent;
    cursor: default;
  }
  .modal {
    position: relative;
    background: var(--surface-raised);
    color: var(--text-primary);
    border-radius: var(--radius-modal);
    box-shadow: var(--elev-overlay);
    width: 100%;
    max-height: 90vh;
    display: flex;
    flex-direction: column;
    overflow: hidden;
  }
  .modal--sm {
    max-width: 420px;
  }
  .modal--md {
    max-width: 640px;
  }
  .modal--lg {
    max-width: 900px;
  }
  .modal__head {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: var(--sp-4);
    border-bottom: 1px solid var(--divider);
  }
  .modal__head h2 {
    font-size: var(--type-heading-size);
  }
  .close {
    display: inline-flex;
    padding: var(--sp-1);
    border: 0;
    background: transparent;
    color: var(--text-secondary);
    cursor: pointer;
    border-radius: var(--radius-sm);
  }
  .close:hover {
    background: var(--hover-overlay);
  }
  .modal__body {
    padding: var(--sp-4);
    overflow-y: auto;
  }
  .modal__foot {
    display: flex;
    justify-content: flex-end;
    gap: var(--sp-2);
    padding: var(--sp-4);
    border-top: 1px solid var(--divider);
  }
</style>

// solid/src/ui/Modal.tsx
/**
 * Accessible modal dialog (spec/ui-standards/layout.md › Modals): scrim, Escape-to-close,
 * focus moves in on open and returns to the opener on close, a basic focus trap, and body
 * scroll lock. Rendered in a portal so it layers above the whole frame.
 */
import { type JSX, Show, createEffect, onCleanup } from 'solid-js';
import { Portal } from 'solid-js/web';
import { Icon } from './Icon';
import { Button } from './Button';

const FOCUSABLE = 'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])';

export interface ModalProps {
  open: boolean;
  title: string;
  onClose: () => void;
  width?: string;
  children: JSX.Element;
  footer?: JSX.Element;
}

export function Modal(props: ModalProps): JSX.Element {
  let dialog: HTMLDivElement | undefined;

  createEffect(() => {
    if (!props.open) return;
    const opener = document.activeElement as HTMLElement | null;
    queueMicrotask(() => {
      const first = dialog?.querySelector<HTMLElement>(FOCUSABLE);
      (first ?? dialog)?.focus();
    });
    const prevOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    onCleanup(() => {
      document.body.style.overflow = prevOverflow;
      opener?.focus?.();
    });
  });

  const onKeyDown = (e: KeyboardEvent) => {
    if (e.key === 'Escape') {
      e.preventDefault();
      props.onClose();
      return;
    }
    if (e.key === 'Tab' && dialog) {
      const items = [...dialog.querySelectorAll<HTMLElement>(FOCUSABLE)].filter((el) => !el.hasAttribute('disabled'));
      if (!items.length) return;
      const first = items[0]!;
      const last = items[items.length - 1]!;
      if (e.shiftKey && document.activeElement === first) {
        e.preventDefault();
        last.focus();
      } else if (!e.shiftKey && document.activeElement === last) {
        e.preventDefault();
        first.focus();
      }
    }
  };

  return (
    <Show when={props.open}>
      <Portal>
        <div class="scrim" onClick={() => props.onClose()} />
        <div
          class="modal"
          role="dialog"
          aria-modal="true"
          aria-label={props.title}
          tabindex={-1}
          ref={dialog}
          onKeyDown={onKeyDown}
          style={{ '--modal-w': props.width ?? '460px' }}
        >
          <header class="modal__header">
            <h2>{props.title}</h2>
            <button class="modal__close" type="button" aria-label="Close" onClick={() => props.onClose()}>
              <Icon name="close" size={18} />
            </button>
          </header>
          <div class="modal__body">{props.children}</div>
          <Show when={props.footer}>
            <footer class="modal__footer">{props.footer}</footer>
          </Show>
        </div>
      </Portal>
    </Show>
  );
}

export interface ConfirmDialogProps {
  open: boolean;
  title: string;
  message: JSX.Element;
  confirmLabel?: string;
  cancelLabel?: string;
  danger?: boolean;
  busy?: boolean;
  onConfirm: () => void;
  onCancel: () => void;
}

/** A yes/no confirmation over a Modal (logout, finalise, reduce-to-zero, …). */
export function ConfirmDialog(props: ConfirmDialogProps): JSX.Element {
  return (
    <Modal
      open={props.open}
      title={props.title}
      onClose={props.onCancel}
      footer={
        <>
          <Button variant="ghost" onClick={() => props.onCancel()}>
            {props.cancelLabel ?? 'Cancel'}
          </Button>
          <Button variant={props.danger ? 'danger' : 'primary'} busy={props.busy} onClick={() => props.onConfirm()}>
            {props.confirmLabel ?? 'Confirm'}
          </Button>
        </>
      }
    >
      <p style={{ margin: 0 }}>{props.message}</p>
    </Modal>
  );
}
