// react/src/components/StatusBadge.tsx
import './StatusBadge.css';

/**
 * Status shown with text + style, never colour alone (accessibility.md).
 * Tone maps to a state colour; the label is always present.
 */
export type BadgeTone = 'neutral' | 'info' | 'warning' | 'error' | 'success';

interface StatusBadgeProps {
  label: string;
  tone?: BadgeTone;
}

export function StatusBadge({ label, tone = 'neutral' }: StatusBadgeProps) {
  return <span className={`oms-badge oms-badge--${tone}`}>{label}</span>;
}

// solid/src/ui/StatusBadge.tsx
import { type JSX } from 'solid-js';

/*
 * Status badge — colour + label together, never colour alone
 * (accessibility.md#colour-independence).
 */

export type Tone = 'neutral' | 'info' | 'success' | 'warning' | 'error';

export function StatusBadge(props: { label: string; tone?: Tone }): JSX.Element {
  return <span class={`badge badge-${props.tone ?? 'neutral'}`}>{props.label}</span>;
}
