// react/src/components/StatusCrumbs.tsx
import { useRef, useState } from 'react';
import { Icon } from '@/icons/Icon';
import { Popover } from './Popover';
import { formatDateTime } from '@/lib/format';
import './StatusCrumbs.css';

/**
 * Generic lifecycle indicator per spec/ui-standards/controls.md#status-crumbs.
 * The vertical supplies its ordered statuses + the timestamp each reached one has.
 * Reached statuses are emphasised, not-yet-reached are muted; state is conveyed by
 * position + text, never colour alone. Revealing shows a history stepper (enhancement).
 */
export interface StatusStep {
  key: string;
  label: string;
  reachedAt?: string | null;
}

interface StatusCrumbsProps {
  steps: StatusStep[];
  currentKey: string;
}

export function StatusCrumbs({ steps, currentKey }: StatusCrumbsProps) {
  const [showHistory, setShowHistory] = useState(false);
  const triggerRef = useRef<HTMLButtonElement>(null);
  const currentIndex = steps.findIndex((s) => s.key === currentKey);
  const current = steps[currentIndex];

  const hasHistory = steps.some((s, i) => i <= currentIndex && s.reachedAt);

  return (
    <div className="oms-crumbs">
      <button
        ref={triggerRef}
        type="button"
        className="oms-crumbs__trigger"
        aria-label={`Status: ${current?.label ?? 'unknown'}. Show history.`}
        aria-expanded={showHistory}
        onClick={() => hasHistory && setShowHistory((v) => !v)}
      >
        {/* Full crumbs on wide screens */}
        <span className="oms-crumbs__full" aria-hidden="true">
          {steps.map((step, i) => {
            const reached = i <= currentIndex;
            return (
              <span key={step.key} className="oms-crumbs__item">
                {i > 0 && (
                  <Icon name="chevron-down" size={14} className="oms-crumbs__sep" />
                )}
                <span
                  className={`oms-crumbs__label${reached ? ' is-reached' : ''}${
                    i === currentIndex ? ' is-current' : ''
                  }`}
                >
                  {step.label}
                </span>
              </span>
            );
          })}
        </span>
        {/* Collapsed label on small screens */}
        <span className="oms-crumbs__collapsed">Status: {current?.label}</span>
      </button>

      {hasHistory && (
        <Popover
          anchorRef={triggerRef}
          open={showHistory}
          onClose={() => setShowHistory(false)}
          placement="top-start"
          role="dialog"
        >
          <ol className="oms-crumbs__history">
            {steps.map((step, i) => {
              const reached = i <= currentIndex;
              return (
                <li
                  key={step.key}
                  className={`oms-crumbs__hist-item${reached ? ' is-reached' : ''}`}
                >
                  <span className="oms-crumbs__hist-dot" aria-hidden="true" />
                  <span className="oms-crumbs__hist-label">{step.label}</span>
                  <span className="oms-crumbs__hist-time tabular">
                    {step.reachedAt ? formatDateTime(step.reachedAt) : '—'}
                  </span>
                </li>
              );
            })}
          </ol>
        </Popover>
      )}
    </div>
  );
}

// solid/src/ui/StatusCrumbs.tsx
import { createSignal, For, Show, type JSX } from 'solid-js';
import { Icon } from './Icon';
import { Popover } from './Popover';
import { isPhone } from '../state/viewport';
import { formatDateTime } from '../lib/format';

/*
 * Status crumbs (controls.md#status-crumbs-lifecycle-indicator): a generic, read-only
 * lifecycle indicator. The vertical supplies its ordered statuses and each reached
 * status's timestamp. Reached statuses are emphasised, not-yet-reached are muted, the
 * current status is the last reached. State is position + text, never colour alone.
 * Revealing (hover / focus / tap) shows WHEN each status was reached — an enhancement,
 * reachable by keyboard/touch. On small screens the row collapses to "Status: {current}".
 */

export interface CrumbStep {
  key: string;
  label: string;
  reachedAt?: string | null;
}

export interface StatusCrumbsProps {
  steps: CrumbStep[];
  /** Key of the current (last reached) status. */
  current: string;
}

export function StatusCrumbs(props: StatusCrumbsProps): JSX.Element {
  const [open, setOpen] = createSignal(false);
  let trigger: HTMLButtonElement | undefined;

  const currentIndex = () => props.steps.findIndex((s) => s.key === props.current);
  const reached = (i: number) => i <= currentIndex();
  const currentLabel = () => props.steps[currentIndex()]?.label ?? '';

  return (
    <div class="status-crumbs">
      <button
        ref={trigger}
        type="button"
        class="status-crumbs-trigger"
        aria-label={`Status: ${currentLabel()}. Show history`}
        aria-expanded={open()}
        onClick={() => setOpen((v) => !v)}
        onMouseEnter={() => setOpen(true)}
        onMouseLeave={() => setOpen(false)}
        onFocus={() => setOpen(true)}
        onBlur={() => setOpen(false)}
      >
        <Show
          when={!isPhone()}
          fallback={<span class="crumb crumb-current">Status: {currentLabel()}</span>}
        >
          <For each={props.steps}>
            {(step, i) => (
              <>
                <Show when={i() > 0}>
                  <Icon name="chevron-down" size={14} class="crumb-sep" />
                </Show>
                <span
                  class={`crumb${reached(i()) ? ' crumb-reached' : ' crumb-muted'}${
                    i() === currentIndex() ? ' crumb-current' : ''
                  }`}
                >
                  {step.label}
                </span>
              </>
            )}
          </For>
        </Show>
      </button>
      <Popover open={open()} anchor={trigger} onClose={() => setOpen(false)} role="tooltip">
        <ol class="crumb-history">
          <For each={props.steps}>
            {(step, i) => (
              <li class={`crumb-history-item${reached(i()) ? ' reached' : ''}`}>
                <span class="crumb-history-dot" aria-hidden="true" />
                <span class="crumb-history-label">{step.label}</span>
                <span class="crumb-history-time tabular">
                  {step.reachedAt ? formatDateTime(step.reachedAt) : reached(i()) ? '' : '—'}
                </span>
              </li>
            )}
          </For>
        </ol>
      </Popover>
    </div>
  );
}
