// svelte/src/lib/components/StatusCrumbs.svelte
<script lang="ts">
  // Lifecycle indicator (spec ui-standards/controls.md › status crumbs). Ordered
  // statuses separated by a forward chevron (flips under RTL); reached statuses are
  // emphasised, not-yet-reached muted. State conveyed by position + text, never colour
  // alone. Revealing (hover/focus/tap) shows when each reached status occurred.
  import Icon from './Icon.svelte';
  import { formatDateTime } from '../util/format';

  export type Crumb = { key: string; label: string; reachedAt?: string | null };

  type Props = { crumbs: Crumb[]; currentKey: string };
  let { crumbs, currentKey }: Props = $props();

  let currentIndex = $derived(crumbs.findIndex((c) => c.key === currentKey));
  let showHistory = $state(false);
</script>

<div
  class="crumbs"
  role="button"
  aria-label="Status: {crumbs[currentIndex]?.label}. Show history."
  tabindex="0"
  onmouseenter={() => (showHistory = true)}
  onmouseleave={() => (showHistory = false)}
  onfocus={() => (showHistory = true)}
  onblur={() => (showHistory = false)}
>
  {#each crumbs as crumb, i (crumb.key)}
    {#if i > 0}<span class="sep"><Icon name="chevron-down" size={14} /></span>{/if}
    <span class="crumb" class:reached={i <= currentIndex} class:current={i === currentIndex}>
      {crumb.label}
    </span>
  {/each}

  {#if showHistory}
    <div class="history" role="tooltip">
      {#each crumbs as crumb (crumb.key)}
        <div class="history__row" class:muted={!crumb.reachedAt}>
          <span>{crumb.label}</span>
          <span class="tnum">{crumb.reachedAt ? formatDateTime(crumb.reachedAt) : '—'}</span>
        </div>
      {/each}
    </div>
  {/if}
</div>

<style>
  .crumbs {
    position: relative;
    display: inline-flex;
    align-items: center;
    gap: var(--sp-1);
    padding: var(--sp-1) var(--sp-2);
    border-radius: var(--radius-sm);
    cursor: default;
  }
  .crumb {
    font-size: var(--type-body-size);
    color: var(--text-disabled);
  }
  .crumb.reached {
    color: var(--brand-primary);
    font-weight: var(--type-emphasis-weight);
  }
  .crumb.current {
    text-decoration: underline;
    text-underline-offset: 3px;
  }
  .sep {
    color: var(--text-disabled);
    display: inline-flex;
    transform: rotate(-90deg);
  }
  :global([dir='rtl']) .sep {
    transform: rotate(90deg);
  }
  .history {
    position: absolute;
    bottom: calc(100% + 6px);
    left: 0;
    z-index: var(--z-popover);
    background: var(--surface-raised);
    border: 1px solid var(--border-default);
    border-radius: var(--radius-control);
    box-shadow: var(--elev-raised);
    padding: var(--sp-2);
    min-width: 220px;
  }
  .history__row {
    display: flex;
    justify-content: space-between;
    gap: var(--sp-4);
    padding: var(--sp-1) var(--sp-2);
    font-size: var(--type-caption-size);
  }
  .history__row.muted {
    color: var(--text-disabled);
  }
</style>

// solid/src/ui/StatusCrumbs.tsx
import { createSignal, For, Show, type JSX } from 'solid-js';
import { Icon } from './Icon';
import { Popover } from './Popover';
import { isPhone } from '../state/viewport';
import { formatDateTime } from '../lib/format';

/*
 * Status crumbs (controls.md#status-crumbs-lifecycle-indicator): a generic, read-only
 * lifecycle indicator. The vertical supplies its ordered statuses and each reached
 * status's timestamp. Reached statuses are emphasised, not-yet-reached are muted, the
 * current status is the last reached. State is position + text, never colour alone.
 * Revealing (hover / focus / tap) shows WHEN each status was reached — an enhancement,
 * reachable by keyboard/touch. On small screens the row collapses to "Status: {current}".
 */

export interface CrumbStep {
  key: string;
  label: string;
  reachedAt?: string | null;
}

export interface StatusCrumbsProps {
  steps: CrumbStep[];
  /** Key of the current (last reached) status. */
  current: string;
}

export function StatusCrumbs(props: StatusCrumbsProps): JSX.Element {
  const [open, setOpen] = createSignal(false);
  let trigger: HTMLButtonElement | undefined;

  const currentIndex = () => props.steps.findIndex((s) => s.key === props.current);
  const reached = (i: number) => i <= currentIndex();
  const currentLabel = () => props.steps[currentIndex()]?.label ?? '';

  return (
    <div class="status-crumbs">
      <button
        ref={trigger}
        type="button"
        class="status-crumbs-trigger"
        aria-label={`Status: ${currentLabel()}. Show history`}
        aria-expanded={open()}
        onClick={() => setOpen((v) => !v)}
        onMouseEnter={() => setOpen(true)}
        onMouseLeave={() => setOpen(false)}
        onFocus={() => setOpen(true)}
        onBlur={() => setOpen(false)}
      >
        <Show
          when={!isPhone()}
          fallback={<span class="crumb crumb-current">Status: {currentLabel()}</span>}
        >
          <For each={props.steps}>
            {(step, i) => (
              <>
                <Show when={i() > 0}>
                  <Icon name="chevron-down" size={14} class="crumb-sep" />
                </Show>
                <span
                  class={`crumb${reached(i()) ? ' crumb-reached' : ' crumb-muted'}${
                    i() === currentIndex() ? ' crumb-current' : ''
                  }`}
                >
                  {step.label}
                </span>
              </>
            )}
          </For>
        </Show>
      </button>
      <Popover open={open()} anchor={trigger} onClose={() => setOpen(false)} role="tooltip">
        <ol class="crumb-history">
          <For each={props.steps}>
            {(step, i) => (
              <li class={`crumb-history-item${reached(i()) ? ' reached' : ''}`}>
                <span class="crumb-history-dot" aria-hidden="true" />
                <span class="crumb-history-label">{step.label}</span>
                <span class="crumb-history-time tabular">
                  {step.reachedAt ? formatDateTime(step.reachedAt) : reached(i()) ? '' : '—'}
                </span>
              </li>
            )}
          </For>
        </ol>
      </Popover>
    </div>
  );
}
