// solid/src/chrome/Sidebar.tsx
/**
 * Desktop primary nav (spec/chrome/01-behaviours.md › Sidebar). Collapsible expanded ↔
 * icon-rail via an explicit toggle (no hover-to-peek — divergence D3); the choice persists.
 * Two data-driven groups (upper scrollable, lower). Active item reflects the route. Hidden
 * in full-screen mode (handled by AppShell).
 */
import { type JSX, For, Show } from 'solid-js';
import { A, useLocation } from '@solidjs/router';
import { Icon } from '../ui/Icon';
import { chrome } from '../state/chrome';
import { navGroups, isActive, type NavGroup, type NavItem } from './nav-config';

function NavLink(props: { item: NavItem; pathname: string }): JSX.Element {
  const active = () => isActive(props.item.route, props.pathname);
  return (
    <A
      href={props.item.route}
      class={`nav-item${active() ? ' nav-item--active' : ''}`}
      title={chrome.collapsed ? props.item.label : undefined}
      aria-current={active() ? 'page' : undefined}
    >
      <Icon name={props.item.icon} size={22} />
      <span class="nav-item__label">{props.item.label}</span>
    </A>
  );
}

export function Sidebar(): JSX.Element {
  const location = useLocation();
  const visibleItems = (g: NavGroup) => g.items.filter((i) => i.visible?.() ?? true);

  let brandRef: HTMLButtonElement | undefined;
  // The brand mark is the collapse/expand toggle; activating it plays a single 360° spin
  // whose direction echoes the change (spec/chrome/01 › Sidebar). Decorative — suppressed
  // under a reduced-motion preference.
  const toggle = () => {
    const collapsing = !chrome.collapsed;
    chrome.toggle();
    const reduce = typeof window !== 'undefined' && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    if (!reduce && brandRef?.animate) {
      brandRef.animate([{ transform: 'rotate(0deg)' }, { transform: `rotate(${collapsing ? -360 : 360}deg)` }], {
        duration: 450,
        easing: 'ease-in-out'
      });
    }
  };

  return (
    <nav class={`sidebar${chrome.collapsed ? ' sidebar--collapsed' : ''}`} aria-label="Primary">
      <div class="sidebar__brand">
        <button
          ref={brandRef}
          class="sidebar__brand-btn"
          type="button"
          aria-label={chrome.collapsed ? 'Open the menu' : 'Close the menu'}
          aria-expanded={!chrome.collapsed}
          onClick={toggle}
        >
          <Icon name="m-supply-guy" size={30} />
        </button>
      </div>
      <For each={navGroups}>
        {(group) => (
          <Show when={visibleItems(group).length}>
            <div class={`sidebar__group sidebar__group--${group.id}`}>
              <For each={visibleItems(group)}>{(item) => <NavLink item={item} pathname={location.pathname} />}</For>
            </div>
          </Show>
        )}
      </For>
    </nav>
  );
}

// react/src/app/chrome/Sidebar.tsx
import { useRef, useState } from 'react';
import { NavLink } from 'react-router-dom';
import { Icon } from '@/icons/Icon';
import { useAuth } from '@/app/auth/AuthContext';
import { useTranslation } from '@/app/i18n/i18n';
import { NAV_SECTIONS, type NavSection } from './navConfig';
import './Sidebar.css';

/**
 * Desktop primary nav (spec/chrome/01-behaviours.md#sidebar):
 *  - Expanded (icon + label) ↔ collapsed icon rail; width animates.
 *  - The brand mark IS the toggle (no separate menu button); it plays a single
 *    360° spin on activation (direction echoes the change), suppressed under
 *    reduced-motion. Hover changes nothing (divergence D3).
 *  - Sections split into upper (scrollable) + lower groups; gated by permission.
 *  - Hidden in full-screen mode (handled by the parent).
 */
interface SidebarProps {
  collapsed: boolean;
  onToggle: () => void;
}

export function Sidebar({ collapsed, onToggle }: SidebarProps) {
  const { hasPermission } = useAuth();
  const t = useTranslation();
  const [spin, setSpin] = useState<{ dir: 'cw' | 'ccw'; n: number }>({ dir: 'cw', n: 0 });
  const brandRef = useRef<HTMLButtonElement>(null);

  const handleToggle = () => {
    // Spin one way when expanding, the other when collapsing.
    setSpin((s) => ({ dir: collapsed ? 'cw' : 'ccw', n: s.n + 1 }));
    onToggle();
  };

  const visible = NAV_SECTIONS.filter((s) => !s.permission || hasPermission(s.permission));
  const upper = visible.filter((s) => s.group === 'upper');
  const lower = visible.filter((s) => s.group === 'lower');

  return (
    <nav
      className={`oms-sidebar${collapsed ? ' is-collapsed' : ''}`}
      aria-label="Primary navigation"
    >
      <div className="oms-sidebar__brand-band">
        <button
          ref={brandRef}
          type="button"
          className="oms-sidebar__brand"
          aria-label={collapsed ? 'Open the menu' : 'Close the menu'}
          aria-expanded={!collapsed}
          onClick={handleToggle}
        >
          <span
            key={spin.n}
            className={`oms-sidebar__brand-mark oms-sidebar__brand-mark--${spin.dir}${
              spin.n > 0 ? ' is-spinning' : ''
            }`}
          >
            <Icon name="m-supply-guy" size={collapsed ? 32 : 40} />
          </span>
        </button>
      </div>

      <div className="oms-sidebar__scroll">
        <ul className="oms-sidebar__group">
          {upper.map((section) => (
            <SidebarItem key={section.key} section={section} collapsed={collapsed} label={t(section.labelKey)} />
          ))}
        </ul>
      </div>

      <ul className="oms-sidebar__group oms-sidebar__group--lower">
        {lower.map((section) => (
          <SidebarItem key={section.key} section={section} collapsed={collapsed} label={t(section.labelKey)} />
        ))}
      </ul>
    </nav>
  );
}

function SidebarItem({
  section,
  collapsed,
  label,
}: {
  section: NavSection;
  collapsed: boolean;
  label: string;
}) {
  return (
    <li>
      <NavLink
        to={section.path}
        className={({ isActive }) => `oms-sidebar__link${isActive ? ' is-active' : ''}`}
        title={collapsed ? label : undefined}
      >
        <Icon name={section.icon} size={24} className="oms-sidebar__link-icon" />
        <span className="oms-sidebar__link-label">{label}</span>
      </NavLink>
    </li>
  );
}
