// svelte/src/lib/chrome/AppShell.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';
	import { page } from '$app/state';
	import Sidebar from './Sidebar.svelte';
	import MobileNav from './MobileNav.svelte';
	import BottomBar from './BottomBar.svelte';
	import { chrome } from './chrome.svelte';
	import { auth } from '$lib/auth/auth.svelte';
	import { viewport, BP } from '$lib/ui/viewport.svelte';

	let { children }: { children: Snippet } = $props();

	// Below the tablet-landscape breakpoint we use the mobile top-bar + drawer
	// instead of the sidebar (chrome/00 › Regions).
	const isMobile = $derived(viewport.below(BP.desktop));

	onMount(() => {
		chrome.init();
		auth.init();
	});

	// Auth gate: unauthenticated users are routed to login, not shown the chrome (AC-CH15).
	$effect(() => {
		if (!auth.isAuthenticated && page.url.pathname !== '/login') goto('/login');
	});

	// Responsive sidebar default until the user overrides it (AC-CH2).
	$effect(() => {
		chrome.applyResponsiveDefault(viewport.below(BP.desktop));
	});
</script>

{#if auth.isAuthenticated}
	<div class="shell" class:fullscreen={chrome.fullscreen}>
		{#if !chrome.fullscreen}
			{#if isMobile}
				<MobileNav />
			{:else}
				<Sidebar />
			{/if}
		{/if}

		<div class="main">
			<main>{@render children()}</main>
			{#if !chrome.fullscreen}<BottomBar />{/if}
		</div>
	</div>
{/if}

<style>
	.shell {
		display: flex;
		height: 100vh;
		overflow: hidden;
		background: var(--surface-base);
	}
	/* Mobile: the top bar stacks above content rather than sitting beside it. */
	@media (max-width: 1099px) {
		.shell {
			flex-direction: column;
		}
	}
	.main {
		display: flex;
		flex-direction: column;
		flex: 1;
		min-width: 0;
		min-height: 0;
	}
	main {
		flex: 1;
		overflow: auto;
		padding: var(--space-5);
	}
	.fullscreen main {
		padding: 0;
	}
</style>

// solid/src/chrome/AppShell.tsx
/**
 * The application shell (spec/chrome). Composes the sidebar + section top bar (desktop) or
 * the mobile nav bar (< tablet-portrait), the routed page content, and the persistent bottom
 * bar. The sidebar auto-collapses on medium-and-smaller viewports until the user overrides
 * (AC-CH2) and is hidden in full-screen mode (AC-CH16).
 */
import { type JSX, Show, createEffect, onMount } from 'solid-js';
import { Sidebar } from './Sidebar';
import { TopBar } from './TopBar';
import { BottomBar } from './BottomBar';
import { MobileNav } from './MobileNav';
import { chrome } from '../state/chrome';
import { auth } from '../state/auth';
import { i18n } from '../state/i18n';
import { viewport, BP } from '../state/viewport';

export function AppShell(props: { children: JSX.Element }): JSX.Element {
  onMount(() => {
    chrome.init();
    auth.init();
    i18n.init();
  });

  const isMobile = () => viewport.below(BP.tabletPortrait);

  // Responsive sidebar default: collapse on medium-and-smaller until the user overrides.
  createEffect(() => chrome.applyResponsiveDefault(viewport.below(BP.desktop)));

  return (
    <div class="shell">
      {/* Sidebar spans the full height on the left; the bottom bar lives inside the content
          column (right of the sidebar), per layout.md — it does not span the bottom-left. */}
      <Show when={!isMobile() && !chrome.fullscreen}>
        <Sidebar />
      </Show>
      <div class="shell__content">
        <Show when={isMobile()} fallback={<TopBar />}>
          <MobileNav />
        </Show>
        <main class="shell__routed">{props.children}</main>
        <BottomBar />
      </div>
    </div>
  );
}
