// svelte/src/lib/chrome/MobileNav.svelte
<script lang="ts">
	import { page } from '$app/state';
	import { goto } from '$app/navigation';
	import Icon from '$lib/icons/Icon.svelte';
	import Modal from '$lib/ui/Modal.svelte';
	import Button from '$lib/ui/Button.svelte';
	import { auth } from '$lib/auth/auth.svelte';
	import { navGroups, isActive } from './nav-config';

	let open = $state(false);
	let confirmingLogout = $state(false);

	const allItems = $derived(
		navGroups.flatMap((g) => g.items).filter((i) => !i.visible || i.visible())
	);

	const crumb = $derived(
		allItems.find((i) => isActive(i.route, page.url.pathname))?.label ?? 'open mSupply'
	);

	function navigate(route: string) {
		open = false;
		goto(route);
	}
	function confirmLogout() {
		confirmingLogout = false;
		auth.logout();
		goto('/login');
	}
</script>

<div class="topbar">
	<button
		class="menu-toggle"
		type="button"
		aria-label={open ? 'Close menu' : 'Open menu'}
		aria-expanded={open}
		onclick={() => (open = !open)}
	>
		<Icon name={open ? 'close' : 'list'} size={24} />
	</button>
	<span class="crumb">{crumb}</span>
	<span class="brand"><Icon name="m-supply-guy" size={28} /></span>
</div>

{#if open}
	<!-- svelte-ignore a11y_click_events_have_key_events, a11y_no_static_element_interactions -->
	<div class="drawer-scrim" onclick={() => (open = false)}></div>
	<nav class="drawer" aria-label="Primary">
		<ul>
			{#each allItems as item (item.route)}
				<li>
					<a
						href={item.route}
						class:active={isActive(item.route, page.url.pathname)}
						onclick={(e) => {
							e.preventDefault();
							navigate(item.route);
						}}
					>
						<span class="icon"><Icon name={item.icon} size={20} /></span>{item.label}
					</a>
				</li>
			{/each}
			<li class="sep"></li>
			<li>
				<a href="https://docs.msupply.foundation" target="_blank" rel="noopener">
					<span class="icon"><Icon name="book" size={20} /></span>Docs
					<Icon name="external-link" size={14} flipRtl />
				</a>
			</li>
			<li>
				<button type="button" onclick={() => (confirmingLogout = true)}>
					<span class="icon"><Icon name="power" size={20} /></span>Log out
				</button>
			</li>
		</ul>
	</nav>
{/if}

<Modal bind:open={confirmingLogout} title="Log out?" width="400px">
	Are you sure you want to log out?
	{#snippet footer()}
		<Button variant="ghost" onclick={() => (confirmingLogout = false)}>Cancel</Button>
		<Button variant="primary" onclick={confirmLogout}>Log out</Button>
	{/snippet}
</Modal>

<style>
	.topbar {
		display: flex;
		align-items: center;
		gap: var(--space-3);
		height: 56px;
		padding: 0 var(--space-3);
		background: var(--surface-nav);
		border-bottom: 1px solid var(--border-default);
	}
	.menu-toggle {
		width: var(--touch-target);
		height: var(--touch-target);
		border: 0;
		background: transparent;
		color: var(--text-primary);
		font-size: 20px;
		cursor: pointer;
		border-radius: var(--radius-sm);
	}
	.crumb {
		flex: 1;
		font-weight: 600;
	}
	.brand {
		display: grid;
		place-items: center;
	}
	.drawer-scrim {
		position: fixed;
		inset: 56px 0 0;
		background: var(--surface-scrim);
		z-index: var(--z-sidebar);
	}
	.drawer {
		position: fixed;
		top: 56px;
		inset-inline: 0;
		max-height: calc(100vh - 56px);
		overflow-y: auto;
		background: var(--surface-raised);
		border-bottom: 1px solid var(--border-default);
		box-shadow: var(--shadow-popover);
		z-index: var(--z-sidebar);
		animation: slide-down var(--transition);
	}
	@keyframes slide-down {
		from {
			transform: translateY(-8px);
			opacity: 0;
		}
	}
	ul {
		list-style: none;
		margin: 0;
		padding: var(--space-2);
	}
	.sep {
		height: 1px;
		background: var(--divider);
		margin: var(--space-2) 0;
	}
	a,
	li button {
		display: flex;
		align-items: center;
		gap: var(--space-3);
		width: 100%;
		min-height: var(--touch-target);
		padding: 0 var(--space-3);
		border: 0;
		background: transparent;
		border-radius: var(--radius-control);
		color: var(--text-primary);
		text-decoration: none;
		font: inherit;
		text-align: start;
		cursor: pointer;
	}
	a:hover,
	li button:hover {
		background: var(--hover-overlay);
	}
	a.active {
		background: var(--brand-primary-subtle);
		color: var(--brand-primary);
		font-weight: 600;
	}
	.icon {
		width: 24px;
		text-align: center;
	}
</style>

// solid/src/chrome/MobileNav.tsx
/**
 * Mobile / tablet nav (spec/chrome/01-behaviours.md › Mobile / tablet nav). A top bar with a
 * menu toggle (open/close glyph from the custom set — divergence D4: `menu-dots` ↔ `close`),
 * the current section as breadcrumb, and the brand mark. The menu opens a slide-down drawer
 * with the nav links plus Docs (external), Sync, Settings (permission-gated), and Logout.
 */
import { type JSX, For, Show, createMemo, createSignal } from 'solid-js';
import { A, useLocation, useNavigate } from '@solidjs/router';
import { Icon } from '../ui/Icon';
import { ConfirmDialog } from '../ui/Modal';
import { auth } from '../state/auth';
import { navGroups, activeNavItem, isActive } from './nav-config';

export function MobileNav(): JSX.Element {
  const [open, setOpen] = createSignal(false);
  const [confirm, setConfirm] = createSignal(false);
  const location = useLocation();
  const navigate = useNavigate();
  const section = createMemo(() => activeNavItem(location.pathname));
  const items = createMemo(() => navGroups.flatMap((g) => g.items).filter((i) => i.visible?.() ?? true));

  const doLogout = () => {
    setConfirm(false);
    setOpen(false);
    auth.logout();
    navigate('/login');
  };

  return (
    <>
      <div class="mobile-bar">
        <button
          class="icon-btn icon-btn--plain"
          type="button"
          aria-label={open() ? 'Close menu' : 'Open menu'}
          aria-expanded={open()}
          onClick={() => setOpen(!open())}
        >
          <Icon name={open() ? 'close' : 'menu-dots'} size={22} />
        </button>
        <span style={{ 'font-weight': 600 }}>{section()?.label ?? 'open mSupply'}</span>
        <span class="mobile-bar__brand">
          <Icon name="m-supply-guy" size={26} />
        </span>
      </div>

      <Show when={open()}>
        <div class="mobile-drawer">
          <div class="mobile-drawer__scrim" onClick={() => setOpen(false)} />
          <nav class="mobile-drawer__panel" aria-label="Primary">
            <ul class="menu" style={{ 'max-height': 'none' }}>
              <For each={items()}>
                {(item) => (
                  <li role="none">
                    <A
                      href={item.route}
                      class={`menu-item${isActive(item.route, location.pathname) ? ' menu-item--selected' : ''}`}
                      onClick={() => setOpen(false)}
                    >
                      <Icon name={item.icon} size={20} />
                      <span class="menu-item__label">{item.label}</span>
                    </A>
                  </li>
                )}
              </For>
              <li role="none">
                <a class="menu-item" href="https://docs.msupply.foundation" target="_blank" rel="noreferrer">
                  <Icon name="book" size={20} />
                  <span class="menu-item__label">Docs</span>
                  <Icon name="external-link" size={14} />
                </a>
              </li>
              <li role="none">
                <A href="/sync" class="menu-item" onClick={() => setOpen(false)}>
                  <Icon name="radio" size={20} />
                  <span class="menu-item__label">Sync</span>
                </A>
              </li>
              <Show when={auth.can('ServerAdmin') || auth.can('EditStore')}>
                <li role="none">
                  <A href="/settings" class="menu-item" onClick={() => setOpen(false)}>
                    <Icon name="settings" size={20} />
                    <span class="menu-item__label">Settings</span>
                  </A>
                </li>
              </Show>
              <li role="none">
                <button type="button" class="menu-item" onClick={() => setConfirm(true)}>
                  <Icon name="power" size={20} />
                  <span class="menu-item__label">Logout</span>
                </button>
              </li>
            </ul>
          </nav>
        </div>
      </Show>

      <ConfirmDialog
        open={confirm()}
        title="Log out?"
        message="You will be returned to the login screen."
        confirmLabel="Log out"
        onConfirm={doLogout}
        onCancel={() => setConfirm(false)}
      />
    </>
  );
}
