// react/src/app/layout/PageLayout.tsx
import type { ReactNode } from 'react';
import './PageLayout.css';

/**
 * Shared page anatomy per spec/ui-standards/layout.md. Regions in stacking order:
 *  - App bar / toolbar: title/metadata + page actions + filter/search (stays put)
 *  - Content body: the only region that scrolls; scales to large data sets
 *  - Action footer: lifecycle actions; STAYS VISIBLE regardless of body scroll
 *  - Detail side panel: toggleable; beside the body on wide screens, overlay when narrow
 * Order and roles are preserved responsively.
 */
interface PageLayoutProps {
  appBar?: ReactNode;
  children: ReactNode;
  footer?: ReactNode;
  sidePanel?: ReactNode;
  sidePanelOpen?: boolean;
  /** Remove body padding (e.g. a full-bleed table). */
  flushBody?: boolean;
}

export function PageLayout({
  appBar,
  children,
  footer,
  sidePanel,
  sidePanelOpen = false,
  flushBody = false,
}: PageLayoutProps) {
  return (
    <div className="oms-page">
      {appBar && <div className="oms-page__appbar">{appBar}</div>}
      <div className="oms-page__mid">
        <div className={`oms-page__body${flushBody ? ' is-flush' : ''}`}>{children}</div>
        {sidePanel && sidePanelOpen && (
          <aside className="oms-page__side" aria-label="Details">
            {sidePanel}
          </aside>
        )}
      </div>
      {footer && <div className="oms-page__footer">{footer}</div>}
    </div>
  );
}

// solid/src/chrome/PageLayout.tsx
/**
 * Standard page anatomy (spec/ui-standards/layout.md): an app-bar/toolbar (title, metadata
 * entry points, page actions, filter/search), a single scrolling content body, an optional
 * toggleable detail side panel (overlay on narrow viewports), and an always-visible action
 * footer for lifecycle controls. Only the body scrolls; toolbar and footer stay put.
 */
import { type JSX, Show } from 'solid-js';

export interface PageLayoutProps {
  title?: JSX.Element;
  /** Right-aligned toolbar content: page actions, filter menu, item search. */
  toolbar?: JSX.Element;
  /** Left-aligned toolbar content that follows the title (e.g. active filters). */
  toolbarStart?: JSX.Element;
  children: JSX.Element;
  /** Always-visible action footer (status crumbs, lifecycle button, bulk-action bar). */
  footer?: JSX.Element;
  /** Detail side panel content. */
  side?: JSX.Element;
  sideOpen?: boolean;
}

export function PageLayout(props: PageLayoutProps): JSX.Element {
  return (
    <div class="page">
      <Show when={props.title || props.toolbar || props.toolbarStart}>
        <div class="page__toolbar">
          <Show when={props.title}>
            <h1 class="page__title">{props.title}</h1>
          </Show>
          {props.toolbarStart}
          <div class="page__toolbar-spacer" />
          <Show when={props.toolbar}>
            <div class="page__toolbar-actions">{props.toolbar}</div>
          </Show>
        </div>
      </Show>
      <div class="page__main">
        <div class="page__body">{props.children}</div>
        <Show when={props.side && props.sideOpen}>
          <aside class="page__side" aria-label="Details">
            {props.side}
          </aside>
        </Show>
      </div>
      <Show when={props.footer}>
        <div class="page__footer">{props.footer}</div>
      </Show>
    </div>
  );
}
