// svelte/src/chrome/Sidebar.svelte
<script lang="ts">
  // Desktop primary nav (spec chrome/01-behaviours.md › sidebar). Expanded (icon+label)
  // ↔ collapsed icon rail, width animated. The brand mark IS the toggle (centred, spins
  // 360° on toggle — direction echoes the change, suppressed under reduced-motion). No
  // hover reaction (divergence D3).
  import Icon from '../lib/components/Icon.svelte';
  import { chrome } from '../lib/state/chrome.svelte';
  import { auth } from '../lib/state/auth.svelte';
  import { router } from '../lib/router.svelte';
  import { NAV_UPPER, NAV_LOWER, itemPath, type NavItem } from '../lib/nav';

  let expanded = $derived(chrome.expanded);
  let storeId = $derived(auth.activeStoreId ?? '');

  function isActive(item: NavItem): boolean {
    return router.segments[1] === item.area;
  }
</script>

<nav class="sidebar" class:expanded aria-label="Primary">
  <div class="brand-band">
    <button
      class="brand"
      style="--spin: {chrome.spinDir}"
      aria-label={expanded ? 'Close the menu' : 'Open the menu'}
      aria-expanded={expanded}
      onclick={() => chrome.toggleSidebar()}
    >
      {#key chrome.spinDir}
        <span class="brand__spin"><Icon name="m-supply-guy" size={36} /></span>
      {/key}
    </button>
  </div>

  <div class="group group--upper">
    {#each NAV_UPPER as item (item.key)}
      <a
        class="navitem"
        class:active={isActive(item)}
        href={itemPath(storeId, item)}
        title={expanded ? undefined : item.label}
        aria-current={isActive(item) ? 'page' : undefined}
      >
        <Icon name={item.icon} size={24} />
        {#if expanded}<span class="navitem__label">{item.label}</span>{/if}
      </a>
    {/each}
  </div>

  <div class="group group--lower">
    {#each NAV_LOWER as item (item.key)}
      <a
        class="navitem"
        class:active={isActive(item)}
        href={itemPath(storeId, item)}
        title={expanded ? undefined : item.label}
        aria-current={isActive(item) ? 'page' : undefined}
      >
        <Icon name={item.icon} size={24} />
        {#if expanded}<span class="navitem__label">{item.label}</span>{/if}
      </a>
    {/each}
  </div>
</nav>

<style>
  .sidebar {
    display: flex;
    flex-direction: column;
    width: 72px;
    background: var(--surface-nav);
    border-right: 1px solid var(--divider);
    transition: width 0.2s ease;
    overflow: hidden;
    flex: none;
    height: 100%;
  }
  .sidebar.expanded {
    width: 240px;
  }
  .brand-band {
    display: flex;
    justify-content: center;
    padding: var(--sp-4) 0;
  }
  .brand {
    border: 0;
    background: transparent;
    cursor: pointer;
    padding: var(--sp-1);
    border-radius: var(--radius-control);
    display: inline-flex;
  }
  .brand:hover {
    background: var(--hover-overlay);
  }
  .brand__spin {
    display: inline-flex;
    animation: spin calc(0.5s) ease;
  }
  .sidebar:not(.expanded) .brand__spin {
    animation-direction: reverse;
  }
  @keyframes spin {
    from {
      transform: rotate(0);
    }
    to {
      transform: rotate(360deg);
    }
  }
  @media (prefers-reduced-motion: reduce) {
    .brand__spin {
      animation: none;
    }
  }
  .group {
    display: flex;
    flex-direction: column;
    gap: 2px;
    padding: var(--sp-2);
  }
  .group--upper {
    flex: 1;
    overflow-y: auto;
  }
  .group--lower {
    border-top: 1px solid var(--divider);
  }
  .navitem {
    display: flex;
    align-items: center;
    gap: var(--sp-3);
    padding: var(--sp-2) var(--sp-3);
    border-radius: var(--radius-control);
    color: var(--text-secondary);
    min-height: 44px;
    white-space: nowrap;
  }
  .navitem:hover {
    background: var(--hover-overlay);
    color: var(--text-primary);
  }
  .navitem.active {
    background: var(--selected);
    color: var(--brand-primary);
    font-weight: var(--type-emphasis-weight);
  }
  .sidebar:not(.expanded) .navitem {
    justify-content: center;
  }
</style>

// solid/src/chrome/Sidebar.tsx
/**
 * Desktop primary nav (spec/chrome/01-behaviours.md › Sidebar). Collapsible expanded ↔
 * icon-rail via an explicit toggle (no hover-to-peek — divergence D3); the choice persists.
 * Two data-driven groups (upper scrollable, lower). Active item reflects the route. Hidden
 * in full-screen mode (handled by AppShell).
 */
import { type JSX, For, Show } from 'solid-js';
import { A, useLocation } from '@solidjs/router';
import { Icon } from '../ui/Icon';
import { chrome } from '../state/chrome';
import { navGroups, isActive, type NavGroup, type NavItem } from './nav-config';

function NavLink(props: { item: NavItem; pathname: string }): JSX.Element {
  const active = () => isActive(props.item.route, props.pathname);
  return (
    <A
      href={props.item.route}
      class={`nav-item${active() ? ' nav-item--active' : ''}`}
      title={chrome.collapsed ? props.item.label : undefined}
      aria-current={active() ? 'page' : undefined}
    >
      <Icon name={props.item.icon} size={22} />
      <span class="nav-item__label">{props.item.label}</span>
    </A>
  );
}

export function Sidebar(): JSX.Element {
  const location = useLocation();
  const visibleItems = (g: NavGroup) => g.items.filter((i) => i.visible?.() ?? true);

  let brandRef: HTMLButtonElement | undefined;
  // The brand mark is the collapse/expand toggle; activating it plays a single 360° spin
  // whose direction echoes the change (spec/chrome/01 › Sidebar). Decorative — suppressed
  // under a reduced-motion preference.
  const toggle = () => {
    const collapsing = !chrome.collapsed;
    chrome.toggle();
    const reduce = typeof window !== 'undefined' && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    if (!reduce && brandRef?.animate) {
      brandRef.animate([{ transform: 'rotate(0deg)' }, { transform: `rotate(${collapsing ? -360 : 360}deg)` }], {
        duration: 450,
        easing: 'ease-in-out'
      });
    }
  };

  return (
    <nav class={`sidebar${chrome.collapsed ? ' sidebar--collapsed' : ''}`} aria-label="Primary">
      <div class="sidebar__brand">
        <button
          ref={brandRef}
          class="sidebar__brand-btn"
          type="button"
          aria-label={chrome.collapsed ? 'Open the menu' : 'Close the menu'}
          aria-expanded={!chrome.collapsed}
          onClick={toggle}
        >
          <Icon name="m-supply-guy" size={30} />
        </button>
      </div>
      <For each={navGroups}>
        {(group) => (
          <Show when={visibleItems(group).length}>
            <div class={`sidebar__group sidebar__group--${group.id}`}>
              <For each={visibleItems(group)}>{(item) => <NavLink item={item} pathname={location.pathname} />}</For>
            </div>
          </Show>
        )}
      </For>
    </nav>
  );
}
