// svelte/src/lib/chrome/StoreSelector.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import Popover from '$lib/ui/Popover.svelte';
	import Icon from '$lib/icons/Icon.svelte';
	import Checkbox from '$lib/ui/inputs/Checkbox.svelte';
	import { auth } from '$lib/auth/auth.svelte';
	import { ROOT_PATH } from './nav-config';

	let open = $state(false);
	let query = $state('');

	// Hidden entirely if there's nothing to switch to (AC-CH5).
	const hasChoice = $derived(auth.stores.length >= 2);

	// Sorted by name, filtered by the search (AC-CH6).
	const filtered = $derived(
		[...auth.stores]
			.sort((a, b) => a.name.localeCompare(b.name))
			.filter((s) => s.name.toLowerCase().includes(query.toLowerCase()))
	);

	function select(id: string) {
		const store = auth.stores.find((s) => s.id === id);
		if (!store || store.isDisabled || store.isOnHold || id === auth.storeId) return;
		auth.setStore(id);
		open = false;
		query = '';
		// Land in a valid place for the new store, not a stale deep link (AC-CH8).
		goto(ROOT_PATH);
	}
</script>

{#if hasChoice}
	<Popover bind:open placement="top-start">
		{#snippet trigger()}
			<button
				class="bar-control"
				data-popover-trigger
				type="button"
				aria-haspopup="dialog"
				aria-expanded={open}
				onclick={() => (open = !open)}
			>
				<Icon name="home" size={18} />
				<span class="label">{auth.currentStore?.name ?? 'Select store'}</span>
			</button>
		{/snippet}

		<div class="store-pop">
			<input
				class="control compact"
				type="search"
				placeholder="Search stores…"
				bind:value={query}
				aria-label="Search stores"
			/>
			<ul role="listbox" aria-label="Stores">
				{#each filtered as store (store.id)}
					{@const unselectable = store.isDisabled || store.isOnHold || store.id === auth.storeId}
					<li>
						<button
							type="button"
							role="option"
							aria-selected={store.id === auth.storeId}
							class:current={store.id === auth.storeId}
							disabled={unselectable}
							onclick={() => select(store.id)}
						>
							<span class="name">{store.name}</span>
							<span class="code">{store.code}</span>
							{#if store.id === auth.storeId}<span class="tag">Current</span>{/if}
							{#if store.isOnHold}<span class="tag warn">On hold</span>{/if}
							{#if store.isDisabled}<span class="tag">Disabled</span>{/if}
						</button>
					</li>
				{/each}
				{#if filtered.length === 0}<li class="none">No stores match.</li>{/if}
			</ul>
			<label class="remember">
				<Checkbox
					checked={auth.rememberStoreChoice}
					onchange={(v) => auth.setRememberStoreChoice(v)}
				/>
				<span>Remember my choice (skip this at login)</span>
			</label>
		</div>
	</Popover>
{/if}

<style>
	.store-pop {
		width: 320px;
		max-width: 90vw;
		padding: var(--space-3);
		display: flex;
		flex-direction: column;
		gap: var(--space-2);
	}
	ul {
		list-style: none;
		margin: 0;
		padding: 0;
		max-height: 320px;
		overflow-y: auto;
	}
	li button {
		display: flex;
		align-items: center;
		gap: var(--space-2);
		width: 100%;
		min-height: 44px;
		padding: 0 var(--space-2);
		border: 0;
		border-radius: var(--radius-sm);
		background: transparent;
		color: var(--text-primary);
		font: inherit;
		text-align: start;
		cursor: pointer;
	}
	li button:hover:not(:disabled) {
		background: var(--hover-overlay);
	}
	li button:disabled {
		cursor: not-allowed;
		color: var(--text-disabled);
	}
	li button.current {
		font-weight: 600;
	}
	.name {
		flex: 1;
		min-width: 0;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}
	.code {
		font-size: 12px;
		color: var(--text-secondary);
	}
	.tag {
		font-size: 11px;
		text-transform: uppercase;
		letter-spacing: 0.04em;
		color: var(--text-secondary);
		border: 1px solid var(--border-default);
		border-radius: var(--radius-pill);
		padding: 1px 6px;
	}
	.tag.warn {
		color: var(--state-warning);
		border-color: var(--state-warning);
	}
	.none {
		padding: var(--space-3);
		color: var(--text-secondary);
		text-align: center;
	}
	.remember {
		display: flex;
		align-items: center;
		gap: var(--space-1);
		font-size: 13px;
		color: var(--text-secondary);
		border-top: 1px solid var(--divider);
		padding-top: var(--space-2);
	}
</style>

// solid/src/chrome/StoreSelector.tsx
/**
 * Store selector (spec/chrome/01-behaviours.md › Store selector). A click-popover from the
 * store control. Hidden entirely when the user has fewer than 2 stores. Lists stores sorted
 * by name and searchable; the current store and any disabled/on-hold stores are not
 * selectable (on-hold labelled). Selecting sets the active store and navigates to the root
 * landing path. A per-user "remember choice" preference skips the selector at next login.
 */
import { type JSX, For, Show, createMemo, createSignal } from 'solid-js';
import { useNavigate } from '@solidjs/router';
import { Popover } from '../ui/Popover';
import { Icon } from '../ui/Icon';
import { Checkbox } from '../ui/inputs/Checkbox';
import { auth } from '../state/auth';
import { ROOT_PATH } from './nav-config';

export function StoreSelector(): JSX.Element {
  const [open, setOpen] = createSignal(false);
  const [query, setQuery] = createSignal('');
  const navigate = useNavigate();

  const sorted = createMemo(() => [...auth.stores].sort((a, b) => a.name.localeCompare(b.name)));
  const filtered = createMemo(() => {
    const q = query().trim().toLowerCase();
    return q ? sorted().filter((s) => s.name.toLowerCase().includes(q)) : sorted();
  });

  const choose = (id: string) => {
    const store = auth.stores.find((s) => s.id === id);
    if (!store || store.id === auth.storeId || store.isDisabled || store.isOnHold) return;
    auth.setStore(id);
    setOpen(false);
    setQuery('');
    navigate(ROOT_PATH); // land in a valid place for the new store (AC-CH8)
  };

  // Hidden entirely when there is nothing to switch to (AC-CH5).
  return (
    <Show when={auth.stores.length >= 2} fallback={
      <span class="bottom-bar__item"><Icon name="home" size={14} /><span>{auth.currentStore?.name ?? 'Store'}</span></span>
    }>
      <Popover
        open={open()}
        onClose={() => setOpen(false)}
        placement="top-start"
        trigger={
          <button
            class="bottom-bar__item"
            type="button"
            data-popover-trigger
            aria-haspopup="listbox"
            aria-expanded={open()}
            onClick={() => setOpen(!open())}
          >
            <Icon name="home" size={14} />
            <span>{auth.currentStore?.name ?? 'Select store'}</span>
          </button>
        }
      >
        <div class="selector-popover">
          <div class="select-search">
            <input
              class="control control--compact"
              type="text"
              placeholder="Search stores…"
              value={query()}
              onInput={(e) => setQuery(e.currentTarget.value)}
            />
          </div>
          <ul class="menu" role="listbox" aria-label="Stores">
            <For each={filtered()}>
              {(s) => {
                const isCurrent = () => s.id === auth.storeId;
                const blocked = () => s.isDisabled || s.isOnHold;
                return (
                  <li role="none">
                    <button
                      type="button"
                      role="option"
                      aria-selected={isCurrent()}
                      class={`menu-item${isCurrent() ? ' menu-item--selected' : ''}`}
                      disabled={isCurrent() || blocked()}
                      onClick={() => choose(s.id)}
                    >
                      <span class="menu-check">
                        <Show when={isCurrent()}>
                          <Icon name="check" size={16} />
                        </Show>
                      </span>
                      <span class="menu-item__label">{s.name}</span>
                      <Show when={s.isOnHold}>
                        <span class="store-tag">On hold</span>
                      </Show>
                    </button>
                  </li>
                );
              }}
            </For>
          </ul>
          <label class="menu-item" style={{ cursor: 'pointer' }}>
            <Checkbox
              checked={auth.rememberStoreChoice}
              ariaLabel="Remember this store at login"
              onChange={(v) => auth.setRememberStoreChoice(v)}
            />
            <span class="menu-item__label">Remember choice</span>
          </label>
        </div>
      </Popover>
    </Show>
  );
}
