// svelte/src/lib/chrome/UserMenu.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import Popover from '$lib/ui/Popover.svelte';
	import Modal from '$lib/ui/Modal.svelte';
	import Button from '$lib/ui/Button.svelte';
	import Icon from '$lib/icons/Icon.svelte';
	import { auth } from '$lib/auth/auth.svelte';

	let open = $state(false);
	let confirmingLogout = $state(false);

	function requestLogout() {
		open = false;
		confirmingLogout = true;
	}

	function confirmLogout() {
		confirmingLogout = false;
		auth.logout();
		goto('/login');
	}
</script>

{#if auth.user}
	<Popover bind:open placement="top-end">
		{#snippet trigger()}
			<button
				class="bar-control"
				data-popover-trigger
				type="button"
				aria-haspopup="dialog"
				aria-expanded={open}
				onclick={() => (open = !open)}
			>
				<Icon name="user" size={18} />
				<span class="label">{auth.user?.firstName} {auth.user?.lastName}</span>
			</button>
		{/snippet}

		<div class="user-pop">
			<p class="name">{auth.user.firstName} {auth.user.lastName}</p>
			<dl>
				<div><dt>Username</dt><dd>{auth.user.username}</dd></div>
				<div><dt>Email</dt><dd>{auth.user.email}</dd></div>
				<div><dt>Job title</dt><dd>{auth.user.jobTitle}</dd></div>
			</dl>
			<Button variant="secondary" onclick={requestLogout}>
				<Icon name="power" size={18} />Log out
			</Button>
		</div>
	</Popover>

	<Modal bind:open={confirmingLogout} title="Log out?" width="400px">
		Are you sure you want to log out? You'll need to sign in again to continue.
		{#snippet footer()}
			<Button variant="ghost" onclick={() => (confirmingLogout = false)}>Cancel</Button>
			<Button variant="primary" onclick={confirmLogout}>Log out</Button>
		{/snippet}
	</Modal>
{/if}

<style>
	.user-pop {
		width: 260px;
		padding: var(--space-4);
		display: flex;
		flex-direction: column;
		gap: var(--space-3);
	}
	.name {
		margin: 0;
		font-weight: 600;
		font-size: 15px;
	}
	dl {
		margin: 0;
		display: flex;
		flex-direction: column;
		gap: var(--space-2);
	}
	dt {
		font-size: 11px;
		text-transform: uppercase;
		letter-spacing: 0.04em;
		color: var(--text-secondary);
	}
	dd {
		margin: 0;
		font-size: 14px;
		word-break: break-word;
	}
</style>

// solid/src/chrome/UserMenu.tsx
/**
 * User details + logout (spec/chrome/01-behaviours.md › User details & logout). A click-
 * popover showing username, email, and job title, plus the theme override. Logout requires a
 * confirmation; on confirm the session is cleared and the app navigates to Login (AC-CH14).
 */
import { type JSX, Show, createSignal } from 'solid-js';
import { useNavigate } from '@solidjs/router';
import { Popover } from '../ui/Popover';
import { Icon } from '../ui/Icon';
import { Button } from '../ui/Button';
import { ConfirmDialog } from '../ui/Modal';
import { ThemeToggle } from '../theme/ThemeToggle';
import { auth } from '../state/auth';

export function UserMenu(): JSX.Element {
  const [open, setOpen] = createSignal(false);
  const [confirm, setConfirm] = createSignal(false);
  const navigate = useNavigate();

  const doLogout = () => {
    setConfirm(false);
    setOpen(false);
    auth.logout();
    navigate('/login');
  };

  return (
    <Show when={auth.user}>
      <Popover
        open={open()}
        onClose={() => setOpen(false)}
        placement="top-start"
        trigger={
          <button
            class="bottom-bar__item"
            type="button"
            data-popover-trigger
            aria-haspopup="dialog"
            aria-expanded={open()}
            onClick={() => setOpen(!open())}
          >
            <Icon name="user" size={14} />
            <span>
              {auth.user!.firstName} {auth.user!.lastName}
            </span>
          </button>
        }
      >
        <div class="user-card" role="dialog" aria-label="Account">
          <div class="user-card__name">{auth.user!.username}</div>
          <div class="user-card__row">{auth.user!.email}</div>
          <div class="user-card__row">{auth.user!.jobTitle}</div>
          <div style={{ 'margin-top': 'var(--space-3)' }}>
            <div class="user-card__row" style={{ 'margin-bottom': '4px' }}>
              Appearance
            </div>
            <ThemeToggle />
          </div>
          <div class="user-card__actions">
            <Button variant="secondary" icon="power" onClick={() => setConfirm(true)}>
              Logout
            </Button>
          </div>
        </div>
      </Popover>
      <ConfirmDialog
        open={confirm()}
        title="Log out?"
        message="You will be returned to the login screen."
        confirmLabel="Log out"
        onConfirm={doLogout}
        onCancel={() => setConfirm(false)}
      />
    </Show>
  );
}
