// solid/src/chrome/LanguageSelector.tsx
/**
 * Language selector (spec/chrome/01-behaviours.md › Language selector). Click-popover listing
 * available languages; the current one is not selectable. Selecting changes the active
 * language, persists it per user, and (per AC-CH11) reloads so content re-renders. Honours
 * RTL. Here `reloadOnChange` is off in dev to avoid churn while there are no string
 * catalogues yet; the acceptance contract turns it on.
 */
import { type JSX, For, Show, createSignal } from 'solid-js';
import { Popover } from '../ui/Popover';
import { Icon } from '../ui/Icon';
import { i18n } from '../state/i18n';

export function LanguageSelector(): JSX.Element {
  const [open, setOpen] = createSignal(false);
  const choose = (code: string) => {
    setOpen(false);
    i18n.setLanguage(code);
  };
  return (
    <Popover
      open={open()}
      onClose={() => setOpen(false)}
      placement="top-start"
      trigger={
        <button
          class="bottom-bar__item"
          type="button"
          data-popover-trigger
          aria-haspopup="listbox"
          aria-expanded={open()}
          onClick={() => setOpen(!open())}
        >
          <Icon name="translate" size={14} />
          <span>{i18n.current.name}</span>
        </button>
      }
    >
      <ul class="menu" role="listbox" aria-label="Language" style={{ 'min-width': '200px' }}>
        <For each={i18n.languages}>
          {(l) => {
            const isCurrent = () => l.code === i18n.code;
            return (
              <li role="none">
                <button
                  type="button"
                  role="option"
                  aria-selected={isCurrent()}
                  class={`menu-item${isCurrent() ? ' menu-item--selected' : ''}`}
                  disabled={isCurrent()}
                  onClick={() => choose(l.code)}
                >
                  <span class="menu-check">
                    <Show when={isCurrent()}>
                      <Icon name="check" size={16} />
                    </Show>
                  </span>
                  <span class="menu-item__label" dir={l.rtl ? 'rtl' : undefined}>
                    {l.name}
                  </span>
                </button>
              </li>
            );
          }}
        </For>
      </ul>
    </Popover>
  );
}

// svelte/src/lib/chrome/LanguageSelector.svelte
<script lang="ts">
	import Popover from '$lib/ui/Popover.svelte';
	import Icon from '$lib/icons/Icon.svelte';
	import { i18n } from '$lib/i18n/i18n.svelte';

	let open = $state(false);

	function select(code: string) {
		if (code === i18n.code) return; // current is not selectable (AC-CH10)
		// reloadOnChange off in dev (no string catalogues yet); the spec contract is reload.
		i18n.setLanguage(code, false);
		open = false;
	}
</script>

<Popover bind:open placement="top-start">
	{#snippet trigger()}
		<button
			class="bar-control"
			data-popover-trigger
			type="button"
			aria-haspopup="listbox"
			aria-expanded={open}
			onclick={() => (open = !open)}
		>
			<Icon name="translate" size={18} />
			<span class="label">{i18n.current.name}</span>
		</button>
	{/snippet}

	<ul class="lang-pop" role="listbox" aria-label="Language">
		{#each i18n.languages as lang (lang.code)}
			<li>
				<button
					type="button"
					role="option"
					aria-selected={lang.code === i18n.code}
					class:current={lang.code === i18n.code}
					disabled={lang.code === i18n.code}
					onclick={() => select(lang.code)}
				>
					<span style:direction={lang.rtl ? 'rtl' : 'ltr'}>{lang.name}</span>
					{#if lang.code === i18n.code}<span class="check" aria-hidden="true">✓</span>{/if}
				</button>
			</li>
		{/each}
	</ul>
</Popover>

<style>
	.lang-pop {
		list-style: none;
		margin: 0;
		padding: var(--space-1);
		min-width: 200px;
	}
	li button {
		display: flex;
		align-items: center;
		justify-content: space-between;
		width: 100%;
		min-height: 44px;
		padding: 0 var(--space-3);
		border: 0;
		border-radius: var(--radius-sm);
		background: transparent;
		color: var(--text-primary);
		font: inherit;
		text-align: start;
		cursor: pointer;
	}
	li button:hover:not(:disabled) {
		background: var(--hover-overlay);
	}
	li button.current {
		font-weight: 600;
		cursor: default;
	}
	.check {
		color: var(--brand-primary);
	}
</style>
