// react/src/components/ConfirmDialog.tsx
import type { ReactNode } from 'react';
import { Modal } from './Modal';
import { Button } from './Button';

/**
 * Confirmation dialog for irreversible / guarded actions (logout, finalise,
 * reduce-to-zero). Extra content (e.g. a reason selector) can be slotted in.
 */
interface ConfirmDialogProps {
  open: boolean;
  onClose: () => void;
  onConfirm: () => void;
  title: string;
  message?: ReactNode;
  children?: ReactNode;
  confirmLabel?: string;
  cancelLabel?: string;
  destructive?: boolean;
  busy?: boolean;
  confirmDisabled?: boolean;
}

export function ConfirmDialog({
  open,
  onClose,
  onConfirm,
  title,
  message,
  children,
  confirmLabel = 'Confirm',
  cancelLabel = 'Cancel',
  destructive = false,
  busy = false,
  confirmDisabled = false,
}: ConfirmDialogProps) {
  return (
    <Modal
      open={open}
      onClose={onClose}
      title={title}
      size="sm"
      dismissable={!busy}
      footer={
        <>
          <Button variant="ghost" onClick={onClose} disabled={busy}>
            {cancelLabel}
          </Button>
          <Button
            variant={destructive ? 'destructive' : 'primary'}
            icon={destructive ? 'delete' : 'check'}
            onClick={onConfirm}
            busy={busy}
            disabled={confirmDisabled}
          >
            {confirmLabel}
          </Button>
        </>
      }
    >
      {message && <p style={{ margin: 0 }}>{message}</p>}
      {children}
    </Modal>
  );
}

// svelte/src/lib/components/ConfirmDialog.svelte
<script lang="ts">
  // Confirmation prompt for irreversible/guarded actions (logout, finalise, reduce-to-
  // zero, delete). Built on Modal; confirm can be gated (e.g. reason required).
  import type { Snippet } from 'svelte';
  import Modal from './Modal.svelte';
  import Button from './Button.svelte';

  type Props = {
    open: boolean;
    title: string;
    message?: string;
    confirmLabel?: string;
    cancelLabel?: string;
    destructive?: boolean;
    confirmDisabled?: boolean;
    busy?: boolean;
    onconfirm: () => void;
    oncancel: () => void;
    children?: Snippet;
  };
  let {
    open,
    title,
    message,
    confirmLabel = 'Confirm',
    cancelLabel = 'Cancel',
    destructive = false,
    confirmDisabled = false,
    busy = false,
    onconfirm,
    oncancel,
    children,
  }: Props = $props();
</script>

<Modal {open} {title} size="sm" onclose={oncancel}>
  {#if message}<p class="msg">{message}</p>{/if}
  {#if children}{@render children()}{/if}
  {#snippet footer()}
    <Button variant="ghost" label={cancelLabel} onclick={oncancel} />
    <Button
      variant={destructive ? 'destructive' : 'primary'}
      icon={destructive ? 'delete' : 'check'}
      label={confirmLabel}
      disabled={confirmDisabled}
      {busy}
      onclick={onconfirm}
    />
  {/snippet}
</Modal>

<style>
  .msg {
    margin: 0 0 var(--sp-3);
    color: var(--text-primary);
    line-height: 1.5;
  }
</style>
