// solid/src/ui/Popover.tsx
import { createEffect, onCleanup, type JSX } from 'solid-js';
import { Portal } from 'solid-js/web';

type AriaRole = JSX.HTMLAttributes<HTMLElement>['role'];

/*
 * Transient surface anchored to a trigger (controls.md#menus--popovers):
 *  - renders in a top-level overlay (Portal on document.body) so it is NEVER
 *    clipped by an ancestor's overflow/scroll — it floats above the page AND
 *    above any modal that opened it;
 *  - anchored below the trigger, start-aligned; flips above on bottom overflow
 *    and shifts along the edge to stay on-screen; caps height + scrolls internally;
 *  - dismisses on outside-click, Escape, or the trigger toggling it shut;
 *  - returns focus to the trigger on dismissal (divergence D6).
 */

export interface PopoverProps {
  open: boolean;
  anchor: HTMLElement | undefined;
  onClose: () => void;
  children: JSX.Element;
  /** Match the anchor's width (used by comboboxes). */
  matchWidth?: boolean;
  class?: string;
  /** aria role for the surface (e.g. "listbox", "menu"). */
  role?: AriaRole;
  id?: string;
}

export function Popover(props: PopoverProps): JSX.Element {
  let surface: HTMLDivElement | undefined;

  const position = () => {
    if (!surface || !props.anchor) return;
    const a = props.anchor.getBoundingClientRect();
    const margin = 4;
    const vw = window.innerWidth;
    const vh = window.innerHeight;

    if (props.matchWidth) surface.style.minWidth = `${a.width}px`;

    // Measure natural size.
    surface.style.maxHeight = '';
    const rect = surface.getBoundingClientRect();
    const spaceBelow = vh - a.bottom - margin;
    const spaceAbove = a.top - margin;
    const flipUp = rect.height > spaceBelow && spaceAbove > spaceBelow;

    const maxH = Math.max(120, (flipUp ? spaceAbove : spaceBelow) - margin);
    surface.style.maxHeight = `${maxH}px`;

    let top = flipUp ? a.top - Math.min(rect.height, maxH) - margin : a.bottom + margin;
    let left = a.left;
    // Shift horizontally to stay on-screen.
    if (left + rect.width > vw - margin) left = Math.max(margin, vw - rect.width - margin);
    if (left < margin) left = margin;
    top = Math.max(margin, top);

    surface.style.top = `${top}px`;
    surface.style.left = `${left}px`;
  };

  createEffect(() => {
    if (!props.open) return;
    const trigger = props.anchor ?? (document.activeElement as HTMLElement | null);

    // Position after paint, and keep pinned to the trigger on scroll/resize.
    requestAnimationFrame(position);
    const reflow = () => position();
    window.addEventListener('scroll', reflow, true);
    window.addEventListener('resize', reflow);

    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        e.stopPropagation();
        props.onClose();
      }
    };
    const onPointerDown = (e: PointerEvent) => {
      const target = e.target as Node;
      if (surface?.contains(target) || props.anchor?.contains(target)) return;
      props.onClose();
    };
    document.addEventListener('keydown', onKey, true);
    document.addEventListener('pointerdown', onPointerDown, true);

    onCleanup(() => {
      window.removeEventListener('scroll', reflow, true);
      window.removeEventListener('resize', reflow);
      document.removeEventListener('keydown', onKey, true);
      document.removeEventListener('pointerdown', onPointerDown, true);
      // Return focus to the trigger on dismissal (D6).
      if (trigger && typeof trigger.focus === 'function') trigger.focus();
    });
  });

  return (
    <>
      {props.open && (
        <Portal>
          <div
            ref={surface}
            class={`popover${props.class ? ` ${props.class}` : ''}`}
            role={props.role}
            id={props.id}
          >
            {props.children}
          </div>
        </Portal>
      )}
    </>
  );
}

// svelte/src/lib/components/Popover.svelte
<script lang="ts">
  // Transient surface anchored to a trigger (spec ui-standards/controls.md › menus &
  // popovers). Renders in a top-level portal above the page (and above modals), never
  // clipped by an ancestor. Anchored below-start by default; flips/shifts to stay on
  // screen; caps height and scrolls internally. Dismisses on outside-click / Escape;
  // focus returns to the trigger (divergence D6).
  import type { Snippet } from 'svelte';
  import { portal } from '../util/portal';

  type Props = {
    anchor: HTMLElement | null;
    open: boolean;
    onclose: () => void;
    minWidth?: number;
    matchAnchorWidth?: boolean;
    label?: string;
    children: Snippet;
  };
  let { anchor, open, onclose, minWidth = 180, matchAnchorWidth = false, label, children }: Props =
    $props();

  let panel = $state<HTMLElement | null>(null);
  let pos = $state({ top: 0, left: 0, width: 180, maxHeight: 480, placement: 'bottom' });

  function place() {
    if (!anchor || !panel) return;
    const a = anchor.getBoundingClientRect();
    const gap = 4;
    const vw = window.innerWidth;
    const vh = window.innerHeight;
    const width = matchAnchorWidth ? Math.max(a.width, minWidth) : Math.max(panel.offsetWidth, minWidth);

    // horizontal: start-aligned, shift to stay on screen
    let left = a.left;
    if (left + width > vw - 8) left = Math.max(8, vw - 8 - width);
    if (left < 8) left = 8;

    // vertical: below by default, flip above if not enough room
    const spaceBelow = vh - a.bottom - gap - 8;
    const spaceAbove = a.top - gap - 8;
    const desired = panel.scrollHeight;
    let top: number;
    let maxHeight: number;
    let placement: string;
    if (desired <= spaceBelow || spaceBelow >= spaceAbove) {
      top = a.bottom + gap;
      maxHeight = spaceBelow;
      placement = 'bottom';
    } else {
      maxHeight = spaceAbove;
      top = a.top - gap - Math.min(desired, maxHeight);
      placement = 'top';
    }
    pos = { top, left, width, maxHeight: Math.max(120, maxHeight), placement };
  }

  function onKey(e: KeyboardEvent) {
    if (open && e.key === 'Escape') {
      e.stopPropagation();
      close();
    }
  }

  function onDocPointer(e: PointerEvent) {
    const t = e.target as Node;
    if (panel?.contains(t) || anchor?.contains(t)) return;
    close();
  }

  function close() {
    onclose();
    anchor?.focus();
  }

  $effect(() => {
    if (open && anchor && panel) {
      place();
      // Re-measure after content paints.
      requestAnimationFrame(place);
      const onScroll = () => place();
      window.addEventListener('resize', onScroll);
      window.addEventListener('scroll', onScroll, true);
      document.addEventListener('pointerdown', onDocPointer, true);
      return () => {
        window.removeEventListener('resize', onScroll);
        window.removeEventListener('scroll', onScroll, true);
        document.removeEventListener('pointerdown', onDocPointer, true);
      };
    }
  });
</script>

<svelte:window onkeydown={onKey} />

{#if open}
  <div
    class="popover"
    bind:this={panel}
    use:portal
    role="dialog"
    tabindex="-1"
    aria-label={label}
    style="top:{pos.top}px; left:{pos.left}px; min-width:{pos.width}px; max-height:{pos.maxHeight}px;"
  >
    {@render children()}
  </div>
{/if}

<style>
  .popover {
    position: fixed;
    z-index: var(--z-popover);
    background: var(--surface-raised);
    border: 1px solid var(--border-default);
    border-radius: var(--radius-control);
    box-shadow: var(--elev-raised);
    overflow-y: auto;
    overflow-x: hidden;
    padding: var(--sp-1);
  }
</style>
