// solid/src/ui/Banner.tsx
/**
 * Whole-record message banner (spec/stocktakes/05-ui-surface.md › S5 error surfaces, and
 * the status/lock messaging). Explains why editing is blocked, etc. Colour + icon + text.
 */
import { type JSX } from 'solid-js';
import { Icon, type IconName } from './Icon';

export function Banner(props: { tone?: 'info' | 'warning' | 'error'; icon?: IconName; children: JSX.Element }): JSX.Element {
  const tone = () => props.tone ?? 'info';
  const icon = (): IconName => props.icon ?? (tone() === 'error' ? 'circle-alert' : tone() === 'warning' ? 'alert' : 'info');
  return (
    <div class={`banner banner--${tone()}`} role={tone() === 'error' ? 'alert' : 'status'}>
      <Icon name={icon()} size={18} />
      <span>{props.children}</span>
    </div>
  );
}

// react/src/components/Banner.tsx
import type { ReactNode } from 'react';
import { Icon, type IconName } from '@/icons/Icon';
import './Banner.css';

/**
 * Inline message banner (info/warning/error/success). Used for the stocktake
 * locked/finalised explanations and whole-stocktake error surfaces (spec S5).
 * Colour always pairs with an icon + text (colour independence).
 */
export type BannerTone = 'info' | 'warning' | 'error' | 'success';

const TONE_ICON: Record<BannerTone, IconName> = {
  info: 'info',
  warning: 'alert',
  error: 'circle-alert',
  success: 'check-circle',
};

interface BannerProps {
  tone?: BannerTone;
  title?: string;
  children?: ReactNode;
  action?: ReactNode;
}

export function Banner({ tone = 'info', title, children, action }: BannerProps) {
  return (
    <div className={`oms-banner oms-banner--${tone}`} role={tone === 'error' ? 'alert' : 'status'}>
      <Icon name={TONE_ICON[tone]} size={20} className="oms-banner__icon" />
      <div className="oms-banner__content">
        {title && <p className="oms-banner__title">{title}</p>}
        {children && <div className="oms-banner__body">{children}</div>}
      </div>
      {action && <div className="oms-banner__action">{action}</div>}
    </div>
  );
}
