// solid/src/ui/Popover.tsx
/**
 * Click-popover anchored to a trigger (spec/ui-standards/controls.md › Menus & popovers).
 * The consumer owns `open` and supplies a `trigger` and content `children`.
 *
 * Layering: the content renders in a **top-level overlay** (a portal on `document.body`), so
 * it is never clipped, scrolled, or resized by an ancestor's bounds/overflow/scroll region —
 * including a dialog: a menu opened inside a modal floats *above* that modal (z-index above
 * the modal), not inside its scroll area. Opening never reflows the page beneath it.
 *
 * Placement & collision: anchored to the trigger (default below, start-aligned) and kept
 * tethered; if it would overflow it flips to the opposite side and/or shifts along the edge to
 * stay on-screen, and caps its height and scrolls internally rather than being clipped.
 *
 * Dismisses on outside-click and Escape; on Escape focus returns to `[data-popover-trigger]`.
 */
import { type JSX, Show, createEffect, createSignal, onCleanup } from 'solid-js';
import { Portal } from 'solid-js/web';

type Placement = 'bottom-start' | 'bottom-end' | 'top-start' | 'top-end';
interface Pos {
  top: number;
  left: number;
  width?: number;
  maxHeight: number;
}

export interface PopoverProps {
  open: boolean;
  onClose: () => void;
  placement?: Placement;
  matchWidth?: boolean;
  trigger: JSX.Element;
  children: JSX.Element;
}

const MARGIN = 8;
const GAP = 4;

export function Popover(props: PopoverProps): JSX.Element {
  let root: HTMLDivElement | undefined;
  let content: HTMLDivElement | undefined;
  const [pos, setPos] = createSignal<Pos>();

  const reposition = () => {
    if (!props.open || !root || !content) return;
    const tr = root.getBoundingClientRect();
    const vw = window.innerWidth;
    const vh = window.innerHeight;
    const preferTop = props.placement?.startsWith('top') ?? false;
    const alignEnd = props.placement?.endsWith('end') ?? false;

    const width = props.matchWidth ? tr.width : content.offsetWidth;
    const contentH = content.scrollHeight;
    const spaceBelow = vh - tr.bottom - MARGIN;
    const spaceAbove = tr.top - MARGIN;

    // Flip to whichever side fits; prefer the requested side, else the roomier one.
    const placeAbove = preferTop ? spaceAbove >= contentH || spaceAbove > spaceBelow : spaceBelow < contentH && spaceAbove > spaceBelow;
    const maxHeight = Math.max(120, placeAbove ? spaceAbove : spaceBelow);
    const usedH = Math.min(contentH, maxHeight);
    const top = placeAbove ? tr.top - usedH - GAP : tr.bottom + GAP;

    let left = alignEnd ? tr.right - width : tr.left;
    left = Math.max(MARGIN, Math.min(left, vw - width - MARGIN));

    setPos({ top, left, width: props.matchWidth ? tr.width : undefined, maxHeight });
  };

  const onPointer = (e: PointerEvent) => {
    const t = e.target as Node;
    if (props.open && root && !root.contains(t) && content && !content.contains(t)) props.onClose();
  };
  const onKey = (e: KeyboardEvent) => {
    if (props.open && e.key === 'Escape') {
      props.onClose();
      (root?.querySelector('[data-popover-trigger]') as HTMLElement | null)?.focus();
    }
  };

  createEffect(() => {
    if (!props.open) {
      setPos(undefined);
      return;
    }
    queueMicrotask(reposition); // measure once the portaled content has mounted
    const onScrollResize = () => reposition();
    // capture-phase scroll catches scrolling in any ancestor, keeping the popover tethered.
    window.addEventListener('scroll', onScrollResize, true);
    window.addEventListener('resize', onScrollResize);
    document.addEventListener('pointerdown', onPointer);
    document.addEventListener('keydown', onKey);
    onCleanup(() => {
      window.removeEventListener('scroll', onScrollResize, true);
      window.removeEventListener('resize', onScrollResize);
      document.removeEventListener('pointerdown', onPointer);
      document.removeEventListener('keydown', onKey);
    });
  });

  return (
    <div class="pop-root" ref={root}>
      {props.trigger}
      <Show when={props.open}>
        <Portal>
          <div
            class="pop-content"
            ref={content}
            style={{
              position: 'fixed',
              top: `${pos()?.top ?? -9999}px`,
              left: `${pos()?.left ?? -9999}px`,
              ...(pos()?.width != null ? { width: `${pos()!.width}px`, 'min-width': `${pos()!.width}px` } : {}),
              'max-height': `${pos()?.maxHeight ?? 400}px`,
              visibility: pos() ? 'visible' : 'hidden'
            }}
          >
            {props.children}
          </div>
        </Portal>
      </Show>
    </div>
  );
}

// react/src/components/Popover.tsx
import {
  useCallback,
  useEffect,
  useLayoutEffect,
  useRef,
  useState,
  type ReactNode,
  type RefObject,
} from 'react';
import { createPortal } from 'react-dom';
import './Popover.css';

/**
 * Transient surface anchored to a trigger (menus, selectors, dropdowns) per
 * spec/ui-standards/controls.md#menus--popovers:
 *  - opens on trigger activation; dismisses on outside-click / Escape / selection
 *  - on dismissal, focus returns to the trigger (divergence D6)
 *  - surface.raised colour + raised elevation
 *  - anchored below/start-aligned, stays within the viewport (flips/shifts)
 */

export type Placement = 'bottom-start' | 'bottom-end' | 'top-start' | 'top-end';

interface PopoverProps {
  anchorRef: RefObject<HTMLElement | null>;
  open: boolean;
  onClose: () => void;
  children: ReactNode;
  placement?: Placement;
  /** Match the trigger's width (dropdowns). */
  matchWidth?: boolean;
  /** Restore focus to the trigger on close (default true, per D6). */
  returnFocus?: boolean;
  className?: string;
  /** aria role for the surface; combobox listboxes set their own. */
  role?: string;
  labelledBy?: string;
}

export function Popover({
  anchorRef,
  open,
  onClose,
  children,
  placement = 'bottom-start',
  matchWidth = false,
  returnFocus = true,
  className,
  role = 'menu',
  labelledBy,
}: PopoverProps) {
  const surfaceRef = useRef<HTMLDivElement>(null);
  const [pos, setPos] = useState<{ top: number; left: number; width: number } | null>(
    null,
  );

  const reposition = useCallback(() => {
    const anchor = anchorRef.current;
    const surface = surfaceRef.current;
    if (!anchor || !surface) return;
    const a = anchor.getBoundingClientRect();
    const gap = 4;
    const surfaceH = surface.offsetHeight;
    const surfaceW = matchWidth ? a.width : surface.offsetWidth;
    const preferTop = placement.startsWith('top');
    const endAligned = placement.endsWith('end');

    // Prefer the requested side; flip only if it would overflow and the other side fits.
    const below = a.bottom + gap;
    const above = a.top - gap - surfaceH;
    let top: number;
    if (preferTop) {
      top = above > 8 || a.top > window.innerHeight - a.bottom ? above : below;
    } else {
      top = below + surfaceH > window.innerHeight - 8 && above > 8 ? above : below;
    }

    let left = endAligned ? a.right - surfaceW : a.left;
    // Shift horizontally to stay within the viewport.
    left = Math.max(8, Math.min(left, window.innerWidth - surfaceW - 8));

    setPos({ top, left, width: a.width });
  }, [anchorRef, matchWidth, placement]);

  useLayoutEffect(() => {
    if (!open) return;
    reposition();
    const onScrollResize = () => reposition();
    window.addEventListener('resize', onScrollResize);
    window.addEventListener('scroll', onScrollResize, true);
    return () => {
      window.removeEventListener('resize', onScrollResize);
      window.removeEventListener('scroll', onScrollResize, true);
    };
  }, [open, reposition]);

  // Dismiss on outside-click / Escape; return focus to the trigger.
  useEffect(() => {
    if (!open) return;
    const trigger = anchorRef.current;

    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        e.stopPropagation();
        onClose();
      }
    };
    const onPointer = (e: PointerEvent) => {
      const t = e.target as Node;
      if (surfaceRef.current?.contains(t) || trigger?.contains(t)) return;
      onClose();
    };
    document.addEventListener('keydown', onKey, true);
    document.addEventListener('pointerdown', onPointer, true);
    return () => {
      document.removeEventListener('keydown', onKey, true);
      document.removeEventListener('pointerdown', onPointer, true);
    };
  }, [open, onClose, anchorRef]);

  // On close, return focus to the trigger (D6).
  const wasOpen = useRef(false);
  useEffect(() => {
    if (wasOpen.current && !open && returnFocus) {
      anchorRef.current?.focus?.();
    }
    wasOpen.current = open;
  }, [open, returnFocus, anchorRef]);

  if (!open) return null;

  return createPortal(
    <div
      ref={surfaceRef}
      role={role}
      aria-labelledby={labelledBy}
      className={`oms-popover${className ? ` ${className}` : ''}`}
      style={{
        top: pos?.top ?? -9999,
        left: pos?.left ?? -9999,
        minWidth: matchWidth ? pos?.width : undefined,
        visibility: pos ? 'visible' : 'hidden',
      }}
    >
      {children}
    </div>,
    document.body,
  );
}
