// solid/src/ui/Select.tsx
import {
  createSignal,
  createMemo,
  For,
  Show,
  createUniqueId,
  type JSX,
  createEffect,
} from 'solid-js';
import { Icon } from './Icon';
import { Popover } from './Popover';
import { Field } from './inputs';

/*
 * Single-select dropdown (controls.md#single-select-dropdown): a type-to-filter
 * combobox (NOT the native <select>), searchable by default, themeable. The async
 * variant (controls.md#async--catalogue-lookup-variant) shares the same shell and
 * keyboard/selection/clearing behaviour, differing only in where options come from
 * (a debounced remote query vs. a local list).
 *
 * Clearability follows optionality (divergence D5): an OPTIONAL field shows a clear
 * × when a value is set; a REQUIRED field never does.
 */

export interface Option {
  value: string;
  label: string;
  disabled?: boolean;
}

interface CoreProps {
  options: Option[];
  loading?: boolean;
  error?: string;
  onRetry?: () => void;
  /** Idle prompt shown before enough characters are typed (async). */
  promptText?: string;
  emptyText?: string;
  /** Called as the filter text changes (async fetches on this). */
  onQuery?: (query: string) => void;
  /** When false, the core does not filter options itself (async supplies filtered). */
  localFilter: boolean;

  value: string | null | undefined;
  onChange: (value: string | null) => void;
  placeholder?: string;
  label?: string;
  required?: boolean;
  disabled?: boolean;
  fieldError?: string;
  id?: string;
  containerClass?: string;
}

function Core(props: CoreProps): JSX.Element {
  const id = props.id ?? createUniqueId();
  const listId = `${id}-listbox`;
  const [open, setOpen] = createSignal(false);
  const [query, setQuery] = createSignal('');
  const [active, setActive] = createSignal(0);
  let input: HTMLInputElement | undefined;

  const selectedOption = () => props.options.find((o) => o.value === props.value);
  const selectedLabel = () => selectedOption()?.label ?? '';

  const visible = createMemo(() => {
    if (!props.localFilter) return props.options;
    const q = query().trim().toLowerCase();
    if (!q) return props.options;
    return props.options.filter((o) => o.label.toLowerCase().includes(q));
  });

  // Keep the active option within bounds when the visible set changes.
  createEffect(() => {
    visible();
    setActive(0);
  });

  const openList = () => {
    if (props.disabled) return;
    setQuery('');
    props.onQuery?.('');
    setOpen(true);
  };
  const close = () => setOpen(false);

  const selectAt = (i: number) => {
    const opt = visible()[i];
    if (!opt || opt.disabled) return;
    props.onChange(opt.value);
    close();
  };

  const move = (delta: number) => {
    const opts = visible();
    if (opts.length === 0) return;
    let i = active();
    for (let step = 0; step < opts.length; step++) {
      i = (i + delta + opts.length) % opts.length;
      if (!opts[i]?.disabled) break;
    }
    setActive(i);
  };

  const onKeyDown = (e: KeyboardEvent) => {
    if (!open()) {
      if (e.key === 'ArrowDown' || e.key === 'ArrowUp' || e.key === 'Enter' || e.key === ' ') {
        e.preventDefault();
        openList();
      }
      return;
    }
    switch (e.key) {
      case 'ArrowDown':
        e.preventDefault();
        move(1);
        break;
      case 'ArrowUp':
        e.preventDefault();
        move(-1);
        break;
      case 'Home':
        e.preventDefault();
        setActive(0);
        break;
      case 'End':
        e.preventDefault();
        setActive(visible().length - 1);
        break;
      case 'Enter':
        e.preventDefault();
        selectAt(active());
        break;
      case 'Tab':
        close();
        break;
    }
  };

  const showClear = () => !props.required && !!props.value && !props.disabled;

  return (
    <Field
      label={props.label}
      error={props.fieldError}
      required={props.required}
      fieldId={id}
      class={props.containerClass}
    >
      <div class={`combobox${open() ? ' combobox-open' : ''}${props.disabled ? ' combobox-disabled' : ''}`}>
        <input
          ref={input}
          id={id}
          class="input combobox-input"
          role="combobox"
          aria-expanded={open()}
          aria-controls={listId}
          aria-autocomplete="list"
          autocomplete="off"
          disabled={props.disabled}
          placeholder={selectedLabel() || props.placeholder}
          value={open() ? query() : selectedLabel()}
          aria-invalid={props.fieldError ? 'true' : undefined}
          onFocus={openList}
          onClick={openList}
          onInput={(e) => {
            setQuery(e.currentTarget.value);
            props.onQuery?.(e.currentTarget.value);
            setOpen(true);
          }}
          onKeyDown={onKeyDown}
        />
        <div class="combobox-adornments">
          <Show when={showClear()}>
            <button
              type="button"
              class="combobox-clear"
              aria-label="Clear"
              onClick={() => {
                props.onChange(null);
                input?.focus();
              }}
            >
              <Icon name="close" size={16} />
            </button>
          </Show>
          <Icon name="chevron-down" size={16} class="combobox-chevron" />
        </div>
        <Popover open={open()} anchor={input} onClose={close} matchWidth role="listbox" id={listId}>
          <Show when={props.loading}>
            <div class="combobox-status">Loading…</div>
          </Show>
          <Show when={props.error}>
            <div class="combobox-status combobox-error">
              <span>{props.error}</span>
              <Show when={props.onRetry}>
                <button type="button" class="btn btn-ghost btn-compact" onClick={() => props.onRetry?.()}>
                  Retry
                </button>
              </Show>
            </div>
          </Show>
          <Show when={!props.loading && !props.error && visible().length === 0}>
            <div class="combobox-status">
              {props.localFilter || query() ? (props.emptyText ?? 'No matches') : (props.promptText ?? 'Type to search…')}
            </div>
          </Show>
          <For each={visible()}>
            {(opt, i) => (
              <button
                type="button"
                role="option"
                aria-selected={opt.value === props.value}
                disabled={opt.disabled}
                class={`combobox-option${i() === active() ? ' combobox-option-active' : ''}`}
                onPointerEnter={() => setActive(i())}
                onClick={() => selectAt(i())}
              >
                <span class="menu-item-check" aria-hidden="true">
                  {opt.value === props.value && <Icon name="check" size={16} />}
                </span>
                <span class="combobox-option-label">{opt.label}</span>
              </button>
            )}
          </For>
        </Popover>
      </div>
    </Field>
  );
}

export interface SelectProps {
  options: Option[];
  value: string | null | undefined;
  onChange: (value: string | null) => void;
  label?: string;
  placeholder?: string;
  required?: boolean;
  disabled?: boolean;
  error?: string;
  id?: string;
  containerClass?: string;
  emptyText?: string;
}

/** Local single-select (options shipped to the client). */
export function Select(props: SelectProps): JSX.Element {
  return (
    <Core
      localFilter
      options={props.options}
      value={props.value}
      onChange={props.onChange}
      label={props.label}
      placeholder={props.placeholder}
      required={props.required}
      disabled={props.disabled}
      fieldError={props.error}
      id={props.id}
      containerClass={props.containerClass}
      emptyText={props.emptyText}
    />
  );
}

export interface AsyncSelectProps {
  /** Currently-selected option (must be supplied so its label renders when set). */
  selected: Option | null;
  /** Debounced-fetched results for the current query. */
  results: Option[];
  onQuery: (query: string) => void;
  onChange: (option: Option | null) => void;
  loading?: boolean;
  error?: string;
  onRetry?: () => void;
  label?: string;
  placeholder?: string;
  promptText?: string;
  emptyText?: string;
  required?: boolean;
  disabled?: boolean;
  fieldError?: string;
  id?: string;
  containerClass?: string;
}

/** Async catalogue-lookup single-select (remote query per keystroke). */
export function AsyncSelect(props: AsyncSelectProps): JSX.Element {
  // Merge the selected option into the option pool so its label resolves.
  const options = createMemo<Option[]>(() => {
    const list = [...props.results];
    if (props.selected && !list.some((o) => o.value === props.selected!.value)) {
      list.unshift(props.selected);
    }
    return list;
  });
  return (
    <Core
      localFilter={false}
      options={options()}
      value={props.selected?.value ?? null}
      onChange={(v) => props.onChange(v == null ? null : (options().find((o) => o.value === v) ?? null))}
      onQuery={props.onQuery}
      loading={props.loading}
      error={props.error}
      onRetry={props.onRetry}
      label={props.label}
      placeholder={props.placeholder}
      promptText={props.promptText}
      emptyText={props.emptyText}
      required={props.required}
      disabled={props.disabled}
      fieldError={props.fieldError}
      id={props.id}
      containerClass={props.containerClass}
    />
  );
}

// react/src/components/Select.tsx
import { useEffect, useId, useMemo, useRef, useState } from 'react';
import { Icon } from '@/icons/Icon';
import { FieldShell } from './Field';
import { Popover } from './Popover';
import './Select.css';

/**
 * Single-select dropdown per spec/ui-standards/controls.md#single-select-dropdown:
 * a type-to-filter combobox (combobox + listbox), NOT the native <select>.
 *  - trigger shows the selected label (or placeholder) + disclosure chevron
 *  - typing filters options in place (case-insensitive substring)
 *  - selected option marked (check); a separate active option tracks keyboard focus
 *  - clearability follows optionality (divergence D5): optional shows a clear ×
 *    when a value is set; required never does
 *  - full keyboard model; disabled options shown but skipped
 */
export interface SelectOption {
  value: string;
  label: string;
  disabled?: boolean;
}

interface SelectProps {
  value: string | null;
  onChange: (value: string | null) => void;
  options: SelectOption[];
  /** Optional fields are clearable (D5). Defaults to true. */
  optional?: boolean;
  placeholder?: string;
  label?: string;
  error?: string;
  hint?: string;
  disabled?: boolean;
  size?: 'default' | 'compact';
  emptyMessage?: string;
  className?: string;
  ariaLabel?: string;
  /**
   * When provided, the parent drives filtering (e.g. server-side search): the
   * typed query is reported here and the given options are shown as-is (no
   * client-side substring filter).
   */
  onQueryChange?: (query: string) => void;
}

export function Select({
  value,
  onChange,
  options,
  optional = true,
  placeholder = 'Select…',
  label,
  error,
  hint,
  disabled,
  size = 'default',
  emptyMessage = 'No matches',
  className,
  ariaLabel,
  onQueryChange,
}: SelectProps) {
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState('');
  const [active, setActive] = useState(0);
  const wrapRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const listId = useId();

  const selected = options.find((o) => o.value === value) ?? null;

  const filtered = useMemo(() => {
    // Server-driven mode: parent filters, show options as-is.
    if (onQueryChange) return options;
    const q = query.trim().toLowerCase();
    if (!q) return options;
    return options.filter((o) => o.label.toLowerCase().includes(q));
  }, [options, query, onQueryChange]);

  // When (re)opening, start unfiltered and highlight the selected option.
  useEffect(() => {
    if (open) {
      const idx = filtered.findIndex((o) => o.value === value);
      setActive(idx >= 0 ? idx : firstEnabled(filtered));
    } else {
      setQuery('');
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open]);

  // Keep the active index within the filtered set as the user types.
  useEffect(() => {
    setActive((a) => Math.min(Math.max(0, a), Math.max(0, filtered.length - 1)));
  }, [filtered.length]);

  const commit = (opt: SelectOption | undefined) => {
    if (!opt || opt.disabled) return;
    onChange(opt.value);
    setOpen(false);
    inputRef.current?.focus();
  };

  const clear = () => {
    onChange(null);
    setOpen(false);
    inputRef.current?.focus();
  };

  const moveActive = (dir: 1 | -1) => {
    if (filtered.length === 0) return;
    let i = active;
    for (let step = 0; step < filtered.length; step++) {
      i = (i + dir + filtered.length) % filtered.length;
      if (!filtered[i].disabled) break;
    }
    setActive(i);
  };

  const onKeyDown = (e: React.KeyboardEvent) => {
    if (disabled) return;
    switch (e.key) {
      case 'ArrowDown':
        e.preventDefault();
        if (!open) setOpen(true);
        else moveActive(1);
        break;
      case 'ArrowUp':
        e.preventDefault();
        if (!open) setOpen(true);
        else moveActive(-1);
        break;
      case 'Home':
        if (open) {
          e.preventDefault();
          setActive(firstEnabled(filtered));
        }
        break;
      case 'End':
        if (open) {
          e.preventDefault();
          setActive(lastEnabled(filtered));
        }
        break;
      case 'Enter':
        if (open) {
          e.preventDefault();
          commit(filtered[active]);
        } else {
          setOpen(true);
        }
        break;
      case ' ':
        if (!open) {
          e.preventDefault();
          setOpen(true);
        }
        break;
      case 'Escape':
        if (open) {
          e.preventDefault();
          setOpen(false);
        }
        break;
      case 'Tab':
        setOpen(false);
        break;
    }
  };

  const showClear = optional && value != null && !disabled;
  const displayValue = open ? query : (selected?.label ?? '');

  return (
    <FieldShell label={label} error={error} hint={hint} className={className}>
      <div ref={wrapRef} className={`oms-select oms-select--${size}`}>
        <div
          className={`oms-select__control${error ? ' is-invalid' : ''}${
            disabled ? ' is-disabled' : ''
          }`}
        >
          <input
            ref={inputRef}
            type="text"
            role="combobox"
            aria-expanded={open}
            aria-controls={listId}
            aria-autocomplete="list"
            aria-activedescendant={
              open && filtered[active] ? `${listId}-opt-${active}` : undefined
            }
            aria-label={ariaLabel ?? (typeof label === 'string' ? label : undefined)}
            aria-invalid={error ? true : undefined}
            className="oms-select__input"
            value={displayValue}
            placeholder={selected ? selected.label : placeholder}
            disabled={disabled}
            onChange={(e) => {
              setQuery(e.target.value);
              onQueryChange?.(e.target.value);
              if (!open) setOpen(true);
            }}
            onMouseDown={() => {
              if (!disabled && !open) setOpen(true);
            }}
            onKeyDown={onKeyDown}
          />
          {showClear && (
            <button
              type="button"
              className="oms-select__clear"
              aria-label="Clear selection"
              title="Clear"
              onClick={clear}
              tabIndex={0}
            >
              <Icon name="close" size={16} />
            </button>
          )}
          <button
            type="button"
            className="oms-select__chevron"
            aria-label={open ? 'Close options' : 'Open options'}
            tabIndex={-1}
            disabled={disabled}
            onMouseDown={(e) => {
              e.preventDefault();
              setOpen((o) => !o);
              inputRef.current?.focus();
            }}
          >
            <Icon name="chevron-down" size={18} />
          </button>
        </div>

        <Popover
          anchorRef={wrapRef}
          open={open}
          onClose={() => setOpen(false)}
          matchWidth
          returnFocus={false}
          role="presentation"
        >
          <ul id={listId} role="listbox" className="oms-select__list">
            {filtered.length === 0 ? (
              <li className="oms-menu-empty">{emptyMessage}</li>
            ) : (
              filtered.map((opt, i) => (
                <li
                  key={opt.value}
                  id={`${listId}-opt-${i}`}
                  role="option"
                  aria-selected={opt.value === value}
                  aria-disabled={opt.disabled || undefined}
                  className={`oms-menu-item${i === active ? ' is-active' : ''}${
                    opt.disabled ? ' is-disabled' : ''
                  }`}
                  onMouseEnter={() => !opt.disabled && setActive(i)}
                  onMouseDown={(e) => {
                    e.preventDefault();
                    commit(opt);
                  }}
                >
                  <span className="oms-select__opt-label">{opt.label}</span>
                  {opt.value === value && (
                    <Icon name="check" size={16} className="oms-menu-item__check" />
                  )}
                </li>
              ))
            )}
          </ul>
        </Popover>
      </div>
    </FieldShell>
  );
}

function firstEnabled(opts: SelectOption[]): number {
  const i = opts.findIndex((o) => !o.disabled);
  return i >= 0 ? i : 0;
}
function lastEnabled(opts: SelectOption[]): number {
  for (let i = opts.length - 1; i >= 0; i--) if (!opts[i].disabled) return i;
  return 0;
}
