// solid/src/ui/SplitButton.tsx
import { createSignal, For, type JSX } from 'solid-js';
import { Icon, type IconName } from './Icon';
import { Popover } from './Popover';

/*
 * Split (multi-action) button (controls.md#split-multi-action-button). One default
 * target plus alternatives: the primary segment performs the currently-selected
 * action; the disclosure segment opens a menu of ALL options. Invalid options are
 * shown-but-disabled (the menu doubles as a lifecycle legend); the selected option
 * is marked. Picking an option makes it the new primary and is remembered — it does
 * NOT fire immediately. Confirmation/precondition handling is the caller's (onPrimary).
 */

export interface SplitOption<V extends string> {
  value: V;
  label: string;
  disabled?: boolean;
}

export interface SplitButtonProps<V extends string> {
  options: SplitOption<V>[];
  selected: V;
  onSelect: (value: V) => void;
  onPrimary: (value: V) => void;
  icon?: IconName;
  busy?: boolean;
}

export function SplitButton<V extends string>(props: SplitButtonProps<V>): JSX.Element {
  const [open, setOpen] = createSignal(false);
  let disclosure: HTMLButtonElement | undefined;

  const current = () => props.options.find((o) => o.value === props.selected) ?? props.options[0];

  return (
    <div class="split-button">
      <button
        type="button"
        class="split-primary"
        disabled={props.busy || current()?.disabled}
        aria-busy={props.busy ? 'true' : undefined}
        onClick={() => props.onPrimary(props.selected)}
      >
        {props.busy ? (
          <span class="btn-spinner" aria-hidden="true" />
        ) : (
          props.icon && <Icon name={props.icon} size={20} />
        )}
        <span class="btn-label">{current()?.label}</span>
      </button>
      <button
        ref={disclosure}
        type="button"
        class="split-disclosure"
        aria-haspopup="menu"
        aria-expanded={open()}
        aria-label="More status options"
        onClick={() => setOpen((v) => !v)}
      >
        <Icon name="chevron-down" size={16} />
      </button>
      <Popover
        open={open()}
        anchor={disclosure}
        onClose={() => setOpen(false)}
        role="menu"
        matchWidth
      >
        <For each={props.options}>
          {(opt) => (
            <button
              type="button"
              role="menuitemradio"
              aria-checked={opt.value === props.selected}
              class="menu-item"
              disabled={opt.disabled}
              onClick={() => {
                props.onSelect(opt.value);
                setOpen(false);
              }}
            >
              <span class="menu-item-check" aria-hidden="true">
                {opt.value === props.selected && <Icon name="check" size={16} />}
              </span>
              <span>{opt.label}</span>
            </button>
          )}
        </For>
      </Popover>
    </div>
  );
}

// react/src/components/SplitButton.tsx
import { useRef, useState } from 'react';
import { Icon, type IconName } from '@/icons/Icon';
import { Menu, type MenuOption } from './Menu';
import './SplitButton.css';

/**
 * Split (multi-action) button per spec/ui-standards/controls.md#split-multi-action-button.
 * One default target + alternatives, most notably advancing a document's status.
 *  - primary segment fires the currently-selected action directly
 *  - disclosure chevron opens a menu of ALL options; picking one makes it the new
 *    primary and remembers it — it does NOT fire immediately
 *  - invalid options are shown but disabled; the selected one is marked
 */
export interface SplitAction {
  key: string;
  label: string;
  disabled?: boolean;
}

interface SplitButtonProps {
  options: SplitAction[];
  selectedKey: string;
  onSelectedChange: (key: string) => void;
  onActivate: (key: string) => void;
  icon?: IconName;
  busy?: boolean;
}

export function SplitButton({
  options,
  selectedKey,
  onSelectedChange,
  onActivate,
  icon = 'arrow-right',
  busy = false,
}: SplitButtonProps) {
  const [menuOpen, setMenuOpen] = useState(false);
  const discRef = useRef<HTMLButtonElement>(null);

  const selected = options.find((o) => o.key === selectedKey) ?? options[0];

  const menuOptions: MenuOption[] = options.map((o) => ({
    key: o.key,
    label: o.label,
    disabled: o.disabled,
    selected: o.key === selectedKey,
    onSelect: () => onSelectedChange(o.key),
  }));

  return (
    <div className="oms-split">
      <button
        type="button"
        className="oms-split__primary"
        disabled={busy || selected?.disabled}
        aria-busy={busy || undefined}
        onClick={() => selected && onActivate(selected.key)}
      >
        <span className="oms-split__label">{selected?.label}</span>
        <Icon
          name={busy ? 'refresh' : icon}
          size={18}
          className={busy ? 'oms-btn__spin' : undefined}
        />
      </button>
      <button
        ref={discRef}
        type="button"
        className="oms-split__disclosure"
        aria-label="More status options"
        aria-haspopup="menu"
        aria-expanded={menuOpen}
        // Disabled only while busy; the menu stays available even in the
        // degenerate single-option case (it acts as an informational legend).
        disabled={busy}
        onClick={() => setMenuOpen((v) => !v)}
      >
        <Icon name="chevron-down" size={16} />
      </button>
      <Menu
        anchorRef={discRef}
        open={menuOpen}
        onClose={() => setMenuOpen(false)}
        options={menuOptions}
        placement="top-start"
      />
    </div>
  );
}
