// solid/src/components/ui/StatusBadge.tsx
import { type JSX } from 'solid-js';
import type { StocktakeStatus } from '../../api/types';

// Status shown with text + style, never colour alone
// (spec/ui-standards/accessibility.md#colour-independence).
export function StatusBadge(props: { status: StocktakeStatus }): JSX.Element {
  const label = () => (props.status === 'NEW' ? 'New' : 'Finalised');
  const cls = () => (props.status === 'NEW' ? 'badge--new' : 'badge--finalised');
  return <span class={`badge ${cls()}`}>{label()}</span>;
}

// react/src/components/StatusBadge.tsx
import './StatusBadge.css';

/**
 * Status shown with text + style, never colour alone (accessibility.md).
 * Tone maps to a state colour; the label is always present.
 */
export type BadgeTone = 'neutral' | 'info' | 'warning' | 'error' | 'success';

interface StatusBadgeProps {
  label: string;
  tone?: BadgeTone;
}

export function StatusBadge({ label, tone = 'neutral' }: StatusBadgeProps) {
  return <span className={`oms-badge oms-badge--${tone}`}>{label}</span>;
}
