// solid/src/ui/inputs/Toggle.tsx
/**
 * Toggle switch (spec/ui-standards/inputs.md — accent when on). Used for boolean options
 * like "include items with no stock on hand". A labelled button with `aria-pressed`.
 */
import { type JSX, Show } from 'solid-js';

export interface ToggleProps {
  checked: boolean;
  onChange?: (checked: boolean) => void;
  label?: JSX.Element;
  disabled?: boolean;
  ariaLabel?: string;
}

export function Toggle(props: ToggleProps): JSX.Element {
  return (
    <button
      type="button"
      class="toggle"
      role="switch"
      aria-pressed={props.checked}
      aria-label={props.ariaLabel}
      disabled={props.disabled}
      onClick={() => props.onChange?.(!props.checked)}
    >
      <span class="toggle__track" aria-hidden="true">
        <span class="toggle__thumb" />
      </span>
      <Show when={props.label}>
        <span>{props.label}</span>
      </Show>
    </button>
  );
}

// react/src/components/Toggle.tsx
import { useId } from 'react';
import './Toggle.css';

/** Switch/toggle using the accent colour when on (inputs.md). */
interface ToggleProps {
  checked: boolean;
  onChange: (checked: boolean) => void;
  label?: string;
  disabled?: boolean;
  id?: string;
}

export function Toggle({ checked, onChange, label, disabled, id }: ToggleProps) {
  const genId = useId();
  const inputId = id ?? genId;
  return (
    <label className={`oms-toggle${disabled ? ' is-disabled' : ''}`} htmlFor={inputId}>
      <input
        id={inputId}
        type="checkbox"
        role="switch"
        checked={checked}
        disabled={disabled}
        onChange={(e) => onChange(e.target.checked)}
        className="oms-toggle__input"
      />
      <span className="oms-toggle__track" aria-hidden="true">
        <span className="oms-toggle__thumb" />
      </span>
      {label && <span className="oms-toggle__label">{label}</span>}
    </label>
  );
}
