// svelte/src/routes/stocktakes/LineEditor.svelte
<script lang="ts">
  // S4 — Line editor (spec stocktakes/05-ui-surface.md#s4--line-editor, J3). The single
  // surface for entering line data: counted packs, batch, dates, location, pack size,
  // prices, reason, comment/note. Modal over S3, opened by selecting a line (edit) or
  // Add item (create). A reason is required when the count adjusts stock in a direction
  // that has active reasons (spec 03 › adjustment-reason rules).
  import Modal from '../../lib/components/Modal.svelte';
  import Button from '../../lib/components/Button.svelte';
  import Field from '../../lib/components/Field.svelte';
  import Select from '../../lib/components/Select.svelte';
  import TextInput from '../../lib/components/TextInput.svelte';
  import AsyncSelect from '../../lib/components/AsyncSelect.svelte';
  import Icon from '../../lib/components/Icon.svelte';
  import { auth } from '../../lib/state/auth.svelte';
  import { searchItems } from '../../lib/api/catalogue';
  import { uuid, type LineInsert, type LineUpdate } from '../../lib/api/stocktakes';
  import {
    NEGATIVE_REASON_TYPES,
    VACCINE_WASTAGE_TYPES,
    type ReasonOption,
    type StocktakeLine,
    type Location,
    type CatalogueItem,
  } from '../../lib/api/types';

  type Props = {
    open: boolean;
    // Editing an existing line, or null for a new item.
    line: StocktakeLine | null;
    stocktakeId: string;
    existingItemIds: string[]; // exclude from add-search
    reasons: ReasonOption[];
    locations: Location[];
    // per-line save error keyed to this line, if any
    lineError?: string | null;
    onclose: () => void;
    onsave: (ops: { insert?: LineInsert; update?: LineUpdate }) => Promise<boolean>;
    // navigation between existing lines
    onprev?: () => void;
    onnext?: () => void;
    hasPrev?: boolean;
    hasNext?: boolean;
  };
  let {
    open,
    line,
    stocktakeId,
    existingItemIds,
    reasons,
    locations,
    lineError = null,
    onclose,
    onsave,
    onprev,
    onnext,
    hasPrev = false,
    hasNext = false,
  }: Props = $props();

  let storeId = $derived(auth.activeStoreId!);
  let isEdit = $derived(line !== null);

  // Form state — reset whenever the target line changes.
  let pickedItem = $state<CatalogueItem | null>(null);
  let counted = $state('');
  let batch = $state('');
  let expiry = $state('');
  let packSize = $state('');
  let costPrice = $state('');
  let sellPrice = $state('');
  let locationId = $state<string | null>(null);
  let reasonId = $state<string | null>(null);
  let comment = $state('');
  let note = $state('');
  let saving = $state(false);

  // Re-seed the form when the modal opens or the line changes.
  let seedKey = $derived(open ? (line?.id ?? 'new') : 'closed');
  $effect(() => {
    seedKey; // dependency
    if (!open) return;
    pickedItem = null;
    counted = line?.countedNumberOfPacks != null ? String(line.countedNumberOfPacks) : '';
    batch = line?.batch ?? '';
    expiry = line?.expiryDate ?? '';
    packSize = line?.packSize != null ? String(line.packSize) : '';
    costPrice = line?.costPricePerPack != null ? String(line.costPricePerPack) : '';
    sellPrice = line?.sellPricePerPack != null ? String(line.sellPricePerPack) : '';
    locationId = line?.location?.id ?? null;
    reasonId = line?.reasonOption?.id ?? null;
    comment = line?.comment ?? '';
    note = line?.note ?? '';
  });

  let itemName = $derived(isEdit ? line!.itemName : (pickedItem?.name ?? ''));
  let unitName = $derived(isEdit ? line?.item?.unitName : pickedItem?.unitName);
  let isVaccine = $derived(isEdit ? !!line?.item?.isVaccine : !!pickedItem?.isVaccine);

  // Snapshot for direction/reason logic. New items have snapshot 0.
  let snapshot = $derived(line?.snapshotNumberOfPacks ?? 0);
  let countedNum = $derived(counted.trim() === '' ? null : Number(counted));
  let delta = $derived(countedNum == null ? 0 : countedNum - snapshot);

  // Reasons valid for the current adjustment direction.
  let validReasons = $derived.by(() => {
    if (delta > 0) return reasons.filter((r) => r.type === 'POSITIVE_INVENTORY_ADJUSTMENT');
    if (delta < 0) {
      const types = isVaccine ? NEGATIVE_REASON_TYPES : NEGATIVE_REASON_TYPES.filter((t) => !VACCINE_WASTAGE_TYPES.includes(t));
      return reasons.filter((r) => types.includes(r.type));
    }
    return [];
  });
  let reasonRequired = $derived(countedNum != null && delta !== 0 && validReasons.length > 0);
  let reasonMissing = $derived(reasonRequired && !reasonId);

  let canSave = $derived(
    (isEdit || pickedItem != null) && !reasonMissing && (counted.trim() === '' || !isNaN(Number(counted))),
  );

  async function save() {
    if (!canSave) return;
    saving = true;
    let ok: boolean;
    if (isEdit && line) {
      const update: LineUpdate = {
        id: line.id,
        countedNumberOfPacks: countedNum,
        batch: batch || null,
        expiryDate: expiry || null,
        packSize: packSize ? Number(packSize) : null,
        costPricePerPack: costPrice ? Number(costPrice) : null,
        sellPricePerPack: sellPrice ? Number(sellPrice) : null,
        location: locationId ?? '',
        reasonOptionId: reasonRequired ? reasonId : reasonId, // send chosen reason (or unchanged)
        comment: comment || null,
        note: note || null,
      };
      ok = await onsave({ update });
    } else if (pickedItem) {
      const insert: LineInsert = {
        id: uuid(),
        itemId: pickedItem.id,
        countedNumberOfPacks: countedNum,
        batch: batch || null,
        expiryDate: expiry || null,
        packSize: packSize ? Number(packSize) : pickedItem.defaultPackSize,
        costPricePerPack: costPrice ? Number(costPrice) : null,
        sellPricePerPack: sellPrice ? Number(sellPrice) : null,
        location: locationId,
        reasonOptionId: reasonRequired ? reasonId : null,
        comment: comment || null,
        note: note || null,
      };
      ok = await onsave({ insert });
    } else {
      ok = false;
    }
    saving = false;
    if (ok) onclose();
  }

  async function itemSearch(q: string) {
    const items = await searchItems(storeId, q, existingItemIds);
    return items.map((i) => ({ value: i.id, label: i.name, sublabel: i.code, item: i }));
  }
</script>

<Modal {open} title={isEdit ? `Edit line — ${itemName}` : 'Add item'} size="lg" {onclose}>
  <div class="editor">
    {#if lineError}
      <div class="banner error"><Icon name="circle-alert" size={18} /> {lineError}</div>
    {/if}

    <!-- Item selector -->
    {#if isEdit}
      <Field label="Item">
        <TextInput value={`${line?.item?.code ?? ''}  ${itemName}`.trim()} readonly />
      </Field>
    {:else}
      <Field label="Item" hint="Items already on the stocktake are excluded.">
        <AsyncSelect
          selectedLabel={pickedItem?.name}
          placeholder="Search the catalogue…"
          search={itemSearch}
          onselect={(o: any) => (pickedItem = o.item)}
        />
      </Field>
    {/if}

    {#if isEdit || pickedItem}
      <div class="grid2">
        <Field label="Counted packs" error={reasonMissing ? null : undefined}>
          <TextInput bind:value={counted} type="number" min={0} align="right" placeholder="Not counted" />
        </Field>
        <Field label={unitName ? `Pack size (${unitName})` : 'Pack size'}>
          <TextInput bind:value={packSize} type="number" min={0} align="right" />
        </Field>
        <Field label="Batch">
          <TextInput bind:value={batch} />
        </Field>
        <Field label="Expiry date">
          <TextInput bind:value={expiry} type="date" />
        </Field>
        <Field label="Location">
          <Select
            value={locationId}
            options={locations.map((l) => ({ value: l.id, label: `${l.code} — ${l.name}` }))}
            placeholder="No location"
            onchange={(v) => (locationId = v)}
          />
        </Field>
        <Field
          label="Reason"
          error={reasonMissing ? 'A reason is required for this adjustment.' : null}
        >
          <Select
            value={reasonId}
            required={reasonRequired}
            invalid={reasonMissing}
            disabled={validReasons.length === 0}
            options={validReasons.map((r) => ({ value: r.id, label: r.reason }))}
            placeholder={validReasons.length === 0 ? 'No reason needed' : 'Select a reason…'}
            onchange={(v) => (reasonId = v)}
          />
        </Field>
        <Field label="Cost price / pack">
          <TextInput bind:value={costPrice} type="number" min={0} align="right" />
        </Field>
        <Field label="Sell price / pack">
          <TextInput bind:value={sellPrice} type="number" min={0} align="right" />
        </Field>
      </div>

      <!-- Difference readout -->
      <div class="diff" aria-live="polite">
        Snapshot <strong class="tnum">{snapshot}</strong> · Counted
        <strong class="tnum">{countedNum ?? '—'}</strong> · Difference
        <strong class="tnum" class:pos={delta > 0} class:neg={delta < 0}>
          {countedNum == null ? '—' : delta > 0 ? `+${delta}` : delta < 0 ? `−${Math.abs(delta)}` : '0'}
        </strong>
      </div>

      <div class="grid2">
        <Field label="Comment"><TextInput bind:value={comment} /></Field>
        <Field label="Note (carried to stock)"><TextInput bind:value={note} /></Field>
      </div>
    {/if}
  </div>

  {#snippet footer()}
    {#if isEdit && (hasPrev || hasNext)}
      <div class="nav">
        <Button variant="ghost" icon="arrow-left" iconOnly label="Previous item" disabled={!hasPrev} onclick={() => onprev?.()} />
        <Button variant="ghost" icon="arrow-right" iconOnly label="Next item" disabled={!hasNext} onclick={() => onnext?.()} />
      </div>
    {/if}
    <div class="grow"></div>
    <Button variant="ghost" label="Cancel" onclick={onclose} />
    <Button variant="primary" icon="save" label="Save" busy={saving} disabled={!canSave} onclick={save} />
  {/snippet}
</Modal>

<style>
  .editor {
    display: flex;
    flex-direction: column;
    gap: var(--sp-4);
  }
  .grid2 {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: var(--sp-3);
  }
  @media (max-width: 560px) {
    .grid2 {
      grid-template-columns: 1fr;
    }
  }
  .banner {
    display: flex;
    align-items: center;
    gap: var(--sp-2);
    padding: var(--sp-2) var(--sp-3);
    border-radius: var(--radius-control);
  }
  .banner.error {
    background: var(--state-error-subtle);
    color: var(--state-error);
  }
  .diff {
    padding: var(--sp-2) var(--sp-3);
    background: var(--surface-sunken);
    border-radius: var(--radius-control);
    color: var(--text-secondary);
  }
  .diff .pos {
    color: var(--state-success);
  }
  .diff .neg {
    color: var(--state-error);
  }
  .nav {
    display: flex;
    gap: var(--sp-1);
  }
  .grow {
    flex: 1;
  }
</style>

// react/src/features/stocktakes/LineEditor.tsx
import { useMemo, useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { Modal } from '@/components/Modal';
import { Button } from '@/components/Button';
import { Select } from '@/components/Select';
import { TextInput } from '@/components/Field';
import { Banner } from '@/components/Banner';
import { ConfirmDialog } from '@/components/ConfirmDialog';
import { Icon } from '@/icons/Icon';
import { useToast } from '@/components/Toast';
import { useDebouncedValue } from '@/lib/useDebouncedValue';
import { formatNumber } from '@/lib/format';
import { batchLines, type LineInsert, type LineUpdate } from './linesApi';
import { searchItems } from './itemsApi';
import { reasonsForDirection, directionOf } from './reasons';
import type { LineReason, StocktakeLine } from './types';
import './LineEditor.css';

/**
 * Line editor (spec S4): the single surface for entering line data. Add mode
 * searches the catalogue (excluding items already on the stocktake) and shows the
 * item's batches to count + lets new ones be added; edit mode is locked to the
 * item and shows ALL of that item's batches on the stocktake plus add-new.
 * Committed by an explicit Save (modal — not auto-saved); leaving with unsaved
 * changes prompts a confirmation (inputs.md#modal--explicit-save).
 */
interface LineEditorProps {
  storeId: string;
  stocktakeId: string;
  line: StocktakeLine | null; // null = add mode
  allLines: StocktakeLine[];
  existingItemIds: string[];
  reasons: LineReason[];
  onClose: () => void;
  onSaved: () => void;
}

interface DraftBatch {
  key: string;
  lineId?: string; // existing stocktake line → update
  stockLineId?: string; // existing stock line → insert with link
  label: string;
  snapshot: number;
  isNew: boolean;
  counted: string;
  batch: string;
  expiryDate: string;
  packSize: string;
  reasonOptionId: string | null;
}

function draftFromLine(l: StocktakeLine): DraftBatch {
  return {
    key: l.id,
    lineId: l.id,
    stockLineId: l.stockLine?.id ?? undefined,
    label: `${l.batch || 'No batch'}${l.expiryDate ? ` · exp ${l.expiryDate}` : ''}`,
    snapshot: l.snapshotNumberOfPacks,
    isNew: false,
    counted: l.countedNumberOfPacks?.toString() ?? '',
    batch: l.batch ?? '',
    expiryDate: l.expiryDate ?? '',
    packSize: l.packSize?.toString() ?? '',
    reasonOptionId: l.reasonOption?.id ?? null,
  };
}

export function LineEditor({
  storeId,
  stocktakeId,
  line,
  allLines,
  existingItemIds,
  reasons,
  onClose,
  onSaved,
}: LineEditorProps) {
  const toast = useToast();
  const isEdit = line != null;
  const [error, setError] = useState<string | null>(null);
  const [confirmDiscard, setConfirmDiscard] = useState(false);

  // ---- Add mode: server-side item search (the Select reports the typed query) ----
  const [query, setQuery] = useState('');
  const debounced = useDebouncedValue(query, 300);
  const [pickedItemId, setPickedItemId] = useState<string | null>(null);

  const itemsQuery = useQuery({
    queryKey: ['itemSearch', storeId, debounced],
    queryFn: () => searchItems(storeId, debounced),
    enabled: !isEdit,
  });
  const items = (itemsQuery.data ?? []).filter((i) => !existingItemIds.includes(i.id));

  // ---- Draft batches ----
  const initial = useMemo<DraftBatch[]>(
    () => (line ? allLines.filter((l) => l.itemId === line.itemId).map(draftFromLine) : []),
    [line, allLines],
  );
  const [batches, setBatches] = useState<DraftBatch[]>(initial);
  const initialJson = useMemo(() => JSON.stringify(initial), [initial]);
  const dirty = JSON.stringify(batches) !== initialJson || (!isEdit && pickedItemId != null);

  const seedFromItem = (itemId: string) => {
    setPickedItemId(itemId);
    const item = items.find((i) => i.id === itemId);
    if (!item) return;
    setBatches(
      item.availableBatches.map((b) => ({
        key: b.id,
        stockLineId: b.id,
        label: `${b.batch || 'No batch'}${b.expiryDate ? ` · exp ${b.expiryDate}` : ''}`,
        snapshot: b.totalNumberOfPacks,
        isNew: false,
        counted: '',
        batch: b.batch ?? '',
        expiryDate: b.expiryDate ?? '',
        packSize: b.packSize.toString(),
        reasonOptionId: null,
      })),
    );
  };

  const addNewBatch = () =>
    setBatches((bs) => [
      ...bs,
      {
        key: `new-${bs.length}-${bs.reduce((n, b) => n + b.key.length, 0)}`,
        label: 'New batch',
        snapshot: 0,
        isNew: true,
        counted: '',
        batch: '',
        expiryDate: '',
        packSize: '1',
        reasonOptionId: null,
      },
    ]);

  const patchBatch = (key: string, patch: Partial<DraftBatch>) =>
    setBatches((bs) => bs.map((b) => (b.key === key ? { ...b, ...patch } : b)));

  const save = useMutation({
    mutationFn: async () => {
      const itemId = isEdit ? line!.itemId : pickedItemId!;
      const updates: LineUpdate[] = [];
      const inserts: LineInsert[] = [];

      for (const b of batches) {
        const counted = b.counted === '' ? undefined : Number(b.counted);
        if (b.lineId) {
          // Existing stocktake line → update.
          updates.push({
            id: b.lineId,
            countedNumberOfPacks: counted,
            batch: b.batch || undefined,
            expiryDate: b.expiryDate || null,
            packSize: b.packSize ? Number(b.packSize) : undefined,
            reasonOptionId: b.reasonOptionId ?? undefined,
          });
        } else if (b.counted !== '' || (b.isNew && b.batch)) {
          // New line (available stock batch or a brand-new batch) → insert.
          inserts.push({
            itemId,
            stockLineId: b.stockLineId,
            countedNumberOfPacks: counted,
            batch: b.isNew ? b.batch || undefined : undefined,
            expiryDate: b.isNew ? b.expiryDate || undefined : undefined,
            packSize: b.isNew && b.packSize ? Number(b.packSize) : undefined,
            reasonOptionId: b.reasonOptionId ?? undefined,
          });
        }
      }
      return batchLines(storeId, { stocktakeId, update: updates, insert: inserts });
    },
    onSuccess: (res) => {
      if (res.ok) {
        toast.success(isEdit ? 'Line saved' : 'Lines added');
        onSaved();
      } else {
        setError(res.lineErrors.map((e) => e.message).join('; '));
      }
    },
    onError: (e) => setError((e as Error).message),
  });

  const attemptClose = () => {
    if (dirty && !save.isPending) setConfirmDiscard(true);
    else onClose();
  };

  const canSave = isEdit
    ? dirty
    : pickedItemId != null && batches.some((b) => b.counted !== '' || (b.isNew && b.batch));

  const showBatches = isEdit || pickedItemId != null;

  return (
    <>
      <Modal
        open
        onClose={attemptClose}
        title={isEdit ? `Edit ${line!.itemName}` : 'Add item'}
        size="lg"
        dismissable={!save.isPending}
        footer={
          <>
            <Button variant="ghost" onClick={attemptClose} disabled={save.isPending}>
              Cancel
            </Button>
            <Button variant="primary" icon="check" busy={save.isPending} disabled={!canSave} onClick={() => save.mutate()}>
              Save
            </Button>
          </>
        }
      >
        {error && (
          <Banner tone="error" title="Could not save">
            {error}
          </Banner>
        )}

        {isEdit ? (
          <div className="oms-le__item">
            <Icon name="stock" size={18} />
            <span>
              <strong>{line!.item.code}</strong> {line!.itemName}
            </span>
            {line!.item.unitName && <span className="oms-le__unit">{line!.item.unitName}</span>}
          </div>
        ) : (
          <div className="oms-le__search">
            <Select
              label="Item"
              placeholder="Search the catalogue…"
              options={items.map((i) => ({ value: i.id, label: `${i.code} · ${i.name}` }))}
              value={pickedItemId}
              onChange={(v) => v && seedFromItem(v)}
              onQueryChange={setQuery}
              emptyMessage={itemsQuery.isFetching ? 'Searching…' : 'No matching items'}
              ariaLabel="Item"
            />
            <p className="oms-le__hint">Type to search. Items already on the stocktake are excluded.</p>
          </div>
        )}

        {showBatches && (
          <div className="oms-le__batches">
            <div className="oms-le__batches-head">
              <span>Batch</span>
              <span className="oms-align-right">Snapshot</span>
              <span className="oms-align-right">Counted</span>
              <span>Reason</span>
            </div>
            {batches.map((b) => {
              const counted = b.counted === '' ? null : Number(b.counted);
              const dir = counted == null ? null : directionOf(b.snapshot, counted);
              const dirReasons = dir ? reasonsForDirection(reasons, dir) : [];
              const reasonRequired = dir != null && dirReasons.length > 0;
              return (
                <div key={b.key} className="oms-le__batch">
                  {b.isNew ? (
                    <div className="oms-le__newbatch">
                      <TextInput
                        placeholder="Batch"
                        value={b.batch}
                        onChange={(e) => patchBatch(b.key, { batch: e.target.value })}
                        aria-label="Batch"
                      />
                      <TextInput
                        type="date"
                        value={b.expiryDate}
                        onChange={(e) => patchBatch(b.key, { expiryDate: e.target.value })}
                        aria-label="Expiry"
                      />
                      <TextInput
                        type="number"
                        placeholder="Pack size"
                        value={b.packSize}
                        onChange={(e) => patchBatch(b.key, { packSize: e.target.value })}
                        aria-label="Pack size"
                      />
                    </div>
                  ) : (
                    <span className="oms-le__batch-label">{b.label}</span>
                  )}
                  <span className="oms-align-right tabular">{b.isNew ? '—' : formatNumber(b.snapshot)}</span>
                  <TextInput
                    type="number"
                    min={0}
                    value={b.counted}
                    onChange={(e) => patchBatch(b.key, { counted: e.target.value })}
                    aria-label="Counted packs"
                  />
                  <div className="oms-le__reason">
                    {reasonRequired ? (
                      <Select
                        size="compact"
                        optional={false}
                        options={dirReasons.map((r) => ({ value: r.id, label: r.reason }))}
                        value={b.reasonOptionId}
                        onChange={(v) => patchBatch(b.key, { reasonOptionId: v })}
                        placeholder="Reason required"
                        ariaLabel="Reason"
                      />
                    ) : (
                      <span className="oms-muted">—</span>
                    )}
                  </div>
                </div>
              );
            })}

            <Button variant="ghost" size="compact" icon="plus" onClick={addNewBatch}>
              Add new batch
            </Button>
          </div>
        )}
      </Modal>

      <ConfirmDialog
        open={confirmDiscard}
        onClose={() => setConfirmDiscard(false)}
        onConfirm={() => {
          setConfirmDiscard(false);
          onClose();
        }}
        title="Discard changes?"
        message="You have unsaved changes to this item's batches."
        confirmLabel="Discard"
        cancelLabel="Keep editing"
        destructive
      />
    </>
  );
}
