// solid/src/domain/stocktakes/StocktakeDetailPage.tsx
import { createResource, createSignal, createMemo, createEffect, Show, on, type JSX } from 'solid-js';
import { useParams } from '@solidjs/router';
import { Table, type Column } from '../../ui/Table';
import { Button } from '../../ui/Button';
import { SplitButton } from '../../ui/SplitButton';
import { StatusBadge } from '../../ui/StatusBadge';
import { StatusCrumbs } from '../../ui/StatusCrumbs';
import { Icon } from '../../ui/Icon';
import { ConfirmDialog } from '../../ui/ConfirmDialog';
import { Select } from '../../ui/Select';
import { LineEditor } from './StocktakeLineEditor';
import {
  fetchStocktakeByNumber,
  fetchStocktakeLines,
  updateStocktakeHeader,
  finaliseStocktake,
  batchLines,
  type FinaliseError,
} from './api';
import { fetchActiveReasonOptions, fetchLocations } from './reference';
import type { StocktakeLine } from './types';
import { isEditable, editBlockReason, difference, hasCountedLine, reasonsForDirection } from './rules';
import { createAutosave } from '../../lib/autosave';
import { formatDate, formatDateTime, formatSigned, formatNumber } from '../../lib/format';
import { toast } from '../../state/toast';
import './stocktakes.css';

/*
 * S3 — Stocktake detail (J4/J5/J6/J7). A read-only line table (line data is entered
 * only in the S4 editor — AC-D1/D2); in-place auto-saved header/metadata fields
 * (AC-E6/E7); a persistent status footer with the lock toggle, New→Finalised status
 * crumbs, and the finalise split button (AC-D3); bulk line actions when rows are
 * selected; and finalise with typed errors keyed to the offending lines. Every edit
 * affordance shares the one editability gate (NEW & unlocked).
 */

const LINE_PAGE_SIZE = 500;

export function StocktakeDetailPage(): JSX.Element {
  const params = useParams();
  const [refreshKey, setRefreshKey] = createSignal(0);

  const [header] = createResource(
    () => ({ storeId: params.storeId!, number: Number(params.number), _k: refreshKey() }),
    (s) => fetchStocktakeByNumber(s.storeId, s.number),
  );

  const [linesData] = createResource(
    () => {
      const h = header();
      return h ? { storeId: params.storeId!, stocktakeId: h.id, _k: refreshKey() } : undefined;
    },
    (s) => fetchStocktakeLines({ storeId: s.storeId, stocktakeId: s.stocktakeId, page: 1, pageSize: LINE_PAGE_SIZE }),
  );

  const [reasons] = createResource(fetchActiveReasonOptions, { initialValue: [] });
  const [locations] = createResource(() => params.storeId, fetchLocations, { initialValue: [] });

  const editable = () => (header() ? isEditable(header()!) : false);
  const blockReason = () => (header() ? editBlockReason(header()!) : null);

  /* ---------- In-place header autosave (AC-E6/E7) ---------- */
  const saveField = (patch: Parameters<typeof updateStocktakeHeader>[2]) =>
    updateStocktakeHeader(params.storeId!, header()!.id, patch);
  const asDescription = createAutosave('', (v) => saveField({ description: v }));
  const asComment = createAutosave('', (v) => saveField({ comment: v }));
  const asCountedBy = createAutosave('', (v) => saveField({ countedBy: v }));
  const asVerifiedBy = createAutosave('', (v) => saveField({ verifiedBy: v }));

  // Re-sync baselines when the record loads/refreshes (no write).
  createEffect(
    on(header, (h) => {
      if (!h) return;
      asDescription.sync(h.description ?? '');
      asComment.sync(h.comment ?? '');
      asCountedBy.sync(h.countedBy ?? '');
      asVerifiedBy.sync(h.verifiedBy ?? '');
    }),
  );

  /* ---------- View-only item filter (not a stored field) ---------- */
  const [itemFilter, setItemFilter] = createSignal('');
  const allLines = () => linesData()?.nodes ?? [];
  const lines = createMemo(() => {
    const q = itemFilter().trim().toLowerCase();
    if (!q) return allLines();
    return allLines().filter((l) => l.itemName.toLowerCase().includes(q) || l.item.code.toLowerCase().includes(q));
  });

  /* ---------- Selection + bulk actions (J5) ---------- */
  const [selected, setSelected] = createSignal<Set<string>>(new Set());
  const clearSelection = () => setSelected(new Set<string>());
  const toggle = (id: string) =>
    setSelected((p) => {
      const n = new Set(p);
      n.has(id) ? n.delete(id) : n.add(id);
      return n;
    });
  const toggleAll = () =>
    setSelected((p) => (p.size === lines().length ? new Set<string>() : new Set(lines().map((l) => l.id))));
  const selectedLines = () => allLines().filter((l) => selected().has(l.id));

  /* ---------- Editor (S4) ---------- */
  const [editorOpen, setEditorOpen] = createSignal(false);
  const [editIndex, setEditIndex] = createSignal(-1); // -1 = add-new
  const editingLine = () => (editIndex() >= 0 ? lines()[editIndex()] ?? null : null);
  const openEditor = (line: StocktakeLine | null) => {
    setEditIndex(line ? lines().findIndex((l) => l.id === line.id) : -1);
    setEditorOpen(true);
  };

  /* ---------- Finalise (J7) ---------- */
  const [finaliseOpen, setFinaliseOpen] = createSignal(false);
  const [finalising, setFinalising] = createSignal(false);
  const [finaliseErr, setFinaliseErr] = createSignal<FinaliseError | undefined>();
  const reducedStockLineIds = () => new Set(finaliseErr()?.reducedStockLineIds ?? []);
  const mismatchLineIds = () => new Set(finaliseErr()?.mismatchLineIds ?? []);

  const attemptFinalise = () => {
    if (!hasCountedLine(allLines())) {
      toast.warning('Nothing counted yet — count at least one line before finalising.');
      return;
    }
    setFinaliseErr(undefined);
    setFinaliseOpen(true);
  };
  const doFinalise = async () => {
    setFinalising(true);
    try {
      const res = await finaliseStocktake(params.storeId!, header()!.id);
      if (res.ok) {
        toast.success('Stocktake finalised.');
        setFinaliseOpen(false);
        setRefreshKey((k) => k + 1);
      } else {
        setFinaliseErr(res.error);
        setFinaliseOpen(false);
        toast.error(res.error.message);
      }
    } catch (e) {
      toast.error((e as Error).message);
    } finally {
      setFinalising(false);
    }
  };

  /* ---------- Lock toggle (J6) ---------- */
  const toggleLock = async () => {
    const h = header();
    if (!h) return;
    try {
      await updateStocktakeHeader(params.storeId!, h.id, { isLocked: !h.isLocked });
      setRefreshKey((k) => k + 1);
    } catch (e) {
      toast.error((e as Error).message);
    }
  };

  /* ---------- Bulk: reduce to zero / change location / delete (J5) ---------- */
  const [reduceOpen, setReduceOpen] = createSignal(false);
  const [reduceReason, setReduceReason] = createSignal<string | null>(null);
  const [bulkBusy, setBulkBusy] = createSignal(false);
  const [locOpen, setLocOpen] = createSignal(false);
  const [bulkLoc, setBulkLoc] = createSignal<string | null>(null);
  const [delLinesOpen, setDelLinesOpen] = createSignal(false);

  // Reduce-to-zero is a reduction: capture a reason when active reduction reasons exist (AC-E8).
  const reductionReasons = createMemo(() => reasonsForDirection(reasons(), 'negative'));
  const reduceReasonRequired = () => reductionReasons().length > 0;

  const applyReduceToZero = async () => {
    setBulkBusy(true);
    try {
      const updates = selectedLines().map((l) => ({
        id: l.id,
        countedNumberOfPacks: 0,
        reasonOptionId: reduceReason() ?? undefined,
      }));
      const errs = await batchLines(params.storeId!, header()!.id, [], updates, []);
      if (errs.length) toast.error(errs[0]!.message);
      else toast.success(`Reduced ${updates.length} line(s) to zero.`);
      setReduceOpen(false);
      setReduceReason(null);
      clearSelection();
      setRefreshKey((k) => k + 1);
    } finally {
      setBulkBusy(false);
    }
  };
  const applyChangeLocation = async () => {
    setBulkBusy(true);
    try {
      const updates = selectedLines().map((l) => ({ id: l.id, locationId: bulkLoc() }));
      const errs = await batchLines(params.storeId!, header()!.id, [], updates, []);
      if (errs.length) toast.error(errs[0]!.message);
      else toast.success(`Moved ${updates.length} line(s).`);
      setLocOpen(false);
      clearSelection();
      setRefreshKey((k) => k + 1);
    } finally {
      setBulkBusy(false);
    }
  };
  const applyDeleteLines = async () => {
    setBulkBusy(true);
    try {
      const errs = await batchLines(params.storeId!, header()!.id, [], [], [...selected()]);
      if (errs.length) toast.error(errs[0]!.message);
      else toast.success(`Deleted ${selected().size} line(s).`);
      setDelLinesOpen(false);
      clearSelection();
      setRefreshKey((k) => k + 1);
    } finally {
      setBulkBusy(false);
    }
  };

  /* ---------- Side panel ---------- */
  const [panelOpen, setPanelOpen] = createSignal(true);
  const copyRecord = async () => {
    const h = header();
    if (!h) return;
    const text = `Stocktake #${h.stocktakeNumber}\nStatus: ${h.status}\nDescription: ${h.description ?? ''}\nCreated: ${formatDateTime(h.createdDatetime)}\nLines: ${h.lineCount}`;
    try {
      await navigator.clipboard.writeText(text);
      toast.success('Copied to clipboard.');
    } catch {
      toast.error('Copy failed.');
    }
  };

  /* ---------- Line table columns (S3) ---------- */
  const columns: Column<StocktakeLine>[] = [
    {
      key: 'code',
      header: 'Code',
      width: '110px',
      render: (l) => (
        <span class="st-cell-code">
          <Show when={reducedStockLineIds().has(l.stockLine?.id ?? '') || mismatchLineIds().has(l.id)}>
            <Icon name="circle-alert" size={14} label="Line error" class="cell-error-icon" />
          </Show>
          {l.item.code}
        </span>
      ),
      cardHidden: true,
    },
    { key: 'name', header: 'Item', render: (l) => <span class="cell-truncate">{l.itemName}</span> },
    { key: 'batch', header: 'Batch', priority: 3, render: (l) => l.batch || '—' },
    { key: 'expiry', header: 'Expiry', priority: 2, render: (l) => formatDate(l.expiryDate) || '—' },
    { key: 'location', header: 'Location', priority: 3, render: (l) => l.location?.code || '—' },
    { key: 'unit', header: 'Unit', priority: 2, render: (l) => l.item.unitName || '—' },
    { key: 'packSize', header: 'Pack size', priority: 2, align: 'right', render: (l) => <span class="tabular">{formatNumber(l.packSize)}</span> },
    {
      key: 'snapshot',
      header: 'Snapshot',
      align: 'right',
      render: (l) => (
        <span class={`tabular${mismatchLineIds().has(l.id) ? ' cell-error' : ''}`}>
          {formatNumber(l.snapshotNumberOfPacks)}
          <Show when={mismatchLineIds().has(l.id)}>
            <Icon name="circle-alert" size={12} label="Snapshot no longer matches current stock" />
          </Show>
        </span>
      ),
    },
    {
      key: 'counted',
      header: 'Counted',
      align: 'right',
      render: (l) => (
        <span class={`tabular${reducedStockLineIds().has(l.stockLine?.id ?? '') ? ' cell-error' : ''}`}>
          {l.countedNumberOfPacks == null ? '—' : formatNumber(l.countedNumberOfPacks)}
        </span>
      ),
    },
    {
      key: 'difference',
      header: 'Difference',
      align: 'right',
      render: (l) => <span class="tabular">{l.countedNumberOfPacks == null ? '—' : formatSigned(difference(l))}</span>,
    },
    { key: 'reason', header: 'Reason', priority: 2, render: (l) => l.reasonOption?.reason || '—' },
    { key: 'comment', header: 'Comment', priority: 3, render: (l) => <span class="cell-truncate">{l.comment || '—'}</span> },
  ];

  const selection = {
    isSelected: (id: string) => selected().has(id),
    onToggle: toggle,
    onToggleAll: toggleAll,
    get allSelected() {
      return lines().length > 0 && selected().size === lines().length;
    },
    get someSelected() {
      return selected().size > 0;
    },
  };

  const crumbSteps = () => {
    const h = header();
    return [
      { key: 'NEW', label: 'New', reachedAt: h?.createdDatetime },
      { key: 'FINALISED', label: 'Finalised', reachedAt: h?.finalisedDatetime },
    ];
  };

  return (
    <Show when={header()} fallback={<DetailFallback loading={header.loading} error={header.error as Error | undefined} />}>
      {(h) => (
        <div class={`page detail${panelOpen() ? ' with-panel' : ''}`}>
          {/* App bar / toolbar: description + item search + actions */}
          <div class="detail-toolbar">
            <div class="detail-title">
              <span class="detail-number tabular">#{h().stocktakeNumber}</span>
              <input
                class="input detail-description"
                placeholder="Description"
                disabled={!editable()}
                value={asDescription.value()}
                onInput={(e) => asDescription.set(e.currentTarget.value)}
                onBlur={() => asDescription.flush()}
                aria-label="Description"
              />
            </div>
            <div class="detail-toolbar-actions">
              <input
                class="input input-compact detail-search"
                placeholder="Filter items…"
                value={itemFilter()}
                onInput={(e) => setItemFilter(e.currentTarget.value)}
                aria-label="Filter items"
              />
              <Button
                label="Add item"
                icon="plus-circle"
                variant="secondary"
                compact
                disabled={!editable()}
                title={editable() ? undefined : 'Not editable'}
                onClick={() => openEditor(null)}
              />
              <Button label="Report" icon="printer" variant="ghost" compact onClick={() => toast.info('Report generation is out of scope for this build.')} />
              <Button
                icon="sidebar"
                aria-label="Toggle detail panel"
                variant="ghost"
                compact
                onClick={() => setPanelOpen((v) => !v)}
              />
            </div>
          </div>

          {/* Locked / finalised banner */}
          <Show when={blockReason()}>
            <div class={`detail-banner banner-${blockReason() === 'finalised' ? 'info' : 'warning'}`}>
              <Icon name={blockReason() === 'finalised' ? 'info' : 'alert'} size={20} />
              <span>
                {blockReason() === 'finalised'
                  ? 'This stocktake is finalised and read-only.'
                  : 'This stocktake is on hold (locked). Unlock it to make changes.'}
              </span>
            </div>
          </Show>
          <Show when={finaliseErr()}>
            <div class="detail-banner banner-error">
              <Icon name="circle-alert" size={20} />
              <span>{finaliseErr()!.message}</span>
            </div>
          </Show>

          <div class="detail-main">
            {/* Content body: read-only line table */}
            <div class="page-body detail-body">
              <Table
                caption="Stocktake lines"
                columns={columns}
                rows={lines()}
                rowKey={(l) => l.id}
                selection={editable() ? selection : undefined}
                onRowClick={(l) => openEditor(l)}
                rowError={(l) => reducedStockLineIds().has(l.stockLine?.id ?? '') || mismatchLineIds().has(l.id)}
                state={linesData.loading && !linesData() ? 'loading' : lines().length === 0 ? (itemFilter() ? 'empty-no-matches' : 'empty-no-records') : 'normal'}
                emptyMessage="No lines yet. Use Add item to start counting."
                onClearFilters={() => setItemFilter('')}
                cardTitle={(l) => <>{l.item.code} — {l.itemName}</>}
              />
            </div>

            {/* Side panel */}
            <Show when={panelOpen()}>
              <aside class="detail-panel">
                <h3 class="panel-heading">Details</h3>
                <dl class="panel-fields">
                  <dt>Status</dt>
                  <dd><StatusBadge label={h().status === 'NEW' ? 'New' : 'Finalised'} tone={h().status === 'NEW' ? 'info' : 'success'} /></dd>
                  <dt>Entered by</dt>
                  <dd>{h().user?.username ?? '—'}</dd>
                  <dt>Created</dt>
                  <dd class="tabular">{formatDateTime(h().createdDatetime)}</dd>
                  <Show when={h().finalisedDatetime}>
                    <dt>Finalised</dt>
                    <dd class="tabular">{formatDateTime(h().finalisedDatetime)}</dd>
                  </Show>
                  <dt>Lines</dt>
                  <dd class="tabular">{h().lineCount}</dd>
                </dl>

                <label class="field">
                  <span class="field-label">Counted by</span>
                  <input class="input" disabled={!editable()} value={asCountedBy.value()} onInput={(e) => asCountedBy.set(e.currentTarget.value)} onBlur={() => asCountedBy.flush()} />
                </label>
                <label class="field">
                  <span class="field-label">Verified by</span>
                  <input class="input" disabled={!editable()} value={asVerifiedBy.value()} onInput={(e) => asVerifiedBy.set(e.currentTarget.value)} onBlur={() => asVerifiedBy.flush()} />
                </label>
                <label class="field">
                  <span class="field-label">Comment</span>
                  <textarea class="input textarea" disabled={!editable()} value={asComment.value()} onInput={(e) => asComment.set(e.currentTarget.value)} onBlur={() => asComment.flush()} />
                </label>

                <div class="panel-actions">
                  <Button label="Copy" icon="copy" variant="ghost" compact onClick={copyRecord} />
                  <Show when={editable()}>
                    <Button label="Delete" icon="delete" variant="destructive" compact onClick={() => toast.info('Delete this stocktake from the list view.')} />
                  </Show>
                </div>
              </aside>
            </Show>
          </div>

          {/* Action footer: bulk bar when rows selected, else lifecycle controls */}
          <div class="action-footer">
            <Show
              when={selected().size === 0}
              fallback={
                <div class="bulk-bar">
                  <Button icon="minus-circle" aria-label="Clear selection" variant="ghost" compact onClick={clearSelection} />
                  <span class="bulk-count">{selected().size} selected</span>
                  <div class="bulk-actions">
                    <Button label="Reduce to zero" icon="rewind" variant="secondary" compact onClick={() => { setReduceReason(null); setReduceOpen(true); }} />
                    <Button label="Change location" icon="arrow-right" variant="secondary" compact onClick={() => { setBulkLoc(null); setLocOpen(true); }} />
                    <Button label="Delete" icon="delete" variant="destructive" compact onClick={() => setDelLinesOpen(true)} />
                  </div>
                </div>
              }
            >
              <div class="footer-lock">
                <Show when={h().status === 'NEW'}>
                  <button type="button" class={`lock-toggle${h().isLocked ? ' lock-on' : ''}`} onClick={toggleLock} aria-pressed={h().isLocked}>
                    {h().isLocked ? 'On hold' : 'Hold'}
                  </button>
                </Show>
              </div>
              <StatusCrumbs steps={crumbSteps()} current={h().status} />
              <Show when={editable()}>
                <SplitButton
                  icon="arrow-right"
                  options={[
                    { value: 'NEW', label: 'New', disabled: true },
                    { value: 'FINALISED', label: 'Save and confirm → Finalised' },
                  ]}
                  selected="FINALISED"
                  onSelect={() => {}}
                  onPrimary={() => attemptFinalise()}
                />
              </Show>
            </Show>
          </div>

          {/* Line editor */}
          <LineEditor
            open={editorOpen()}
            storeId={params.storeId!}
            stocktakeId={h().id}
            reasons={reasons()}
            locations={locations()}
            line={editingLine()}
            existingItemIds={allLines().map((l) => l.itemId)}
            onClose={() => setEditorOpen(false)}
            onSaved={() => {
              setEditorOpen(false);
              setRefreshKey((k) => k + 1);
            }}
            onNavigate={(delta) => {
              const next = editIndex() + delta;
              if (next >= 0 && next < lines().length) setEditIndex(next);
            }}
            navPrevDisabled={editIndex() <= 0}
            navNextDisabled={editIndex() < 0 || editIndex() >= lines().length - 1}
          />

          {/* Finalise confirmation */}
          <ConfirmDialog
            open={finaliseOpen()}
            title="Finalise stocktake?"
            message="This applies all counted differences as inventory adjustments and makes the stocktake read-only. Uncounted lines are dropped."
            confirmLabel="Save and confirm"
            busy={finalising()}
            onConfirm={doFinalise}
            onCancel={() => setFinaliseOpen(false)}
          />

          {/* Bulk reduce-to-zero (captures a reason when required) */}
          <ConfirmDialog
            open={reduceOpen()}
            title="Reduce selected lines to zero?"
            message={`Set counted = 0 for ${selected().size} selected line(s).`}
            confirmLabel="Reduce to zero"
            busy={bulkBusy()}
            confirmDisabled={reduceReasonRequired() && !reduceReason()}
            onConfirm={applyReduceToZero}
            onCancel={() => setReduceOpen(false)}
          >
            <Show when={reduceReasonRequired()}>
              <Select
                label="Reason (required)"
                placeholder="Choose a reason"
                required
                options={reductionReasons().map((r) => ({ value: r.id, label: r.reason }))}
                value={reduceReason()}
                onChange={setReduceReason}
              />
            </Show>
          </ConfirmDialog>

          {/* Bulk change location */}
          <ConfirmDialog
            open={locOpen()}
            title="Change location"
            message={`Move ${selected().size} selected line(s) to:`}
            confirmLabel="Apply"
            busy={bulkBusy()}
            onConfirm={applyChangeLocation}
            onCancel={() => setLocOpen(false)}
          >
            <Select
              label="Location"
              placeholder="No location"
              options={locations().map((l) => ({ value: l.id, label: `${l.code} — ${l.name}` }))}
              value={bulkLoc()}
              onChange={setBulkLoc}
            />
          </ConfirmDialog>

          {/* Bulk delete lines */}
          <ConfirmDialog
            open={delLinesOpen()}
            title="Delete selected lines?"
            message={`Permanently delete ${selected().size} selected line(s)?`}
            destructive
            confirmLabel="Delete"
            busy={bulkBusy()}
            onConfirm={applyDeleteLines}
            onCancel={() => setDelLinesOpen(false)}
          />
        </div>
      )}
    </Show>
  );
}

function DetailFallback(props: { loading: boolean; error?: Error }): JSX.Element {
  return (
    <div class="page">
      <div class="page-body detail-fallback">
        <Show when={props.loading}>
          <p>Loading stocktake…</p>
        </Show>
        <Show when={props.error}>
          <Icon name="circle-alert" size={32} />
          <p>{props.error?.message}</p>
        </Show>
        <Show when={!props.loading && !props.error}>
          <Icon name="circle-alert" size={32} />
          <p>Stocktake not found.</p>
        </Show>
      </div>
    </div>
  );
}

// react/src/features/stocktakes/StocktakeDetailPage.tsx
import { useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { PageLayout } from '@/app/layout/PageLayout';
import { DataTable, type Column } from '@/components/DataTable';
import { Button } from '@/components/Button';
import { Banner } from '@/components/Banner';
import { StatusBadge } from '@/components/StatusBadge';
import { StatusCrumbs } from '@/components/StatusCrumbs';
import { SplitButton } from '@/components/SplitButton';
import { EditableField } from '@/components/EditableField';
import { TextInput } from '@/components/Field';
import { Toggle } from '@/components/Toggle';
import { ConfirmDialog } from '@/components/ConfirmDialog';
import { Icon } from '@/icons/Icon';
import { useToast } from '@/components/Toast';
import { useStoreId } from '@/app/auth/AuthContext';
import { formatDate, formatDateTime, formatSigned, formatNumber } from '@/lib/format';
import { fetchStocktakeByNumber } from './api';
import {
  fetchReasonOptions,
  fetchStocktakeLines,
  finaliseStocktake,
  updateStocktakeHeader,
} from './linesApi';
import { LineEditor } from './LineEditor';
import { BulkLineActions } from './BulkLineActions';
import type { StocktakeLine } from './types';
import './StocktakeDetailPage.css';

export function StocktakeDetailPage() {
  const { number } = useParams();
  const storeId = useStoreId();
  const navigate = useNavigate();
  const toast = useToast();
  const qc = useQueryClient();

  const [showPanel, setShowPanel] = useState(true);
  const [itemFilter, setItemFilter] = useState('');
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [editorFor, setEditorFor] = useState<StocktakeLine | 'new' | null>(null);
  const [confirmFinalise, setConfirmFinalise] = useState(false);
  const [confirmDelete, setConfirmDelete] = useState(false);
  const [finaliseStatus, setFinaliseStatus] = useState<'FINALISED'>('FINALISED');
  const [bannerError, setBannerError] = useState<string | null>(null);
  const [mismatchKeys, setMismatchKeys] = useState<Set<string>>(new Set()); // snapshot-cell
  const [reducedKeys, setReducedKeys] = useState<Set<string>>(new Set()); // counted-cell

  // Header (by number → gives id used for line queries + mutations).
  const headerQuery = useQuery({
    queryKey: ['stocktake', storeId, number],
    queryFn: () => fetchStocktakeByNumber(storeId!, Number(number)),
    enabled: !!storeId && !!number,
  });
  const st = headerQuery.data;
  const stocktakeId = st?.id;

  const linesQuery = useQuery({
    queryKey: ['stocktakeLines', storeId, stocktakeId],
    queryFn: () => fetchStocktakeLines(storeId!, stocktakeId!),
    enabled: !!storeId && !!stocktakeId,
  });
  const reasonsQuery = useQuery({
    queryKey: ['reasons', storeId],
    queryFn: () => fetchReasonOptions(),
    enabled: !!storeId,
  });

  const lines = linesQuery.data?.nodes ?? [];
  const editable = st?.status === 'NEW' && !st?.isLocked;

  const refetchAll = () => {
    qc.invalidateQueries({ queryKey: ['stocktake', storeId, number] });
    qc.invalidateQueries({ queryKey: ['stocktakeLines', storeId, stocktakeId] });
    // A corrective edit clears the previous finalise-failure markers (they refer to stale data).
    setBannerError(null);
    setMismatchKeys(new Set());
    setReducedKeys(new Set());
  };

  // ---- Header in-place saves ----
  const saveHeader = (patch: Record<string, string>) =>
    updateStocktakeHeader(storeId!, { id: stocktakeId!, ...patch }).then(() => {
      qc.invalidateQueries({ queryKey: ['stocktake', storeId, number] });
    });

  const lockMutation = useMutation({
    mutationFn: (isLocked: boolean) =>
      updateStocktakeHeader(storeId!, { id: stocktakeId!, isLocked }),
    onSuccess: () => refetchAll(),
    onError: (e) => toast.error((e as Error).message),
  });

  const finalise = useMutation({
    mutationFn: () => finaliseStocktake(storeId!, stocktakeId!),
    onSuccess: (res) => {
      setConfirmFinalise(false);
      if (res.ok) {
        setBannerError(null);
        setMismatchKeys(new Set());
        setReducedKeys(new Set());
        toast.success('Stocktake finalised');
        refetchAll();
      } else {
        setBannerError(res.bannerError ?? 'Finalise failed');
        setMismatchKeys(new Set(res.mismatchKeys ?? []));
        setReducedKeys(new Set(res.reducedKeys ?? []));
        toast.error('Finalise blocked — see errors');
      }
    },
    onError: (e) => {
      setConfirmFinalise(false);
      toast.error((e as Error).message);
    },
  });

  const filteredLines = useMemo(() => {
    const q = itemFilter.trim().toLowerCase();
    if (!q) return lines;
    return lines.filter(
      (l) =>
        l.itemName.toLowerCase().includes(q) ||
        l.item.code.toLowerCase().includes(q) ||
        (l.batch ?? '').toLowerCase().includes(q),
    );
  }, [lines, itemFilter]);

  const errorOn = useMemo(() => {
    const mismatch = (l: StocktakeLine) => mismatchKeys.has(l.id);
    const reduced = (l: StocktakeLine) => (l.stockLine?.id ? reducedKeys.has(l.stockLine.id) : false);
    return {
      mismatch, // → snapshot cell
      reduced, //  → counted cell
      any: (l: StocktakeLine) => mismatch(l) || reduced(l),
    };
  }, [mismatchKeys, reducedKeys]);
  const lineHasError = errorOn.any;

  const columns = useMemo<Column<StocktakeLine>[]>(() => {
    const diff = (l: StocktakeLine) =>
      l.countedNumberOfPacks == null ? 0 : l.countedNumberOfPacks - l.snapshotNumberOfPacks;
    return [
      {
        key: 'code',
        header: 'Code',
        priority: 1,
        width: 120,
        render: (l) => (
          <span className="oms-line-code">
            {lineHasError(l) && (
              <Icon
                name="circle-alert"
                size={14}
                title="This line blocked finalise"
                className="oms-line-err"
              />
            )}
            {l.item.code}
          </span>
        ),
      },
      { key: 'name', header: 'Item', priority: 1, render: (l) => l.itemName },
      { key: 'batch', header: 'Batch', priority: 3, render: (l) => l.batch || '—' },
      {
        key: 'expiry',
        header: 'Expiry',
        priority: 2,
        width: 110,
        render: (l) => (l.expiryDate ? formatDate(l.expiryDate) : '—'),
      },
      {
        key: 'manufactureDate',
        header: 'Manufactured',
        priority: 3,
        width: 120,
        render: (l) => (l.manufactureDate ? formatDate(l.manufactureDate) : '—'),
      },
      { key: 'location', header: 'Location', priority: 3, render: (l) => l.location?.name || '—' },
      { key: 'unitName', header: 'Unit', priority: 2, width: 90, render: (l) => l.item.unitName || '—' },
      {
        key: 'packSize',
        header: 'Pack size',
        priority: 2,
        align: 'right',
        width: 90,
        render: (l) => formatNumber(l.packSize),
      },
      {
        key: 'snapshot',
        header: 'Snapshot',
        priority: 1,
        align: 'right',
        width: 110,
        render: (l) => (
          <span className="oms-cell-num">
            {errorOn.mismatch(l) && (
              <Icon
                name="circle-alert"
                size={14}
                title="Snapshot no longer matches current stock"
                className="oms-line-err"
              />
            )}
            {formatNumber(l.snapshotNumberOfPacks)}
          </span>
        ),
      },
      {
        key: 'counted',
        header: 'Counted',
        priority: 1,
        align: 'right',
        width: 110,
        render: (l) => (
          <span className="oms-cell-num">
            {errorOn.reduced(l) && (
              <Icon
                name="circle-alert"
                size={14}
                title="This count would reduce stock below zero"
                className="oms-line-err"
              />
            )}
            {l.countedNumberOfPacks == null ? (
              <span className="oms-muted">—</span>
            ) : (
              formatNumber(l.countedNumberOfPacks)
            )}
          </span>
        ),
      },
      {
        key: 'difference',
        header: 'Difference',
        priority: 1,
        align: 'right',
        width: 100,
        render: (l) => {
          const d = diff(l);
          return <span className={d !== 0 ? 'oms-diff' : undefined}>{formatSigned(d)}</span>;
        },
      },
      { key: 'reason', header: 'Reason', priority: 2, render: (l) => l.reasonOption?.reason || '—' },
      { key: 'manufacturer', header: 'Manufacturer', priority: 3, render: (l) => l.manufacturer?.name || '—' },
      {
        key: 'comment',
        header: 'Comment',
        priority: 3,
        render: (l) => l.comment || '—',
      },
    ];
  }, [errorOn]);

  // ---- Finalise guard: needs at least one counted line ----
  const hasCountedLine = lines.some((l) => l.countedNumberOfPacks != null);
  const onFinaliseActivate = () => {
    if (!hasCountedLine) {
      toast.info('Nothing counted yet — count at least one line to finalise.');
      return;
    }
    setConfirmFinalise(true);
  };

  // ---- App bar ----
  const appBar = (
    <div className="oms-detail-appbar">
      <div className="oms-detail-appbar__top">
        <Button variant="ghost" size="compact" icon="arrow-left" onClick={() => navigate('/inventory/stocktakes')}>
          Stocktakes
        </Button>
        {st && (
          <>
            <h1 className="oms-detail-appbar__title">Stocktake #{st.stocktakeNumber}</h1>
            <StatusBadge
              label={st.status === 'NEW' ? 'New' : 'Finalised'}
              tone={st.status === 'NEW' ? 'info' : 'success'}
            />
          </>
        )}
        <div className="oms-detail-appbar__spacer" />
        <Button
          variant="secondary"
          size="compact"
          icon="plus-circle"
          disabled={!editable}
          onClick={() => setEditorFor('new')}
        >
          Add item
        </Button>
        <Button
          variant="ghost"
          size="compact"
          icon="printer"
          aria-label="Generate report"
          title="Generate report"
          onClick={() => toast.info('Report generation is out of scope for this build.')}
        />
        <Button
          variant="ghost"
          size="compact"
          icon="sidebar"
          aria-label="Toggle details"
          title="Toggle details"
          onClick={() => setShowPanel((v) => !v)}
        />
      </div>
      <div className="oms-detail-appbar__meta">
        <EditableField
          label="Description"
          value={st?.description ?? ''}
          readOnly={!editable}
          placeholder="Add a description"
          onSave={(v) => saveHeader({ description: v })}
        />
        <TextInput
          label="Find item in this stocktake"
          placeholder="Filter lines…"
          value={itemFilter}
          onChange={(e) => setItemFilter(e.target.value)}
        />
      </div>
    </div>
  );

  // ---- Footer: bulk bar when selecting, else lifecycle controls ----
  const footer =
    selected.size > 0 ? (
      <BulkLineActions
        storeId={storeId!}
        stocktakeId={stocktakeId!}
        selectedIds={[...selected]}
        reasons={reasonsQuery.data ?? []}
        onClear={() => setSelected(new Set())}
        onDone={() => {
          setSelected(new Set());
          refetchAll();
        }}
      />
    ) : st ? (
      <div className="oms-detail-footer">
        <div className="oms-detail-footer__lock">
          <Toggle
            checked={st.isLocked}
            disabled={st.status === 'FINALISED' || lockMutation.isPending}
            onChange={(v) => lockMutation.mutate(v)}
            label="On hold"
          />
        </div>
        <StatusCrumbs
          currentKey={st.status}
          steps={[
            { key: 'NEW', label: 'New', reachedAt: st.createdDatetime },
            { key: 'FINALISED', label: 'Finalised', reachedAt: st.finalisedDatetime },
          ]}
        />
        <div className="oms-detail-footer__spacer" />
        {editable && (
          <SplitButton
            options={[
              { key: 'NEW', label: 'New', disabled: true },
              { key: 'FINALISED', label: 'Save and confirm' },
            ]}
            selectedKey={finaliseStatus}
            onSelectedChange={(k) => setFinaliseStatus(k as 'FINALISED')}
            onActivate={onFinaliseActivate}
            busy={finalise.isPending}
          />
        )}
      </div>
    ) : undefined;

  // ---- Side panel ----
  const sidePanel = st ? (
    <div className="oms-detail-panel">
      <h2 className="oms-detail-panel__heading">Details</h2>
      <EditableField
        label="Counted by"
        value={st.countedBy ?? ''}
        readOnly={!editable}
        onSave={(v) => saveHeader({ countedBy: v })}
      />
      <EditableField
        label="Verified by"
        value={st.verifiedBy ?? ''}
        readOnly={!editable}
        onSave={(v) => saveHeader({ verifiedBy: v })}
      />
      <EditableField
        label="Comment"
        value={st.comment ?? ''}
        readOnly={!editable}
        multiline
        onSave={(v) => saveHeader({ comment: v })}
      />
      <dl className="oms-detail-panel__facts">
        <Fact label="Entered by" value={st.user?.username || '—'} />
        <Fact label="Created" value={formatDateTime(st.createdDatetime)} />
        <Fact label="Finalised" value={st.finalisedDatetime ? formatDateTime(st.finalisedDatetime) : '—'} />
      </dl>
      <div className="oms-detail-panel__actions">
        <Button
          variant="ghost"
          size="compact"
          icon="copy"
          onClick={() => {
            navigator.clipboard?.writeText(JSON.stringify(st, null, 2));
            toast.success('Copied record to clipboard');
          }}
        >
          Copy
        </Button>
        {editable && (
          <Button variant="destructive" size="compact" icon="delete" onClick={() => setConfirmDelete(true)}>
            Delete
          </Button>
        )}
      </div>
    </div>
  ) : undefined;

  return (
    <PageLayout appBar={appBar} footer={footer} sidePanel={sidePanel} sidePanelOpen={showPanel}>
      {/* Editability messaging (locked = reversible, finalised = permanent) */}
      {st?.status === 'FINALISED' && (
        <Banner tone="info" title="Finalised — read only">
          This stocktake is finalised. Its differences have been applied as inventory
          adjustments and it can no longer be edited.
        </Banner>
      )}
      {st?.status === 'NEW' && st.isLocked && (
        <Banner
          tone="warning"
          title="On hold — editing is blocked"
          action={
            <Button variant="secondary" size="compact" onClick={() => lockMutation.mutate(false)}>
              Unlock to edit
            </Button>
          }
        >
          Turn off "On hold" to resume editing.
        </Banner>
      )}
      {bannerError && (
        <Banner tone="error" title="Finalise blocked">
          {bannerError}
        </Banner>
      )}

      <div className="oms-detail-table">
        <DataTable
          caption="Stocktake lines"
          columns={columns}
          rows={filteredLines}
          rowKey={(l) => l.id}
          selectable={editable}
          selectedIds={selected}
          onSelectionChange={setSelected}
          onRowClick={(l) => setEditorFor(l)}
          rowError={lineHasError}
          loading={linesQuery.isLoading}
          error={linesQuery.isError ? (linesQuery.error as Error).message : undefined}
          onRetry={() => linesQuery.refetch()}
          isFiltered={!!itemFilter}
          onClearFilters={() => setItemFilter('')}
          emptyMessage={editable ? 'No lines yet — add an item to start counting' : 'No lines'}
          emptyFilteredMessage="No lines match your search"
        />
      </div>

      {editorFor && stocktakeId && (
        <LineEditor
          storeId={storeId!}
          stocktakeId={stocktakeId}
          line={editorFor === 'new' ? null : editorFor}
          allLines={lines}
          existingItemIds={lines.map((l) => l.itemId)}
          reasons={reasonsQuery.data ?? []}
          onClose={() => setEditorFor(null)}
          onSaved={() => {
            setEditorFor(null);
            refetchAll();
          }}
        />
      )}

      <ConfirmDialog
        open={confirmFinalise}
        onClose={() => setConfirmFinalise(false)}
        onConfirm={() => finalise.mutate()}
        title="Finalise stocktake?"
        message="This applies all counted differences as inventory adjustments and cannot be undone. Uncounted lines are removed."
        confirmLabel="Save and confirm"
        busy={finalise.isPending}
      />
      <DeleteStocktakeConfirm
        open={confirmDelete}
        storeId={storeId!}
        id={stocktakeId}
        onClose={() => setConfirmDelete(false)}
        onDeleted={() => {
          toast.success('Stocktake deleted');
          navigate('/inventory/stocktakes');
        }}
      />
    </PageLayout>
  );
}

function Fact({ label, value }: { label: string; value: string }) {
  return (
    <div className="oms-detail-panel__fact">
      <dt>{label}</dt>
      <dd>{value}</dd>
    </div>
  );
}

// Delete uses the header batch-delete endpoint from the list api.
import { deleteStocktakes } from './api';
function DeleteStocktakeConfirm({
  open,
  storeId,
  id,
  onClose,
  onDeleted,
}: {
  open: boolean;
  storeId: string;
  id: string | undefined;
  onClose: () => void;
  onDeleted: () => void;
}) {
  const toast = useToast();
  const del = useMutation({
    mutationFn: () => deleteStocktakes(storeId, [id!]),
    onSuccess: (res) => {
      onClose();
      if (res[0]?.ok) onDeleted();
      else toast.error(res[0]?.error ?? 'Could not delete');
    },
    onError: (e) => {
      onClose();
      toast.error((e as Error).message);
    },
  });
  return (
    <ConfirmDialog
      open={open}
      onClose={onClose}
      onConfirm={() => del.mutate()}
      title="Delete this stocktake?"
      message="This cannot be undone."
      confirmLabel="Delete"
      destructive
      busy={del.isPending}
    />
  );
}
