// solid/src/domain/stocktakes/StocktakeListPage.tsx
import { createResource, createSignal, createMemo, Show, type JSX } from 'solid-js';
import { useParams, useNavigate, useSearchParams } from '@solidjs/router';
import { Table, type Column, type TableState } from '../../ui/Table';
import { FilterBar } from '../../ui/FilterBar';
import { Button } from '../../ui/Button';
import { StatusBadge } from '../../ui/StatusBadge';
import { ConfirmDialog } from '../../ui/ConfirmDialog';
import { CreateStocktakeModal } from './StocktakeCreateModal';
import { fetchStocktakes, deleteStocktakes } from './api';
import type { StocktakeListItem } from './types';
import { formatDate } from '../../lib/format';
import { toCsv, downloadCsv } from '../../lib/csv';
import { toast } from '../../state/toast';
import './stocktakes.css';

/*
 * S1 — Stocktake list. Paginated, sortable table; a status filter (New / Finalised)
 * added from the filter menu and persisted in the URL (AC-L1); bulk delete (AC-L2);
 * CSV export (AC-L3); rows open the detail by human number (AC-L4). List state
 * (filter/sort/page) lives in the URL and replaces history (urls.md).
 */

const PAGE_SIZE = 25;
const DEFAULT_SORT = 'createdDatetime:desc';

function parseSort(sort: string | undefined): { key: string; desc: boolean } {
  const [key, dir] = (sort ?? DEFAULT_SORT).split(':');
  return { key: key!, desc: dir === 'desc' };
}

export function StocktakeListPage(): JSX.Element {
  const params = useParams();
  const navigate = useNavigate();
  const [search, setSearch] = useSearchParams();

  const status = () => (search.status as string | undefined) || undefined;
  const sort = () => parseSort(search.sort as string | undefined);
  const page = () => Number(search.page ?? 1) || 1;

  // Replace history for list-state changes (Back shouldn't unwind each tweak).
  const setListState = (patch: Record<string, string | undefined>) =>
    setSearch(patch, { replace: true });

  const [refreshKey, setRefreshKey] = createSignal(0);
  const source = createMemo(() => ({
    storeId: params.storeId!,
    status: status() as StocktakeListItem['status'] | undefined,
    sortKey: sort().key,
    sortDesc: sort().desc,
    page: page(),
    _k: refreshKey(),
  }));

  const [data] = createResource(source, (s) =>
    fetchStocktakes({
      storeId: s.storeId,
      status: s.status,
      sortKey: s.sortKey,
      sortDesc: s.sortDesc,
      page: s.page,
      pageSize: PAGE_SIZE,
    }),
  );

  const [selected, setSelected] = createSignal<Set<string>>(new Set());
  const [confirmDelete, setConfirmDelete] = createSignal(false);
  const [deleting, setDeleting] = createSignal(false);
  const [createOpen, setCreateOpen] = createSignal(false);

  const rows = () => data()?.nodes ?? [];
  const totalCount = () => data()?.totalCount ?? 0;
  const totalPages = () => Math.max(1, Math.ceil(totalCount() / PAGE_SIZE));

  const tableState = (): TableState => {
    if (data.loading && !data()) return 'loading';
    if (data.error) return 'error';
    if (rows().length === 0) return status() ? 'empty-no-matches' : 'empty-no-records';
    return 'normal';
  };

  const toggle = (id: string) =>
    setSelected((prev) => {
      const next = new Set(prev);
      next.has(id) ? next.delete(id) : next.add(id);
      return next;
    });
  const toggleAll = () =>
    setSelected((prev) => (prev.size === rows().length ? new Set<string>() : new Set(rows().map((r) => r.id))));

  const onSort = (key: string) => {
    const cur = sort();
    const desc = cur.key === key ? !cur.desc : true;
    setListState({ sort: `${key}:${desc ? 'desc' : 'asc'}`, page: undefined });
  };

  const doDelete = async () => {
    setDeleting(true);
    try {
      await deleteStocktakes(params.storeId!, [...selected()]);
      toast.success(`Deleted ${selected().size} stocktake(s).`);
      setSelected(new Set<string>());
      setConfirmDelete(false);
      setRefreshKey((k) => k + 1);
    } catch (e) {
      toast.error((e as Error).message);
    } finally {
      setDeleting(false);
    }
  };

  const exportCsv = () => {
    const headers = ['Number', 'Status', 'Description', 'Comment', 'Created', 'Finalised', 'Locked'];
    const body = rows().map((r) => [
      r.stocktakeNumber,
      r.status,
      r.description ?? '',
      r.comment ?? '',
      formatDate(r.createdDatetime),
      formatDate(r.finalisedDatetime),
      r.isLocked ? 'Yes' : 'No',
    ]);
    downloadCsv('stocktakes.csv', toCsv(headers, body));
  };

  const columns: Column<StocktakeListItem>[] = [
    {
      key: 'stocktakeNumber',
      header: 'Number',
      sortable: true,
      align: 'right',
      width: '90px',
      render: (r) => (
        <span class="tabular st-number">
          #{r.stocktakeNumber}
          <Show when={r.isLocked}>
            <span class="st-held" title="On hold (locked)">held</span>
          </Show>
        </span>
      ),
      cardHidden: true,
    },
    {
      key: 'status',
      header: 'Status',
      sortable: true,
      render: (r) => <StatusBadge label={r.status === 'NEW' ? 'New' : 'Finalised'} tone={r.status === 'NEW' ? 'info' : 'success'} />,
      cardHidden: true,
    },
    { key: 'description', header: 'Description', sortable: true, render: (r) => <span class="cell-truncate">{r.description || '—'}</span> },
    { key: 'comment', header: 'Comment', priority: 3, render: (r) => <span class="cell-truncate">{r.comment || '—'}</span> },
    { key: 'createdDatetime', header: 'Created', sortable: true, priority: 2, width: '120px', render: (r) => formatDate(r.createdDatetime) },
    { key: 'finalisedDatetime', header: 'Finalised', sortable: true, priority: 2, width: '120px', render: (r) => formatDate(r.finalisedDatetime) || '—' },
  ];

  const selection = {
    isSelected: (id: string) => selected().has(id),
    onToggle: toggle,
    onToggleAll: toggleAll,
    get allSelected() {
      return rows().length > 0 && selected().size === rows().length;
    },
    get someSelected() {
      return selected().size > 0;
    },
  };

  return (
    <div class="page">
      <div class="page-toolbar">
        <FilterBar
          defs={[
            {
              key: 'status',
              label: 'Status',
              type: 'enum',
              options: [
                { value: 'NEW', label: 'New' },
                { value: 'FINALISED', label: 'Finalised' },
              ],
            },
          ]}
          values={{ status: status() }}
          onChange={(_k, v) => setListState({ status: v, page: undefined })}
        >
          <Show when={selected().size > 0}>
            <Button
              label={`Delete (${selected().size})`}
              variant="destructive"
              icon="delete"
              compact
              onClick={() => setConfirmDelete(true)}
            />
          </Show>
          <Button label="Export" icon="download" variant="secondary" compact onClick={exportCsv} />
          <Button label="New stocktake" icon="plus-circle" variant="primary" compact onClick={() => setCreateOpen(true)} />
        </FilterBar>
      </div>

      <div class="page-body">
        <Table
          caption="Stocktakes"
          columns={columns}
          rows={rows()}
          rowKey={(r) => r.id}
          selection={selection}
          sort={sort()}
          onSort={onSort}
          state={tableState()}
          errorMessage={data.error ? (data.error as Error).message : undefined}
          onRetry={() => setRefreshKey((k) => k + 1)}
          onClearFilters={() => setListState({ status: undefined, page: undefined })}
          onRowClick={(r) => navigate(`/${params.storeId}/inventory/stocktakes/${r.stocktakeNumber}`)}
          cardTitle={(r) => <>#{r.stocktakeNumber} {r.description || ''}</>}
          cardStatus={(r) => <StatusBadge label={r.status === 'NEW' ? 'New' : 'Finalised'} tone={r.status === 'NEW' ? 'info' : 'success'} />}
        />
      </div>

      <div class="page-footer">
        <span class="page-count tabular">
          {totalCount()} stocktake{totalCount() === 1 ? '' : 's'}
        </span>
        <Show when={totalPages() > 1}>
          <div class="pagination">
            <Button
              icon="arrow-left"
              aria-label="Previous page"
              variant="ghost"
              compact
              disabled={page() <= 1}
              onClick={() => setListState({ page: String(page() - 1) })}
            />
            <span class="tabular">
              {page()} / {totalPages()}
            </span>
            <Button
              icon="arrow-right"
              aria-label="Next page"
              variant="ghost"
              compact
              disabled={page() >= totalPages()}
              onClick={() => setListState({ page: String(page() + 1) })}
            />
          </div>
        </Show>
      </div>

      <CreateStocktakeModal
        open={createOpen()}
        storeId={params.storeId!}
        onClose={() => setCreateOpen(false)}
        onCreated={(number) => {
          setCreateOpen(false);
          navigate(`/${params.storeId}/inventory/stocktakes/${number}`);
        }}
      />

      <ConfirmDialog
        open={confirmDelete()}
        title="Delete stocktakes?"
        message={`Permanently delete ${selected().size} selected stocktake(s)?`}
        destructive
        confirmLabel="Delete"
        busy={deleting()}
        onConfirm={doDelete}
        onCancel={() => setConfirmDelete(false)}
      />
    </div>
  );
}

// react/src/features/stocktakes/StocktakeListPage.tsx
import { useMemo, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { PageLayout } from '@/app/layout/PageLayout';
import { DataTable, type Column, type SortState } from '@/components/DataTable';
import { Button } from '@/components/Button';
import { FilterBar, type FilterDef } from '@/components/FilterBar';
import { StatusBadge } from '@/components/StatusBadge';
import { ConfirmDialog } from '@/components/ConfirmDialog';
import { Icon } from '@/icons/Icon';
import { useToast } from '@/components/Toast';
import { useStoreId } from '@/app/auth/AuthContext';
import { useTranslation } from '@/app/i18n/i18n';
import { formatDate } from '@/lib/format';
import { deleteStocktakes, fetchStocktakes } from './api';
import { CreateStocktakeDialog } from './CreateStocktakeDialog';
import { toCsv, downloadCsv } from './csv';
import type { Stocktake, StocktakeSortField, StocktakeStatus } from './types';
import './StocktakeListPage.css';

const PAGE_SIZE = 25;

const STATUS_FILTER: FilterDef = {
  key: 'status',
  label: 'Status',
  type: 'enum',
  options: [
    { value: 'NEW', label: 'New' },
    { value: 'FINALISED', label: 'Finalised' },
  ],
};

export function StocktakeListPage() {
  const storeId = useStoreId();
  const navigate = useNavigate();
  const toast = useToast();
  const qc = useQueryClient();
  const t = useTranslation();
  const [params, setParams] = useSearchParams();

  const [createOpen, setCreateOpen] = useState(false);
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [confirmDelete, setConfirmDelete] = useState(false);

  // ---- URL-bound state (shareable, survives reload) ----
  const status = (params.get('status') as StocktakeStatus | null) ?? null;
  const sortField = (params.get('sort') as StocktakeSortField) ?? 'createdDatetime';
  const sortDesc = params.get('dir') !== 'asc';
  const page = Math.max(0, Number(params.get('page') ?? '0'));

  const setParam = (key: string, value: string | null) => {
    const next = new URLSearchParams(params);
    if (value == null || value === '') next.delete(key);
    else next.set(key, value);
    if (key !== 'page') next.delete('page'); // changing filter/sort resets paging
    setParams(next, { replace: true });
  };

  const listQuery = useQuery({
    queryKey: ['stocktakes', storeId, status, sortField, sortDesc, page],
    queryFn: ({ signal }) =>
      fetchStocktakes(
        storeId!,
        { status, page, pageSize: PAGE_SIZE, sortField, sortDesc },
        signal,
      ),
    enabled: !!storeId,
    placeholderData: (prev) => prev, // keep rows visible during refetch
  });

  const rows = listQuery.data?.nodes ?? [];
  const totalCount = listQuery.data?.totalCount ?? 0;
  const pageCount = Math.max(1, Math.ceil(totalCount / PAGE_SIZE));

  const del = useMutation({
    mutationFn: (ids: string[]) => deleteStocktakes(storeId!, ids),
    onSuccess: (results) => {
      const ok = results.filter((r) => r.ok).length;
      const failed = results.filter((r) => !r.ok);
      if (ok) toast.success(`Deleted ${ok} stocktake${ok === 1 ? '' : 's'}`);
      if (failed.length) toast.error(`${failed.length} could not be deleted`);
      setSelected(new Set());
      setConfirmDelete(false);
      qc.invalidateQueries({ queryKey: ['stocktakes'] });
    },
    onError: (e) => {
      toast.error((e as Error).message);
      setConfirmDelete(false);
    },
  });

  const columns = useMemo<Column<Stocktake>[]>(
    () => [
      {
        key: 'stocktakeNumber',
        header: '#',
        priority: 1,
        sortable: true,
        align: 'right',
        width: 80,
        render: (r) => r.stocktakeNumber,
      },
      {
        key: 'status',
        header: 'Status',
        priority: 1,
        sortable: true,
        width: 120,
        render: (r) => (
          <StatusBadge
            label={r.status === 'NEW' ? 'New' : 'Finalised'}
            tone={r.status === 'NEW' ? 'info' : 'success'}
          />
        ),
      },
      {
        key: 'description',
        header: 'Description',
        priority: 2,
        sortable: true,
        render: (r) => r.description || <span className="oms-muted">—</span>,
      },
      {
        key: 'comment',
        header: 'Comment',
        priority: 3,
        render: (r) =>
          r.comment ? (
            <span className="oms-truncate" title={r.comment}>
              {r.comment}
            </span>
          ) : (
            <span className="oms-muted">—</span>
          ),
      },
      {
        key: 'createdDatetime',
        header: 'Created',
        priority: 2,
        sortable: true,
        width: 120,
        render: (r) => formatDate(r.createdDatetime),
      },
      {
        key: 'finalisedDatetime',
        header: 'Finalised',
        priority: 3,
        sortable: true,
        width: 120,
        render: (r) =>
          r.finalisedDatetime ? formatDate(r.finalisedDatetime) : <span className="oms-muted">—</span>,
      },
      {
        key: 'isLocked',
        header: 'Locked',
        priority: 2,
        align: 'center',
        width: 80,
        render: (r) =>
          r.isLocked ? (
            <Icon name="eye-off" size={18} title="Locked" />
          ) : (
            <span className="oms-muted">—</span>
          ),
      },
    ],
    [],
  );

  const sort: SortState = { key: sortField, desc: sortDesc };
  const onSortChange = (s: SortState) => {
    const next = new URLSearchParams(params);
    next.set('sort', s.key);
    next.set('dir', s.desc ? 'desc' : 'asc');
    next.delete('page');
    setParams(next, { replace: true });
  };

  const [exporting, setExporting] = useState(false);
  const exportCsv = async () => {
    if (!storeId) return;
    setExporting(true);
    try {
      // Export the whole filtered list, not just the current page.
      const all = await fetchStocktakes(storeId, {
        status,
        page: 0,
        pageSize: Math.max(totalCount, PAGE_SIZE),
        sortField,
        sortDesc,
      });
      const csv = toCsv(
        ['Number', 'Status', 'Description', 'Comment', 'Created', 'Finalised', 'Locked'],
        all.nodes.map((r) => [
          r.stocktakeNumber,
          r.status === 'NEW' ? 'New' : 'Finalised',
          r.description ?? '',
          r.comment ?? '',
          formatDate(r.createdDatetime),
          r.finalisedDatetime ? formatDate(r.finalisedDatetime) : '',
          r.isLocked ? 'Yes' : 'No',
        ]),
      );
      downloadCsv('stocktakes.csv', csv);
      toast.success(`Exported ${all.nodes.length} stocktakes to CSV`);
    } catch (e) {
      toast.error(`Export failed: ${(e as Error).message}`);
    } finally {
      setExporting(false);
    }
  };

  const appBar = (
    <div className="oms-listbar">
      <h1 className="oms-listbar__title">{t('stocktakes.title')}</h1>
      <div className="oms-listbar__filters">
        <FilterBar
          filters={[STATUS_FILTER]}
          values={{ status }}
          onChange={(k, v) => setParam(k, v)}
          onRemoveAll={() => setParam('status', null)}
        />
      </div>
      <div className="oms-listbar__actions">
        <Button
          variant="secondary"
          size="compact"
          icon="download"
          onClick={exportCsv}
          busy={exporting}
        >
          Export
        </Button>
        <Button variant="primary" size="compact" icon="plus-circle" onClick={() => setCreateOpen(true)}>
          {t('action.newStocktake')}
        </Button>
      </div>
    </div>
  );

  const selectionFooter =
    selected.size > 0 ? (
      <div className="oms-selection-bar">
        <Button
          variant="ghost"
          size="compact"
          icon="minus-circle"
          onClick={() => setSelected(new Set())}
        >
          Clear
        </Button>
        <span className="oms-selection-bar__count">{selected.size} selected</span>
        <div style={{ flex: 1 }} />
        <Button
          variant="destructive"
          size="compact"
          icon="delete"
          onClick={() => setConfirmDelete(true)}
        >
          Delete
        </Button>
      </div>
    ) : undefined;

  return (
    <PageLayout appBar={appBar} footer={selectionFooter}>
      <DataTable
        caption="Stocktakes"
        columns={columns}
        rows={rows}
        rowKey={(r) => r.id}
        selectable
        selectedIds={selected}
        onSelectionChange={setSelected}
        sort={sort}
        onSortChange={onSortChange}
        onRowClick={(r) => navigate(`/inventory/stocktakes/${r.stocktakeNumber}`)}
        loading={listQuery.isLoading || listQuery.isFetching}
        error={listQuery.isError ? (listQuery.error as Error).message : undefined}
        onRetry={() => listQuery.refetch()}
        isFiltered={!!status}
        onClearFilters={() => setParam('status', null)}
        emptyMessage="No stocktakes yet — create one to get started"
        emptyFilteredMessage="No stocktakes match the current filter"
      />

      {totalCount > PAGE_SIZE && (
        <div className="oms-pager">
          <Button
            variant="secondary"
            size="compact"
            icon="arrow-left"
            disabled={page === 0}
            onClick={() => setParam('page', String(page - 1))}
          >
            Previous
          </Button>
          <span className="oms-pager__info tabular">
            Page {page + 1} of {pageCount} · {totalCount} total
          </span>
          <Button
            variant="secondary"
            size="compact"
            icon="arrow-right"
            iconTrailing
            disabled={page + 1 >= pageCount}
            onClick={() => setParam('page', String(page + 1))}
          >
            Next
          </Button>
        </div>
      )}

      <CreateStocktakeDialog
        storeId={storeId!}
        open={createOpen}
        onClose={() => setCreateOpen(false)}
        onCreated={(result) => {
          setCreateOpen(false);
          toast.success(`Created stocktake #${result.stocktakeNumber}`);
          qc.invalidateQueries({ queryKey: ['stocktakes'] });
          navigate(`/inventory/stocktakes/${result.stocktakeNumber}`);
        }}
      />

      <ConfirmDialog
        open={confirmDelete}
        onClose={() => setConfirmDelete(false)}
        onConfirm={() => del.mutate([...selected])}
        title={`Delete ${selected.size} stocktake${selected.size === 1 ? '' : 's'}?`}
        message="This cannot be undone."
        confirmLabel="Delete"
        destructive
        busy={del.isPending}
      />
    </PageLayout>
  );
}
