// solid/src/chrome/MobileNav.tsx
/**
 * Mobile / tablet nav (spec/chrome/01-behaviours.md › Mobile / tablet nav). A top bar with a
 * menu toggle (open/close glyph from the custom set — divergence D4: `menu-dots` ↔ `close`),
 * the current section as breadcrumb, and the brand mark. The menu opens a slide-down drawer
 * with the nav links plus Docs (external), Sync, Settings (permission-gated), and Logout.
 */
import { type JSX, For, Show, createMemo, createSignal } from 'solid-js';
import { A, useLocation, useNavigate } from '@solidjs/router';
import { Icon } from '../ui/Icon';
import { ConfirmDialog } from '../ui/Modal';
import { auth } from '../state/auth';
import { navGroups, activeNavItem, isActive } from './nav-config';

export function MobileNav(): JSX.Element {
  const [open, setOpen] = createSignal(false);
  const [confirm, setConfirm] = createSignal(false);
  const location = useLocation();
  const navigate = useNavigate();
  const section = createMemo(() => activeNavItem(location.pathname));
  const items = createMemo(() => navGroups.flatMap((g) => g.items).filter((i) => i.visible?.() ?? true));

  const doLogout = () => {
    setConfirm(false);
    setOpen(false);
    auth.logout();
    navigate('/login');
  };

  return (
    <>
      <div class="mobile-bar">
        <button
          class="icon-btn icon-btn--plain"
          type="button"
          aria-label={open() ? 'Close menu' : 'Open menu'}
          aria-expanded={open()}
          onClick={() => setOpen(!open())}
        >
          <Icon name={open() ? 'close' : 'menu-dots'} size={22} />
        </button>
        <span style={{ 'font-weight': 600 }}>{section()?.label ?? 'open mSupply'}</span>
        <span class="mobile-bar__brand">
          <Icon name="m-supply-guy" size={26} />
        </span>
      </div>

      <Show when={open()}>
        <div class="mobile-drawer">
          <div class="mobile-drawer__scrim" onClick={() => setOpen(false)} />
          <nav class="mobile-drawer__panel" aria-label="Primary">
            <ul class="menu" style={{ 'max-height': 'none' }}>
              <For each={items()}>
                {(item) => (
                  <li role="none">
                    <A
                      href={item.route}
                      class={`menu-item${isActive(item.route, location.pathname) ? ' menu-item--selected' : ''}`}
                      onClick={() => setOpen(false)}
                    >
                      <Icon name={item.icon} size={20} />
                      <span class="menu-item__label">{item.label}</span>
                    </A>
                  </li>
                )}
              </For>
              <li role="none">
                <a class="menu-item" href="https://docs.msupply.foundation" target="_blank" rel="noreferrer">
                  <Icon name="book" size={20} />
                  <span class="menu-item__label">Docs</span>
                  <Icon name="external-link" size={14} />
                </a>
              </li>
              <li role="none">
                <A href="/sync" class="menu-item" onClick={() => setOpen(false)}>
                  <Icon name="radio" size={20} />
                  <span class="menu-item__label">Sync</span>
                </A>
              </li>
              <Show when={auth.can('ServerAdmin') || auth.can('EditStore')}>
                <li role="none">
                  <A href="/settings" class="menu-item" onClick={() => setOpen(false)}>
                    <Icon name="settings" size={20} />
                    <span class="menu-item__label">Settings</span>
                  </A>
                </li>
              </Show>
              <li role="none">
                <button type="button" class="menu-item" onClick={() => setConfirm(true)}>
                  <Icon name="power" size={20} />
                  <span class="menu-item__label">Logout</span>
                </button>
              </li>
            </ul>
          </nav>
        </div>
      </Show>

      <ConfirmDialog
        open={confirm()}
        title="Log out?"
        message="You will be returned to the login screen."
        confirmLabel="Log out"
        onConfirm={doLogout}
        onCancel={() => setConfirm(false)}
      />
    </>
  );
}

// svelte/src/chrome/MobileNav.svelte
<script lang="ts">
  // Mobile / tablet slide-down nav drawer (spec chrome/01-behaviours.md › mobile nav).
  // Nav links + Docs (external), Sync, Settings (gated), Logout. Uses the custom icon
  // set for the toggle (divergence D4) — the toggle itself lives in TopBar.
  import Icon from '../lib/components/Icon.svelte';
  import ConfirmDialog from '../lib/components/ConfirmDialog.svelte';
  import { portal } from '../lib/util/portal';
  import { chrome } from '../lib/state/chrome.svelte';
  import { auth } from '../lib/state/auth.svelte';
  import { router } from '../lib/router.svelte';
  import { ALL_NAV, itemPath } from '../lib/nav';

  let storeId = $derived(auth.activeStoreId ?? '');
  let logoutConfirm = $state(false);
</script>

{#if chrome.mobileNavOpen}
  <div class="drawer-wrap" use:portal>
    <button class="scrim" aria-label="Close menu" onclick={() => chrome.closeMobileNav()}></button>
    <nav class="drawer" aria-label="Primary">
      <ul>
        {#each ALL_NAV as item (item.key)}
          <li>
            <a class="row" href={itemPath(storeId, item)} onclick={() => chrome.closeMobileNav()}>
              <Icon name={item.icon} size={24} /> {item.label}
            </a>
          </li>
        {/each}
        <li class="sep"></li>
        <li>
          <a class="row" href="https://docs.msupply.foundation" target="_blank" rel="noopener">
            <Icon name="book" size={24} /> Docs
          </a>
        </li>
        <li>
          <button class="row" onclick={() => { chrome.closeMobileNav(); logoutConfirm = true; }}>
            <Icon name="power" size={24} /> Logout
          </button>
        </li>
      </ul>
    </nav>
  </div>
{/if}

<ConfirmDialog
  open={logoutConfirm}
  title="Log out?"
  message="You will be returned to the login screen."
  confirmLabel="Log out"
  onconfirm={() => { logoutConfirm = false; auth.logout(); router.navigate('/login'); }}
  oncancel={() => (logoutConfirm = false)}
/>

<style>
  .drawer-wrap {
    position: fixed;
    inset: 0;
    z-index: var(--z-modal);
  }
  .scrim {
    position: absolute;
    inset: 0;
    border: 0;
    background: var(--surface-scrim);
  }
  .drawer {
    position: absolute;
    top: 56px;
    left: 0;
    right: 0;
    max-height: calc(100% - 56px);
    overflow-y: auto;
    background: var(--surface-nav);
    box-shadow: var(--elev-overlay);
    animation: slide 0.2s ease;
  }
  @keyframes slide {
    from {
      transform: translateY(-8px);
      opacity: 0.6;
    }
  }
  ul {
    list-style: none;
    margin: 0;
    padding: var(--sp-2);
  }
  .sep {
    height: 1px;
    background: var(--divider);
    margin: var(--sp-2) 0;
  }
  .row {
    display: flex;
    align-items: center;
    gap: var(--sp-3);
    width: 100%;
    padding: var(--sp-3);
    border: 0;
    background: transparent;
    color: var(--text-primary);
    font: inherit;
    text-align: start;
    cursor: pointer;
    border-radius: var(--radius-control);
    min-height: 48px;
  }
  .row:hover {
    background: var(--hover-overlay);
  }
</style>
