// solid/src/chrome/TopBar.tsx
import { For, Show, type JSX, createMemo } from 'solid-js';
import { useLocation } from '@solidjs/router';
import { Icon } from '../ui/Icon';
import { sectionForArea } from './nav-config';
import { fullScreen, toggleFullScreen } from '../state/chrome';

/*
 * Desktop top bar (chrome/01-behaviours.md#desktop-top-bar): the active section's
 * icon followed by the breadcrumb trail for the current route, plus a full-screen
 * toggle (exit uses the minimise icon).
 */

function prettify(seg: string): string {
  return seg.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

export function TopBar(): JSX.Element {
  const location = useLocation();

  const crumbs = createMemo(() => {
    const segments = location.pathname.split('/').filter(Boolean);
    // segments[0] = storeId; the rest are area / vertical / record.
    const rest = segments.slice(1);
    const section = sectionForArea(rest[0]);
    const labels: string[] = [];
    if (section) labels.push(section.label);
    for (let i = 1; i < rest.length; i++) {
      const seg = rest[i]!;
      // A stocktake record is its human number.
      labels.push(rest[i - 1] === 'stocktakes' && /^\d+$/.test(seg) ? `#${seg}` : prettify(seg));
    }
    return { icon: section?.icon ?? 'dashboard', labels };
  });

  return (
    <div class="topbar">
      <div class="topbar-crumbs">
        <Icon name={crumbs().icon} size={20} />
        <For each={crumbs().labels}>
          {(label, i) => (
            <>
              <Show when={i() > 0}>
                <Icon name="chevron-down" size={14} class="crumb-sep topbar-crumb-sep" />
              </Show>
              <span class="topbar-crumb">{label}</span>
            </>
          )}
        </For>
      </div>
      <div class="topbar-actions">
        <button
          type="button"
          class="btn btn-ghost btn-icon-only btn-compact"
          aria-label={fullScreen() ? 'Exit full screen' : 'Full screen'}
          title={fullScreen() ? 'Exit full screen' : 'Full screen'}
          onClick={() => toggleFullScreen()}
        >
          <Icon name={fullScreen() ? 'minimise' : 'maximise'} size={20} />
        </button>
      </div>
    </div>
  );
}

// svelte/src/chrome/TopBar.svelte
<script lang="ts">
  // Desktop top bar (spec chrome/01-behaviours.md › desktop top bar): active section
  // icon + breadcrumbs, and a full-screen toggle. On compact viewports it becomes the
  // mobile bar with a menu toggle + brand mark.
  import Icon from '../lib/components/Icon.svelte';
  import { router } from '../lib/router.svelte';
  import { chrome } from '../lib/state/chrome.svelte';
  import { viewport } from '../lib/state/viewport.svelte';
  import { auth } from '../lib/state/auth.svelte';
  import { ALL_NAV } from '../lib/nav';

  let seg = $derived(router.segments);
  let section = $derived(ALL_NAV.find((n) => n.area === seg[1]));

  // Breadcrumb trail from the path (store segment excluded).
  let crumbs = $derived.by(() => {
    const out: string[] = [];
    if (section) out.push(section.label);
    if (seg[2]) out.push(titleCase(seg[2]));
    if (seg[3]) out.push(seg[3] === 'new' ? 'New' : `#${seg[3]}`);
    return out;
  });

  function titleCase(s: string): string {
    return s.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
  }
</script>

<header class="topbar">
  {#if viewport.isCompact}
    <button class="menu-toggle" aria-label="Menu" aria-expanded={chrome.mobileNavOpen} onclick={() => chrome.toggleMobileNav()}>
      <Icon name={chrome.mobileNavOpen ? 'close' : 'menu-dots'} size={24} />
    </button>
  {/if}

  <div class="crumbs">
    {#if section}<Icon name={section.icon} size={20} />{/if}
    {#each crumbs as c, i (i)}
      {#if i > 0}<span class="sep">/</span>{/if}
      <span class="crumb" class:last={i === crumbs.length - 1}>{c}</span>
    {/each}
  </div>

  <div class="spacer"></div>

  {#if viewport.isCompact}
    <span class="mini-brand"><Icon name="m-supply-guy" size={28} /></span>
  {:else}
    <button
      class="fs-toggle"
      aria-label={chrome.fullscreen ? 'Exit full screen' : 'Full screen'}
      onclick={() => chrome.toggleFullscreen()}
    >
      <Icon name={chrome.fullscreen ? 'minimise' : 'maximise'} size={20} />
    </button>
  {/if}
</header>

<style>
  .topbar {
    display: flex;
    align-items: center;
    gap: var(--sp-3);
    height: 56px;
    padding: 0 var(--sp-4);
    background: var(--surface-base);
    border-bottom: 1px solid var(--divider);
    flex: none;
  }
  .crumbs {
    display: flex;
    align-items: center;
    gap: var(--sp-2);
    color: var(--text-secondary);
  }
  .crumb.last {
    color: var(--text-primary);
    font-weight: var(--type-emphasis-weight);
  }
  .sep {
    color: var(--text-disabled);
  }
  .spacer {
    flex: 1;
  }
  .menu-toggle,
  .fs-toggle {
    display: inline-flex;
    border: 0;
    background: transparent;
    color: var(--text-secondary);
    cursor: pointer;
    padding: var(--sp-2);
    border-radius: var(--radius-control);
  }
  .menu-toggle:hover,
  .fs-toggle:hover {
    background: var(--hover-overlay);
  }
  .mini-brand {
    display: inline-flex;
  }
</style>
