// react/src/main.tsx
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { RouterProvider } from 'react-router-dom';
import { QueryClientProvider } from '@tanstack/react-query';

import '@/theme/theme.css';
import '@/styles/global.css';
import '@/icons/icon.css';

import { queryClient } from '@/lib/queryClient';
import { ThemeProvider } from '@/theme/ThemeProvider';
import { I18nProvider, applyDocumentLanguage } from '@/app/i18n/i18n';
import { AuthProvider } from '@/app/auth/AuthContext';
import { ToastProvider } from '@/components/Toast';
import { router } from '@/routes';

// Apply <html lang/dir> from the persisted language before first paint.
applyDocumentLanguage();

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <ThemeProvider>
        <I18nProvider>
          <ToastProvider>
            <AuthProvider>
              <RouterProvider router={router} />
            </AuthProvider>
          </ToastProvider>
        </I18nProvider>
      </ThemeProvider>
    </QueryClientProvider>
  </StrictMode>,
);

// solid/src/index.tsx
/* @refresh reload */
import { render } from 'solid-js/web';
import { QueryClient, QueryClientProvider } from '@tanstack/solid-query';
import { ThemeProvider } from './theme/ThemeProvider';
import { StoreProvider } from './context/StoreContext';
import { ToastProvider } from './components/ui/Toast';
import { App } from './App';
import './main.css';
import './components/ui/ui.css';

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: 30_000,
      refetchOnWindowFocus: false,
      retry: 1,
    },
  },
});

const root = document.getElementById('root');
if (!root) throw new Error('#root not found');

render(
  () => (
    <QueryClientProvider client={queryClient}>
      <ThemeProvider>
        <StoreProvider>
          <ToastProvider>
            <App />
          </ToastProvider>
        </StoreProvider>
      </ThemeProvider>
    </QueryClientProvider>
  ),
  root,
);
