// svelte/src/lib/stocktakes/StocktakeLineEditor.svelte
<script lang="ts">
	/**
	 * Line editor (spec S4 / J3) — the SINGLE surface for entering stocktake-line data.
	 * The S3 detail table is read-only; all editing happens here. Two modes:
	 *   - **create** (`editItem` null): search the catalogue for an item not yet on the
	 *     stocktake, then enter one or more new batches (inserts);
	 *   - **edit** (`editItem` set): item is locked; its existing batches load as rows
	 *     (updates), and further new batches can be added (inserts).
	 *
	 * Each batch row captures counted packs, batch, expiry, pack size, location and — when
	 * the count produces an adjustment — a direction-gated reason (03 › Adjustment-reason
	 * rules). Reason/count validation is enforced here so there is a single validation path.
	 *
	 * Scope note (staged): batch/expiry/pack-size are editable for NEW batches; for existing
	 * batches they identify the row and are shown read-only (the update API takes expiry as a
	 * nullable wrapper — see api.ts). Prices, donor, item variant, VVM status, note and
	 * next/previous-item navigation are noted follow-ups.
	 */
	import Modal from '$lib/ui/Modal.svelte';
	import Button from '$lib/ui/Button.svelte';
	import Icon from '$lib/icons/Icon.svelte';
	import NumericField from '$lib/ui/inputs/NumericField.svelte';
	import TextField from '$lib/ui/inputs/TextField.svelte';
	import DateField from '$lib/ui/inputs/DateField.svelte';
	import SelectField from '$lib/ui/inputs/SelectField.svelte';
	import { searchItems, type ItemSearchResult, type Ref } from './reference';
	import { batchStocktakeLines, type UpsertLineInput } from './api';
	import { adjustmentDirection, reasonTypeMatchesDirection } from './rules';
	import type { ReasonOption, StocktakeLine } from './types';
	import { formatDate, formatNumber } from '$lib/format';

	/** Minimal item shape shared by catalogue results and existing-line items. */
	interface EditItem {
		id: string;
		code: string;
		name: string;
		unitName?: string | null;
		defaultPackSize?: number;
	}

	let {
		open = $bindable(false),
		storeId,
		stocktakeId,
		existingItemIds = new Set<string>(),
		locations = [],
		reasons = [],
		editItem = null,
		onSaved
	}: {
		open?: boolean;
		storeId: string;
		stocktakeId: string;
		existingItemIds?: Set<string>;
		locations?: Ref[];
		reasons?: ReasonOption[];
		/** When set, opens in edit mode for this item's existing batches. */
		editItem?: { item: EditItem; lines: StocktakeLine[] } | null;
		onSaved?: () => void;
	} = $props();

	interface BatchRow {
		key: number;
		/** Existing line id ⇒ update; absent ⇒ insert. */
		id?: string;
		snapshot: number;
		counted: number | null;
		batch: string;
		expiry: string | null;
		packSize: number | null;
		locationId: string | null;
		reasonId: string | null;
	}

	let term = $state('');
	let results = $state<ItemSearchResult[]>([]);
	let searching = $state(false);
	let item = $state<EditItem | null>(null);
	let rows = $state<BatchRow[]>([]);
	let saving = $state(false);
	let error = $state<string | null>(null);
	let nextKey = 0;

	const isEdit = $derived(!!editItem);

	// Reset each time the modal opens; edit mode seeds the item + its existing batches.
	$effect(() => {
		if (!open) return;
		error = null;
		term = '';
		results = [];
		if (editItem) {
			item = { ...editItem.item };
			rows = editItem.lines.map(toRow);
		} else {
			item = null;
			rows = [];
		}
	});

	function toRow(l: StocktakeLine): BatchRow {
		return {
			key: nextKey++,
			id: l.id,
			snapshot: l.snapshotNumberOfPacks,
			counted: l.countedNumberOfPacks ?? null,
			batch: l.batch ?? '',
			expiry: l.expiryDate ?? null,
			packSize: l.packSize,
			locationId: l.location?.id ?? null,
			reasonId: l.reasonOption?.id ?? null
		};
	}

	function newRow(): BatchRow {
		return {
			key: nextKey++,
			snapshot: 0,
			counted: null,
			batch: '',
			expiry: null,
			packSize: item?.defaultPackSize ?? 1,
			locationId: null,
			reasonId: null
		};
	}

	// Debounced catalogue search while no item is chosen (create mode only).
	$effect(() => {
		if (!open || item) return;
		const q = term;
		const store = storeId;
		searching = true;
		const t = setTimeout(() => {
			searchItems(store, q)
				.then((r) => (results = r.filter((i) => !existingItemIds.has(i.id))))
				.catch(() => (results = []))
				.finally(() => (searching = false));
		}, 250);
		return () => clearTimeout(t);
	});

	function chooseItem(i: ItemSearchResult) {
		item = { id: i.id, code: i.code, name: i.name, unitName: i.unitName, defaultPackSize: i.defaultPackSize };
		rows = [newRow()];
	}

	function addRow() {
		rows = [...rows, newRow()];
	}
	function removeRow(key: number) {
		rows = rows.filter((r) => r.key !== key);
	}

	// ── Reason gating (mirrors rules.ts, per-row) ──────────────────────────────
	function directionOf(r: BatchRow) {
		return adjustmentDirection({ countedNumberOfPacks: r.counted, snapshotNumberOfPacks: r.snapshot });
	}
	function reasonsFor(r: BatchRow) {
		const dir = directionOf(r);
		return reasons
			.filter((o) => o.isActive && reasonTypeMatchesDirection(o.type, dir))
			.map((o) => ({ value: o.id, label: o.reason }));
	}
	function needsReason(r: BatchRow): boolean {
		return directionOf(r) !== 'none' && reasonsFor(r).length > 0;
	}
	/** Per-row reason problem, or null. Only counted rows are validated. */
	function rowReasonError(r: BatchRow): 'required' | 'invalid' | null {
		if (r.counted == null) return null;
		const dir = directionOf(r);
		if (dir === 'none') return null;
		if (r.reasonId) {
			const opt = reasons.find((o) => o.id === r.reasonId);
			return opt && reasonTypeMatchesDirection(opt.type, dir) ? null : 'invalid';
		}
		return needsReason(r) ? 'required' : null;
	}
	/** When a count change flips the direction, drop a now-invalid reason. */
	function reconcileReason(r: BatchRow) {
		if (r.reasonId && !reasonsFor(r).some((o) => o.value === r.reasonId)) r.reasonId = null;
	}

	const anyReasonError = $derived(rows.some((r) => rowReasonError(r) !== null));
	const anyCounted = $derived(rows.some((r) => r.counted != null));
	const canSave = $derived(!!item && rows.length > 0 && anyCounted && !anyReasonError && !saving);

	async function save() {
		if (!item) return;
		saving = true;
		error = null;
		try {
			const upserts: UpsertLineInput[] = [];
			for (const r of rows) {
				const isNew = !r.id;
				// Skip empty new rows (nothing entered).
				if (isNew && r.counted == null && !r.batch.trim()) continue;
				if (isNew) {
					upserts.push({
						stocktakeId,
						itemId: item.id,
						countedNumberOfPacks: r.counted,
						batch: r.batch.trim() || undefined,
						expiryDate: r.expiry ?? undefined,
						packSize: r.packSize ?? undefined,
						location: r.locationId ? { value: r.locationId } : undefined,
						reasonOptionId: r.reasonId ?? undefined
					});
				} else {
					upserts.push({
						id: r.id,
						stocktakeId,
						countedNumberOfPacks: r.counted,
						location: r.locationId ? { value: r.locationId } : { value: null },
						reasonOptionId: r.reasonId ?? undefined
					});
				}
			}
			if (upserts.length) await batchStocktakeLines(storeId, { upserts });
			open = false;
			onSaved?.();
		} catch (e) {
			error = e instanceof Error ? e.message : String(e);
		} finally {
			saving = false;
		}
	}

	const locationOptions = $derived(
		locations.map((l) => ({ value: l.id, label: l.name || l.code || l.id }))
	);
	const title = $derived(isEdit ? 'Edit item lines' : 'Add item');
</script>

<Modal bind:open {title} width="860px">
	{#if !item}
		<TextField
			label="Search catalogue"
			bind:value={term}
			width="full"
			placeholder="Item code or name"
		/>
		<div class="results" role="listbox" aria-label="Search results">
			{#if searching && results.length === 0}
				<p class="hint">Searching…</p>
			{:else if results.length === 0}
				<p class="hint">{term.trim() ? 'No matching items.' : 'Type to search the catalogue.'}</p>
			{:else}
				{#each results as i (i.id)}
					<button type="button" class="result" role="option" aria-selected="false" onclick={() => chooseItem(i)}>
						<span class="code">{i.code}</span>
						<span class="name">{i.name}</span>
						{#if i.unitName}<span class="unit">{i.unitName}</span>{/if}
					</button>
				{/each}
			{/if}
		</div>
	{:else}
		<div class="chosen">
			<div>
				<span class="code">{item.code}</span>
				<strong>{item.name}</strong>
				{#if item.unitName}<span class="unit">· {item.unitName}</span>{/if}
			</div>
			{#if !isEdit}
				<Button variant="ghost" compact onclick={() => (item = null)}>
					<Icon name="edit" size={16} /> Change item
				</Button>
			{/if}
		</div>

		<div class="grid" role="table" aria-label="Batches">
			<div class="row head" role="row">
				<span role="columnheader">Counted packs</span>
				<span role="columnheader">Batch</span>
				<span role="columnheader">Expiry</span>
				<span role="columnheader">Pack size</span>
				<span role="columnheader">Location</span>
				<span role="columnheader">Reason</span>
				<span role="columnheader" class="sr">Remove</span>
			</div>
			{#each rows as r (r.key)}
				{@const rerr = rowReasonError(r)}
				<div class="row" role="row">
					<NumericField
						label="Counted packs"
						hideLabel
						bind:value={r.counted}
						min={0}
						width="qty"
						onchange={() => reconcileReason(r)}
					/>

					{#if r.id}
						<span class="ro" title={r.batch || '—'}>{r.batch || '—'}</span>
						<span class="ro">{formatDate(r.expiry) || '—'}</span>
						<span class="ro num">{formatNumber(r.packSize)}</span>
					{:else}
						<TextField label="Batch" hideLabel bind:value={r.batch} width="120px" placeholder="—" />
						<DateField label="Expiry" hideLabel bind:value={r.expiry} />
						<NumericField label="Pack size" hideLabel bind:value={r.packSize} min={1} width="qty" />
					{/if}

					<SelectField
						label="Location"
						hideLabel
						bind:value={r.locationId}
						width="160px"
						placeholder="—"
						options={locationOptions}
					/>

					{#if directionOf(r) === 'none'}
						<span class="ro muted">No adjustment</span>
					{:else}
						<SelectField
							label="Reason"
							hideLabel
							value={r.reasonId}
							width="180px"
							placeholder={rerr === 'required' ? 'Reason required' : 'Select reason…'}
							error={rerr ? ' ' : undefined}
							options={reasonsFor(r)}
							onchange={(v) => (r.reasonId = v as string | null)}
						/>
					{/if}

					<button
						type="button"
						class="remove"
						title="Remove batch"
						aria-label="Remove batch"
						disabled={rows.length === 1 || !!r.id}
						onclick={() => removeRow(r.key)}
					>
						<Icon name="delete" size={16} />
					</button>
				</div>
				{#if rerr}
					<p class="rowerr" role="alert">
						{rerr === 'required'
							? 'A reason is required for this adjustment.'
							: "The selected reason doesn't match the adjustment direction."}
					</p>
				{/if}
			{/each}
		</div>

		<Button variant="ghost" compact onclick={addRow}>
			<Icon name="plus-circle" size={16} /> Add another batch
		</Button>
	{/if}

	{#if error}<p class="err" role="alert">⚠ {error}</p>{/if}

	{#snippet footer()}
		<Button variant="ghost" onclick={() => (open = false)}>Cancel</Button>
		<Button variant="primary" onclick={save} disabled={!canSave}>
			{saving ? 'Saving…' : isEdit ? 'Save changes' : 'Add to stocktake'}
		</Button>
	{/snippet}
</Modal>

<style>
	.results {
		margin-top: var(--space-3);
		max-height: 320px;
		overflow-y: auto;
		border: 1px solid var(--border-default);
		border-radius: var(--radius-control);
	}
	.hint {
		margin: 0;
		padding: var(--space-4);
		text-align: center;
		color: var(--text-secondary);
	}
	.result {
		display: flex;
		align-items: baseline;
		gap: var(--space-3);
		width: 100%;
		text-align: start;
		padding: var(--space-2) var(--space-3);
		background: none;
		border: 0;
		border-bottom: 1px solid var(--divider);
		cursor: pointer;
		color: var(--text-primary);
		font: inherit;
	}
	.result:last-child {
		border-bottom: 0;
	}
	.result:hover {
		background: var(--hover-overlay);
	}
	.code {
		font-variant-numeric: tabular-nums;
		color: var(--text-secondary);
		min-width: 88px;
	}
	.name {
		flex: 1;
	}
	.unit {
		color: var(--text-secondary);
		font-size: 13px;
	}
	.chosen {
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: var(--space-3);
		padding: var(--space-3);
		background: var(--surface-sunken);
		border-radius: var(--radius-control);
		margin-bottom: var(--space-4);
	}
	.chosen .code {
		margin-inline-end: var(--space-2);
	}
	.grid {
		display: flex;
		flex-direction: column;
		gap: var(--space-2);
		margin-bottom: var(--space-3);
	}
	.row {
		display: grid;
		grid-template-columns: 90px 120px 150px 90px 160px 180px 40px;
		align-items: center;
		gap: var(--space-3);
	}
	.row.head {
		font-size: var(--font-size-label);
		text-transform: uppercase;
		letter-spacing: 0.04em;
		color: var(--text-secondary);
	}
	.ro {
		font-size: 14px;
		color: var(--text-primary);
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}
	.ro.num {
		font-variant-numeric: tabular-nums;
		text-align: end;
	}
	.ro.muted {
		color: var(--text-secondary);
		font-size: 13px;
	}
	.sr {
		position: absolute;
		width: 1px;
		height: 1px;
		overflow: hidden;
		clip: rect(0 0 0 0);
	}
	.rowerr {
		margin: 0 0 var(--space-2);
		color: var(--state-error);
		font-size: 13px;
	}
	.remove {
		display: inline-flex;
		align-items: center;
		justify-content: center;
		min-width: 40px;
		height: 40px;
		border: 1px solid var(--border-default);
		border-radius: var(--radius-control);
		background: var(--surface-default);
		color: var(--state-error);
		cursor: pointer;
	}
	.remove:disabled {
		opacity: 0.4;
		cursor: not-allowed;
	}
	.err {
		margin: var(--space-3) 0 0;
		color: var(--state-error);
	}
	@media (max-width: 760px) {
		.row,
		.row.head {
			grid-template-columns: 1fr 1fr;
		}
		.row.head {
			display: none;
		}
	}
</style>

// solid/src/domain/stocktakes/StocktakeLineEditor.tsx
/**
 * S4 — Line editor (spec/stocktakes/05-ui-surface.md › S4, journeys J3/J4). The single surface
 * for entering line data (AC-D2): add/count an item's batches and set reason, batch, expiry,
 * location, pack size, prices, comment/note. A modal over S3. When adding, the item is chosen
 * from the catalogue (items already on the stocktake are excluded — AC-E3) and one or more new
 * batches can be entered; when editing an existing line the item is fixed. Reason requirement
 * and validity are surfaced per the adjustment direction (03 › reason rules) and block save.
 * In edit mode, previous/next move between lines without leaving the editor.
 */
import { type JSX, For, Index, Show, batch as solidBatch, createEffect, createMemo, createSignal, onCleanup } from 'solid-js';
import { Modal } from '../../ui/Modal';
import { Button, IconButton } from '../../ui/Button';
import { Icon } from '../../ui/Icon';
import { Popover } from '../../ui/Popover';
import { TextField } from '../../ui/inputs/TextField';
import { NumericField } from '../../ui/inputs/NumericField';
import { DateField } from '../../ui/inputs/DateField';
import { SelectField } from '../../ui/inputs/SelectField';
import { toast } from '../../ui/toast';
import { auth } from '../../state/auth';
import { batchStocktakeLines, type UpsertLineInput } from './api';
import { searchItems, type ItemSearchResult, type Ref } from './reference';
import { reasonError, adjustmentDirection } from './rules';
import type { ReasonOption, StocktakeLine } from './types';

interface BatchRow {
  key: number;
  lineId?: string;
  counted: number | null;
  batch: string;
  expiry: string | null;
  locationId: string;
  packSize: number | null;
  cost: number | null;
  sell: number | null;
  reasonId: string;
  comment: string;
  note: string;
  /** snapshot for the row (existing line's snapshot, else 0 for a new batch). */
  snapshot: number;
}

export interface LineEditorProps {
  stocktakeId: string;
  existingLine: StocktakeLine | null;
  existingItemIds: string[];
  reasons: ReasonOption[];
  locations: Ref[];
  /** Ordered sibling lines, for prev/next navigation in edit mode. */
  siblings?: StocktakeLine[];
  onNavigate?: (line: StocktakeLine) => void;
  onClose: () => void;
  onSaved: () => void;
}

let keySeq = 1;

function rowFromLine(line: StocktakeLine): BatchRow {
  return {
    key: keySeq++,
    lineId: line.id,
    counted: line.countedNumberOfPacks ?? null,
    batch: line.batch ?? '',
    expiry: line.expiryDate ?? null,
    locationId: line.location?.id ?? '',
    packSize: line.packSize ?? null,
    cost: line.costPricePerPack ?? null,
    sell: line.sellPricePerPack ?? null,
    reasonId: line.reasonOption?.id ?? '',
    comment: line.comment ?? '',
    note: line.note ?? '',
    snapshot: line.snapshotNumberOfPacks
  };
}
function blankRow(packSize: number | null): BatchRow {
  return {
    key: keySeq++,
    counted: null,
    batch: '',
    expiry: null,
    locationId: '',
    packSize,
    cost: null,
    sell: null,
    reasonId: '',
    comment: '',
    note: '',
    snapshot: 0
  };
}

export function StocktakeLineEditor(props: LineEditorProps): JSX.Element {
  const isEdit = () => !!props.existingLine;
  const [item, setItem] = createSignal<{ id: string; code: string; name: string; unitName?: string | null; defaultPackSize: number } | null>(
    props.existingLine ? { id: props.existingLine.itemId, code: props.existingLine.item.code, name: props.existingLine.itemName, unitName: props.existingLine.item.unitName, defaultPackSize: props.existingLine.item.defaultPackSize } : null
  );
  const [rows, setRows] = createSignal<BatchRow[]>(props.existingLine ? [rowFromLine(props.existingLine)] : []);
  const [saving, setSaving] = createSignal(false);

  // React to the edited line changing (prev/next navigation reuses this instance).
  createEffect(() => {
    const line = props.existingLine;
    if (line) {
      solidBatch(() => {
        setItem({ id: line.itemId, code: line.item.code, name: line.itemName, unitName: line.item.unitName, defaultPackSize: line.item.defaultPackSize });
        setRows([rowFromLine(line)]);
      });
    }
  });

  const reasonOptions = () => props.reasons.map((r) => ({ value: r.id, label: r.reason }));
  const locationOptions = () => props.locations.map((l) => ({ value: l.id, label: l.code ? `${l.name} (${l.code})` : l.name }));

  // Update by index. <Index> keys rows by position, so replacing a row object (immutable
  // update) updates the leaf bindings in place without recreating the DOM node — the focused
  // input keeps focus while typing (the alternative, <For>, keys by reference and would
  // recreate the row on every keystroke).
  const updateRow = (i: number, patch: Partial<BatchRow>) =>
    setRows((rs) => rs.map((r, idx) => (idx === i ? { ...r, ...patch } : r)));
  const addRow = () => setRows((rs) => [...rs, blankRow(item()?.defaultPackSize ?? null)]);
  const removeRow = (i: number) => setRows((rs) => rs.filter((_, idx) => idx !== i));

  // Reason feedback per row (03 › reason rules).
  const rowReasonError = (r: BatchRow): string | undefined => {
    const pseudo = {
      countedNumberOfPacks: r.counted,
      snapshotNumberOfPacks: r.snapshot,
      reasonOption: props.reasons.find((x) => x.id === r.reasonId) ?? null
    } as StocktakeLine;
    const e = reasonError(pseudo, props.reasons);
    if (e === 'AdjustmentReasonNotProvided') return 'A reason is required for this adjustment';
    if (e === 'AdjustmentReasonNotValid') return 'Reason not valid for this adjustment direction';
    return undefined;
  };
  const directionLabel = (r: BatchRow) => {
    const d = adjustmentDirection({ countedNumberOfPacks: r.counted, snapshotNumberOfPacks: r.snapshot });
    return d === 'positive' ? 'Stock up' : d === 'negative' ? 'Stock down' : '';
  };

  const canSave = createMemo(() => {
    if (!item()) return false;
    if (rows().length === 0) return false;
    return rows().every((r) => !rowReasonError(r));
  });

  const buildUpsert = (r: BatchRow): UpsertLineInput => {
    const u: UpsertLineInput = {
      stocktakeId: props.stocktakeId,
      countedNumberOfPacks: r.counted,
      batch: r.batch || undefined,
      packSize: r.packSize ?? undefined,
      costPricePerPack: r.cost ?? undefined,
      sellPricePerPack: r.sell ?? undefined,
      location: { value: r.locationId || null },
      reasonOptionId: r.reasonId || undefined,
      comment: r.comment || undefined,
      note: r.note || undefined,
      expiryDate: r.expiry ?? undefined
    };
    if (r.lineId) u.id = r.lineId;
    else u.itemId = item()!.id;
    return u;
  };

  const save = async (): Promise<boolean> => {
    if (!canSave()) return false;
    setSaving(true);
    try {
      const res = await batchStocktakeLines(auth.storeId, { upserts: rows().map(buildUpsert) });
      const failed = [...res.inserts, ...res.updates].filter((x) => x.errorType);
      if (failed.length) {
        toast(`Save failed: ${failed[0]!.errorType}`, 'error');
        return false;
      }
      return true;
    } catch {
      toast('Save failed', 'error');
      return false;
    } finally {
      setSaving(false);
    }
  };

  const onSaveClose = async () => {
    if (await save()) props.onSaved();
  };

  // Prev/next navigation (edit mode) — save current, then move to the sibling.
  const siblingIndex = createMemo(() => (props.siblings ?? []).findIndex((l) => l.id === props.existingLine?.id));
  const neighbour = (dir: 1 | -1) => (props.siblings ?? [])[siblingIndex() + dir];
  const navigate = async (dir: 1 | -1) => {
    const next = neighbour(dir);
    if (!next) return;
    if (await save()) props.onNavigate?.(next);
  };

  return (
    <Modal
      open
      title={isEdit() ? `Edit ${item()?.name ?? 'line'}` : 'Add item'}
      onClose={props.onClose}
      width="720px"
      footer={
        <>
          <Show when={isEdit() && (props.siblings?.length ?? 0) > 1}>
            <div class="editor-nav" style={{ 'margin-inline-end': 'auto' }}>
              <IconButton icon="arrow-left" label="Previous item" plain disabled={!neighbour(-1)} onClick={() => navigate(-1)} />
              <span class="hint">
                {siblingIndex() + 1} / {props.siblings!.length}
              </span>
              <IconButton icon="arrow-right" label="Next item" plain disabled={!neighbour(1)} onClick={() => navigate(1)} />
            </div>
          </Show>
          <Button variant="ghost" onClick={props.onClose}>
            Cancel
          </Button>
          <Button variant="primary" icon="save" busy={saving()} disabled={!canSave()} onClick={onSaveClose}>
            Save
          </Button>
        </>
      }
    >
      <div class="line-editor">
        {/* Item selector */}
        <Show
          when={!isEdit()}
          fallback={
            <div>
              <div class="field__label">Item</div>
              <div style={{ 'font-weight': 600 }}>
                {item()?.name} <span class="hint">({item()?.code})</span>
              </div>
              <Show when={item()?.unitName}>
                <div class="hint">Unit: {item()!.unitName}</div>
              </Show>
            </div>
          }
        >
          <ItemPicker
            excludeIds={props.existingItemIds}
            onPick={(it) =>
              solidBatch(() => {
                setItem(it);
                setRows([blankRow(it.defaultPackSize)]);
              })
            }
            selected={item()}
          />
        </Show>

        {/* Batch rows */}
        <Show when={item()}>
          <div class="editor-batches">
            <Index each={rows()}>
              {(row, i) => (
                <div class="batch-card">
                  <div class="batch-card__head">
                    <strong>{row().lineId ? `Batch ${row().batch || '—'}` : 'New batch'}</strong>
                    <Show when={!isEdit() && rows().length > 1}>
                      <button class="filter-chip__remove" type="button" aria-label="Remove batch" onClick={() => removeRow(i)}>
                        <Icon name="close" size={16} />
                      </button>
                    </Show>
                  </div>
                  <div class="batch-card__grid">
                    <NumericField label="Counted packs" value={row().counted} onInput={(v) => updateRow(i, { counted: v })} min={0} width="100%" />
                    <NumericField label="Pack size" value={row().packSize} onInput={(v) => updateRow(i, { packSize: v })} min={0} width="100%" />
                    <TextField label="Batch" value={row().batch} onInput={(v) => updateRow(i, { batch: v })} full />
                    <DateField label="Expiry" value={row().expiry} onChange={(v) => updateRow(i, { expiry: v })} width="100%" />
                    <SelectField label="Location" searchable value={row().locationId} onChange={(v) => updateRow(i, { locationId: v })} options={locationOptions()} placeholder="None" full />
                    <NumericField label="Cost / pack" value={row().cost} onInput={(v) => updateRow(i, { cost: v })} min={0} width="100%" />
                    <NumericField label="Sell / pack" value={row().sell} onInput={(v) => updateRow(i, { sell: v })} min={0} width="100%" />
                    <SelectField
                      label={`Reason${directionLabel(row()) ? ` · ${directionLabel(row())}` : ''}`}
                      value={row().reasonId}
                      onChange={(v) => updateRow(i, { reasonId: v })}
                      options={reasonOptions()}
                      placeholder="Select…"
                      error={rowReasonError(row())}
                      full
                    />
                    <div style={{ 'grid-column': '1 / -1' }}>
                      <TextField label="Comment" value={row().comment} onInput={(v) => updateRow(i, { comment: v })} full />
                    </div>
                  </div>
                </div>
              )}
            </Index>
            <Show when={!isEdit()}>
              <Button variant="ghost" icon="plus-circle" onClick={addRow}>
                Add another batch
              </Button>
            </Show>
          </div>
        </Show>
      </div>
    </Modal>
  );
}

/** Async catalogue item picker (S4 › Item selector). Debounced search excluding items already
 *  on the stocktake. */
function ItemPicker(props: {
  excludeIds: string[];
  selected: { id: string; name: string; code: string } | null;
  onPick: (item: ItemSearchResult) => void;
}): JSX.Element {
  const [open, setOpen] = createSignal(false);
  const [query, setQuery] = createSignal('');
  const [results, setResults] = createSignal<ItemSearchResult[]>([]);
  const [loading, setLoading] = createSignal(false);
  let timer: ReturnType<typeof setTimeout> | undefined;
  let searchEl: HTMLInputElement | undefined;

  const run = (term: string) => {
    if (timer) clearTimeout(timer);
    timer = setTimeout(async () => {
      setLoading(true);
      try {
        const items = await searchItems(auth.storeId, term);
        setResults(items.filter((i) => !props.excludeIds.includes(i.id)));
      } catch {
        setResults([]);
      } finally {
        setLoading(false);
      }
    }, 300);
  };
  onCleanup(() => timer && clearTimeout(timer));

  return (
    <div class="field field--full">
      <span class="field__label">Item</span>
      <Popover
        open={open()}
        onClose={() => setOpen(false)}
        matchWidth
        trigger={
          <button
            type="button"
            class="control select-trigger"
            data-popover-trigger
            aria-haspopup="listbox"
            aria-expanded={open()}
            onClick={() => {
              setOpen(!open());
              if (!open()) return;
              queueMicrotask(() => searchEl?.focus());
              if (!results().length) run('');
            }}
          >
            <span class={`select-trigger__value${props.selected ? '' : ' is-placeholder'}`}>
              {props.selected ? `${props.selected.name} (${props.selected.code})` : 'Search the catalogue…'}
            </span>
            <Icon name="search" size={16} class="select-trigger__chevron" />
          </button>
        }
      >
        <div>
          <div class="select-search">
            <input
              ref={searchEl}
              class="control control--compact"
              type="text"
              placeholder="Search by code or name…"
              value={query()}
              onInput={(e) => {
                setQuery(e.currentTarget.value);
                run(e.currentTarget.value);
              }}
            />
          </div>
          <ul class="menu" role="listbox" aria-label="Items">
            <Show when={!loading()} fallback={<li class="menu-item"><span class="spinner" /> Searching…</li>}>
              <Show when={results().length} fallback={<li class="menu-item" style={{ color: 'var(--text-secondary)' }}>No matching items</li>}>
                <For each={results()}>
                  {(it) => (
                    <li role="none">
                      <button
                        type="button"
                        role="option"
                        class="menu-item"
                        onClick={() => {
                          props.onPick(it);
                          setOpen(false);
                        }}
                      >
                        <span class="menu-item__label">
                          {it.name} <span class="hint">({it.code})</span>
                        </span>
                      </button>
                    </li>
                  )}
                </For>
              </Show>
            </Show>
          </ul>
        </div>
      </Popover>
    </div>
  );
}
