// svelte/src/lib/stocktakes/StocktakeCreateModal.svelte
<script lang="ts">
	import Modal from '$lib/ui/Modal.svelte';
	import Button from '$lib/ui/Button.svelte';
	import TextField from '$lib/ui/inputs/TextField.svelte';
	import SelectField from '$lib/ui/inputs/SelectField.svelte';
	import DateField from '$lib/ui/inputs/DateField.svelte';
	import Toggle from '$lib/ui/inputs/Toggle.svelte';
	import { auth } from '$lib/auth/auth.svelte';
	import { insertStocktake } from './api';
	import { listLocations, listMasterLists, estimateLineCount, type Ref } from './reference';
	import type { CreateMode } from './types';

	let { open = $bindable(false), onCreated }: { open?: boolean; onCreated?: (n: number) => void } =
		$props();

	type Mode = Exclude<CreateMode, 'initial'>;
	let mode = $state<Mode>('full');
	let description = $state('');
	// Full
	let includeAllItems = $state(false);
	// Filtered
	let masterListId = $state<string | null>(null);
	let locationId = $state<string | null>(null);
	let expiresBefore = $state<string | null>(null);
	let includeAllMasterListItems = $state(false);

	let locations = $state<Ref[]>([]);
	let masterLists = $state<(Ref & { linesCount: number })[]>([]);
	let estimate = $state<number | null>(null);
	let estimating = $state(false);
	let saving = $state(false);
	let error = $state<string | null>(null);

	// Load reference data when the modal opens.
	$effect(() => {
		if (!open) return;
		const storeId = auth.storeId;
		listLocations(storeId).then((l) => (locations = l)).catch(() => {});
		listMasterLists(storeId).then((m) => (masterLists = m)).catch(() => {});
	});

	// Switching mode resets the other modes' inputs (spec S2).
	function setMode(m: Mode) {
		mode = m;
		includeAllItems = false;
		masterListId = null;
		locationId = null;
		expiresBefore = null;
		includeAllMasterListItems = false;
	}

	// Recompute the estimate as inputs change.
	$effect(() => {
		if (!open) return;
		const params = {
			mode,
			isAllItemsStocktake: includeAllItems,
			masterListId: masterListId ?? undefined,
			locationId: locationId ?? undefined,
			expiresBefore: expiresBefore ?? undefined,
			includeAllMasterListItems
		};
		const storeId = auth.storeId;
		const ml = masterLists;
		estimating = true;
		estimateLineCount(storeId, params, ml)
			.then((n) => (estimate = n))
			.finally(() => (estimating = false));
	});

	async function confirm() {
		saving = true;
		error = null;
		try {
			const input =
				mode === 'blank'
					? { createBlankStocktake: true, description: description || undefined }
					: mode === 'full'
						? { isAllItemsStocktake: includeAllItems || undefined, description: description || undefined }
						: {
								masterListId: masterListId ?? undefined,
								locationId: locationId ?? undefined,
								expiresBefore: expiresBefore ?? undefined,
								includeAllMasterListItems: includeAllMasterListItems || undefined,
								description: description || undefined
							};
			const { stocktakeNumber } = await insertStocktake(auth.storeId, input);
			open = false;
			onCreated?.(stocktakeNumber);
		} catch (e) {
			error = e instanceof Error ? e.message : String(e);
		} finally {
			saving = false;
		}
	}

	const modes: { value: Mode; label: string; hint: string }[] = [
		{ value: 'full', label: 'Full', hint: 'Count everything on hand.' },
		{ value: 'filtered', label: 'Filtered', hint: 'Count a subset by list, location or expiry.' },
		{ value: 'blank', label: 'Blank', hint: "I'll add items myself." }
	];
</script>

<Modal bind:open title="New stocktake" width="560px">
	<div class="modes" role="radiogroup" aria-label="Creation mode">
		{#each modes as m (m.value)}
			<button
				type="button"
				role="radio"
				aria-checked={mode === m.value}
				class="mode"
				class:active={mode === m.value}
				onclick={() => setMode(m.value)}
			>
				<span class="mode-label">{m.label}</span>
				<span class="mode-hint">{m.hint}</span>
			</button>
		{/each}
	</div>

	<div class="fields">
		<TextField label="Description" bind:value={description} width="full" placeholder="Optional label" />

		{#if mode === 'full'}
			<Toggle label="Include items with no stock on hand" bind:checked={includeAllItems} />
		{:else if mode === 'filtered'}
			<SelectField
				label="Master list"
				bind:value={masterListId}
				width="full"
				placeholder="Any"
				options={masterLists.map((m) => ({ value: m.id, label: m.name }))}
			/>
			{#if masterListId}
				<Toggle
					label="Include all master-list items (incl. zero stock)"
					bind:checked={includeAllMasterListItems}
				/>
			{/if}
			<SelectField
				label="Location"
				bind:value={locationId}
				width="full"
				placeholder={locations.length ? 'Any' : 'No locations in this store'}
				options={locations.map((l) => ({ value: l.id, label: l.name || l.code || l.id }))}
			/>
			<DateField label="Expires before" bind:value={expiresBefore} />
		{/if}
	</div>

	<div class="feedback" aria-live="polite">
		{#if mode === 'blank'}
			A blank stocktake — no lines are generated.
		{:else if estimating}
			Estimating…
		{:else if estimate != null}
			Will generate ≈ <strong>{estimate.toLocaleString()}</strong> line{estimate === 1 ? '' : 's'}.
			{#if includeAllItems || includeAllMasterListItems}<span class="muted"> (plus zero-stock items)</span>{/if}
		{:else}
			Estimate unavailable.
		{/if}
	</div>

	{#if error}<p class="err" role="alert">⚠ {error}</p>{/if}

	{#snippet footer()}
		<Button variant="ghost" onclick={() => (open = false)}>Cancel</Button>
		<Button variant="primary" onclick={confirm} disabled={saving}>
			{saving ? 'Creating…' : 'Create'}
		</Button>
	{/snippet}
</Modal>

<style>
	.modes {
		display: grid;
		grid-template-columns: repeat(3, 1fr);
		gap: var(--space-2);
		margin-bottom: var(--space-4);
	}
	.mode {
		display: flex;
		flex-direction: column;
		gap: var(--space-1);
		text-align: start;
		padding: var(--space-3);
		border: 1px solid var(--border-default);
		border-radius: var(--radius-control);
		background: var(--surface-default);
		color: var(--text-primary);
		cursor: pointer;
	}
	.mode.active {
		border-color: var(--brand-primary);
		background: var(--brand-primary-subtle);
	}
	.mode-label {
		font-weight: 600;
	}
	.mode-hint {
		font-size: 12px;
		color: var(--text-secondary);
	}
	.fields {
		display: flex;
		flex-direction: column;
		gap: var(--space-4);
	}
	.feedback {
		margin-top: var(--space-4);
		padding: var(--space-3);
		background: var(--surface-sunken);
		border-radius: var(--radius-control);
		font-size: 14px;
	}
	.muted {
		color: var(--text-secondary);
	}
	.err {
		margin: var(--space-3) 0 0;
		color: var(--state-error);
	}
</style>

// solid/src/domain/stocktakes/StocktakeCreateModal.tsx
/**
 * S2 — Create flow (spec/stocktakes/05-ui-surface.md › S2, journey J2). Pick a mode
 * (Full / Filtered / Blank, mutually exclusive — switching resets the other inputs), set its
 * parameters, and see an estimated line count (or a blank notice) before confirming. On
 * confirm the stocktake is created (NEW) and the caller navigates to its detail view (S3).
 */
import { type JSX, Show, batch, createMemo, createResource, createSignal } from 'solid-js';
import { Modal } from '../../ui/Modal';
import { Button } from '../../ui/Button';
import { TextField } from '../../ui/inputs/TextField';
import { DateField } from '../../ui/inputs/DateField';
import { SelectField, type SelectOption } from '../../ui/inputs/SelectField';
import { Toggle } from '../../ui/inputs/Toggle';
import { toast } from '../../ui/toast';
import { auth } from '../../state/auth';
import { insertStocktake } from './api';
import { listLocations, listMasterLists, listVvmStatuses, estimateLineCount, type Ref } from './reference';
import type { CreateMode, CreateStocktakeInput } from './types';

export function StocktakeCreateModal(props: {
  open: boolean;
  onClose: () => void;
  onCreated: (stocktakeNumber: number) => void;
}): JSX.Element {
  const [mode, setMode] = createSignal<Exclude<CreateMode, 'initial'>>('full');
  const [description, setDescription] = createSignal('');
  const [comment, setComment] = createSignal('');
  const [isAllItems, setIsAllItems] = createSignal(false);
  const [masterListId, setMasterListId] = createSignal('');
  const [locationId, setLocationId] = createSignal('');
  const [vvmStatusId, setVvmStatusId] = createSignal('');
  const [expiresBefore, setExpiresBefore] = createSignal<string | null>(null);
  const [includeAllMaster, setIncludeAllMaster] = createSignal(false);
  const [saving, setSaving] = createSignal(false);

  // Reference data loaded lazily when the modal opens.
  const [refs] = createResource(
    () => (props.open ? auth.storeId : undefined),
    async (storeId) => {
      const [locations, masterLists, vvm] = await Promise.all([
        listLocations(storeId).catch(() => [] as Ref[]),
        listMasterLists(storeId).catch(() => [] as (Ref & { lineCount: number })[]),
        listVvmStatuses(storeId).catch(() => [] as Ref[])
      ]);
      return { locations, masterLists, vvm };
    }
  );

  const opt = (r: Ref): SelectOption => ({ value: r.id, label: r.code ? `${r.name} (${r.code})` : r.name });

  const resetOthers = () => {
    setIsAllItems(false);
    setMasterListId('');
    setLocationId('');
    setVvmStatusId('');
    setExpiresBefore(null);
    setIncludeAllMaster(false);
  };
  const pickMode = (m: Exclude<CreateMode, 'initial'>) => {
    if (m === mode()) return;
    batch(() => {
      setMode(m);
      resetOthers();
    });
  };

  const estimateParams = createMemo(() => ({
    mode: mode(),
    isAllItemsStocktake: isAllItems(),
    locationId: locationId() || undefined,
    masterListId: masterListId() || undefined,
    includeAllMasterListItems: includeAllMaster(),
    expiresBefore: expiresBefore() || undefined
  }));

  const [estimate] = createResource(
    () => (props.open && mode() !== 'blank' ? estimateParams() : undefined),
    (p) => estimateLineCount(auth.storeId, p, refs()?.masterLists ?? [])
  );

  const create = async () => {
    setSaving(true);
    const base: CreateStocktakeInput = {
      description: description() || undefined,
      comment: comment() || undefined
    };
    if (mode() === 'full') base.isAllItemsStocktake = isAllItems();
    else if (mode() === 'blank') base.createBlankStocktake = true;
    else {
      base.masterListId = masterListId() || undefined;
      base.locationId = locationId() || undefined;
      base.vvmStatusId = vvmStatusId() || undefined;
      base.expiresBefore = expiresBefore() || undefined;
      base.includeAllMasterListItems = includeAllMaster();
    }
    try {
      const res = await insertStocktake(auth.storeId, base);
      if (res.ok) {
        toast(`Stocktake #${res.stocktakeNumber} created`, 'success');
        props.onCreated(res.stocktakeNumber);
        reset();
      } else {
        toast(`Could not create stocktake (${res.errorType})`, 'error');
      }
    } catch {
      toast('Could not create stocktake', 'error');
    } finally {
      setSaving(false);
    }
  };

  const reset = () => {
    batch(() => {
      setMode('full');
      setDescription('');
      setComment('');
      resetOthers();
    });
  };
  const close = () => {
    if (saving()) return;
    props.onClose();
  };

  const MODES: { value: Exclude<CreateMode, 'initial'>; label: string }[] = [
    { value: 'full', label: 'Full' },
    { value: 'filtered', label: 'Filtered' },
    { value: 'blank', label: 'Blank' }
  ];

  return (
    <Modal
      open={props.open}
      title="New stocktake"
      onClose={close}
      width="560px"
      footer={
        <>
          <Button variant="ghost" onClick={close}>
            Cancel
          </Button>
          <Button variant="primary" busy={saving()} icon="plus-circle" onClick={create}>
            Create
          </Button>
        </>
      }
    >
      <div class="line-editor">
        <div role="group" aria-label="Creation mode" style={{ display: 'flex', gap: '8px' }}>
          {MODES.map((m) => (
            <button
              type="button"
              class={`btn btn--compact ${mode() === m.value ? 'btn--primary' : 'btn--secondary'}`}
              aria-pressed={mode() === m.value}
              onClick={() => pickMode(m.value)}
            >
              {m.label}
            </button>
          ))}
        </div>

        <div class="form-grid">
          <div class="form-grid--full">
            <TextField label="Description" value={description()} onInput={setDescription} placeholder="Optional label" full />
          </div>
          <div class="form-grid--full">
            <TextField label="Comment" value={comment()} onInput={setComment} multiline rows={2} full />
          </div>
        </div>

        <Show when={mode() === 'full'}>
          <Toggle checked={isAllItems()} onChange={setIsAllItems} label="Include items with no stock on hand" />
        </Show>

        <Show when={mode() === 'filtered'}>
          <div class="form-grid">
            <SelectField
              label="Master list"
              searchable
              value={masterListId()}
              onChange={setMasterListId}
              options={(refs()?.masterLists ?? []).map(opt)}
              placeholder="Any"
              full
            />
            <SelectField
              label="Location"
              searchable
              value={locationId()}
              onChange={setLocationId}
              options={(refs()?.locations ?? []).map(opt)}
              placeholder="Any"
              full
            />
            <SelectField
              label="VVM status"
              value={vvmStatusId()}
              onChange={setVvmStatusId}
              options={(refs()?.vvm ?? []).map(opt)}
              placeholder="Any"
              full
            />
            <DateField label="Expires before" value={expiresBefore()} onChange={setExpiresBefore} width="100%" />
            <div class="form-grid--full">
              <Toggle
                checked={includeAllMaster()}
                onChange={setIncludeAllMaster}
                disabled={!masterListId()}
                label="Include all master-list items (incl. zero stock)"
              />
            </div>
          </div>
        </Show>

        <Show
          when={mode() !== 'blank'}
          fallback={<p class="hint">A blank stocktake has no lines — you add items yourself.</p>}
        >
          <p class="hint">
            <Show when={estimate.loading} fallback={<>Estimated lines: <strong>{estimate() ?? '—'}</strong></>}>
              Estimating…
            </Show>
          </p>
        </Show>
      </div>
    </Modal>
  );
}
